Fix 591
OWASP/wstg pull request #1074
Opened 2023-06-30 09:42 UTC by manindar-mohan

This PR covers issue #591.

- [ ] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

- Moved all XSS to chapter 11, client-side testing
- added sub-sections for XSS

Thank you for your contribution!

2023-06-30 14:54 UTC, kingthorin commented
@ThunderSon since this is essentially a breaking change shall we delay it till 5.x?

2023-06-30 18:22 UTC, ThunderSon commented
@kingthorin 💯 , definitely a breaking change for the IDs. Let's do a review and finalize things and set it for v5

2023-06-30 19:10 UTC, kingthorin commented
Thanks

2023-07-03 12:51 UTC, manindar-mohan commented
I have fixed almost all the mistakes, yet some are popping up on adjacent pushes, should I fix them all? these mistakes are from the old files that I haven’t changed. @kingthorin

2023-07-03 13:08 UTC, kingthorin commented
I’ll have a look shortly. It’s probably fine.

2023-07-08 16:35 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_HTTP_Verb_Tampering.md
> +|WSTG-INPV-01|
@kingthorin I wouldn't put this as Id number 1. I feel with v5, we can take it out, no?
This will impact all the other docs, so I think we need to decide on this.

2023-07-08 16:42 UTC, ThunderSon requested changes

2023-07-08 16:42 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/17-Testing_for_Server-side_Template_Injection.md
> +- [Server-ide Template Injection: from detection to Remote shell](https://www.okiok.com/server-side-template-injection-from-detection-to-remote-shell/)
```suggestion
- [Server-side Template Injection: from detection to Remote shell](https://www.okiok.com/server-side-template-injection-from-detection-to-remote-shell/)
```

2023-07-08 16:42 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/01.3-Testing_for_DOM-based_Cross_Site_Scripting.md
> +## References
References must be at the end of the document, not at the start. Any reason for moving them here?

2023-07-09 00:44 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_HTTP_Verb_Tampering.md
> +|WSTG-INPV-01|
You mean this specific topic?

2023-07-24 12:52 UTC, kingthorin commented
Why did you close this?

2023-07-25 07:02 UTC, manindar-mohan commented
Sorry, that was a mistake, didn’t know this happened.

2025-06-27 06:22 UTC, manindar-mohan commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/01.3-Testing_for_DOM-based_Cross_Site_Scripting.md
> +## References
Done.

2025-07-01 11:30 UTC, kingthorin commented
Some of the link checks will be FPs, don't get too worried about it.

2026-08-26 13:46 UTC, kingthorin commented
Thanks for tackling this. With the current glut of conflicts I'm just going to have an agent tackle it.

2026-08-26 13:46 UTC, closed without merging