Add tests for Archive Directory Traversal
OWASP/wstg pull request #1138
Opened 2024-04-17 18:52 UTC by doverh

This PR covers issue #845 

- [X] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

- Add tests for Archive Directory Traversal
- Update references and add how to(example youtube)

Thank you for your contribution!

2024-04-17 20:18 UTC, kingthorin commented
Please address the bot's feedback. (Yes we know some of it might be pre-existing g.)

2024-04-17 21:41 UTC, doverh commented
@kingthorin checks passing now. Let me know if I need to revert any of those zip --> ZIP changes.

2024-04-17 21:53 UTC, kingthorin commented
That stuff looks good to me. There are a few parts that read a bit awkwardly but I"ll do a review tomorrow and point them out or suggest alternative wording.

2024-04-18 01:26 UTC, doverh commented
@kingthorin the text was indeed awkward. I sent a new version trying to bring it closer to the wstg style guide.

2024-04-18 17:06 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- Include a unit test to upload an infected compressed file on the extraction method.
```suggestion
- Include a unit test to upload an infected compressed file then execute the extraction method.
```

2024-04-18 17:06 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- Validate that libraries being used have been [patched for this vulnerability.](https://github.com/snyk/ZIP-slip-vulnerability#affected-libraries)
ZIP in the URL can be lower cased. (If the bot still complains I'll deal with it)

2024-04-18 17:06 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +```
Again probably doesn't need line numbers.

2024-04-18 17:06 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- [ZIP Slip](https://res.cloudinary.com/snyk/image/upload/v1528192501/ZIP-slip-vulnerability/technical-whitepaper.pdf)
In the URL can likely be lower cased.

2024-04-18 19:18 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +If the application extracts archives (such as ZIP files), then it may be possible to write to unintended locations using directory traversal. This can be exploited by uploading a malicious ZIP file t
Reverted!

2024-04-18 19:18 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +2. A functionality, that is required to extract compressed files, either using custom code or a library. Archive Directory Traversal vulnerability exists when the extraction functionality don’t valid
Done!

2024-04-18 19:19 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- Validate that libraries being used have been [patched for this vulnerability.](https://github.com/snyk/ZIP-slip-vulnerability#affected-libraries)
Reverted!

2024-04-18 19:19 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +```
Line number removed!

2024-04-18 19:20 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- [ZIP Slip](https://res.cloudinary.com/snyk/image/upload/v1528192501/ZIP-slip-vulnerability/technical-whitepaper.pdf)
Done!

2024-04-18 19:20 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- Include a unit test to upload an infected compressed file on the extraction method.
Done!

2024-04-18 19:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +When this file is uploaded, it should be detected and quarantined or deleted by the  application. Depending on how the application processes the file, it may not be obvious whether this has taken pla
Still

2024-04-18 19:46 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +1. A malicious archive, that extracted breaks out of the target directory. A compressed file could contains two files: a “notinfected.sh” file, extracted into the target directory, and a “infected.sh
The text needs a tweak too

2024-04-18 19:46 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +2. A functionality, that is required to extract compressed files, either using custom code or a library. Archive Directory Traversal vulnerability exists when the extraction functionality don’t valid
don't ↔️ doesn't

2024-04-22 13:51 UTC, kingthorin commented
Thanks, sorry I wasn't able to tackle it over the weekend. Will try to get it knocked off later today.

2024-04-23 09:56 UTC, rbsec reviewed
I've added a few comments based on my thoughts - I think that it's a good thing test to add, but we don't really give enough details here to allow someone reading the guide to actual test for this.

2024-04-23 09:56 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +1. A malicious archive that breaks out of the target directory when extracted. This malicious archive can contain two files: a 'notinfected.sh' file, extracted into the target directory, and also an
Including the two separate files in a directory is a good way to test this - but I wonder if `infected.sh` is a sensible filename? We don't need it to be a `.sh` file to prove the concept, and a sysadmin finding a file called `infected.sh` on their system is likely to cause unintended issues.

The two files could just as easily be called `base` and `traversal` or something more neutral, that's less likely to cause a panic.

2024-04-23 09:56 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- Upload a malicious ZIP file and try to remote access this file when upload is completed.  [Watch it in action here](https://www.youtube.com/watch?v=l1MT5lr4p9o)
I don't really see what a YouTube video adds to this? If the explanation in the WSTG isn't detailed enough then we should expand it - it's not use if I'm trying to test for this vulnerability in an environment where I don't have Internet access and the WSTG just says "go on YouTubeand watch this video".

So something like

* Create a ZIP containing two files - with with a traversed path such as `../../traversed` and one without `base`.
* Upload the file to the application.
* Verify that the two files are located within different folders on the web server after the archive has been extracted.

It would also be useful to provide some guidance on how you actually create a ZIP archive to use for this.

2024-04-23 09:56 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +    }
This isn't really a "testing technique", and seems a bit too specific to in the WSTG as a recommendation.

2024-04-23 09:56 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +            ZipEntry e ​=​entries.nextElement();
The space before the `=` but not after looks weird to me - is this a Java thing?

2024-04-23 09:56 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +If the application extracts archives (such as ZIP files), then it may be possible to write to unintended locations using directory traversal. This can be exploited by uploading a malicious ZIP file t
We already have a reference to the paper in the references section at the bottom, so I don't really think that we need another one here? Or if this is a better link, then replace the other reference with it.

2024-04-23 19:58 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +1. A malicious archive that breaks out of the target directory when extracted. This malicious archive can contain two files: a 'notinfected.sh' file, extracted into the target directory, and also an
It makes sense to me and I renamed them.

2024-04-23 20:11 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +    }
@rbsec  You are right, after reviewing it it looks more a remediation. Should we move it to remediation section instead?

2024-04-23 20:34 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        jar -tvf 'zip file name'
You could use inline code fences if that makes more sense. (Single backtick before and after)

2024-04-23 20:38 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        jar -tvf 'zip file name'
Like:
&#96;`jar -tvf <zip file name>`&#96;

2024-04-23 20:43 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +    }
@doverh most of the other remediation sections in the WSTG are more general - usually a few bullet points giving a high level explanation of how to fix the issue, rather than specific code samples. This means that they're more generally applicable, whereas this kind of code sample is only really useful if they're using the specific language and framework of that code.

So perhaps taking out the code block, but giving a brief explanation of what they should do to fix it in the remediation section would be better?

2024-04-23 23:03 UTC, doverh commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +    }
@rbsec I reviewed File Upload Cheat Sheet  and it brings sections with instructions on File Upload Protection and Filename Sanitization that present a general level explanation for the Java code I share as vulnerable. Do you believe this is adequate?

2024-04-23 23:15 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +    Enumeration<ZipEntry>entries=​​zip​.g​etEntries();
```suggestion
    Enumeration<ZipEntry> entries =​ ​zip​.g​etEntries(); 
```

2024-04-23 23:15 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        'ZIP -r <zip_filename> <directoty_name>'
```suggestion
        'zip -r <zip_filename> <directoty_name>'
```

2024-04-23 23:16 UTC, kingthorin approved these changes
LGTM

2024-04-23 23:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        'zip -r <zip_filename> <directoty_name>'
```suggestion
        `zip -r <zip_filename> <directoty_name>`
```

2024-04-23 23:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        'mkdir <zip_folder>'
```suggestion
        `mkdir <zip_folder>`
```

2024-04-23 23:18 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        'touch base.txt'
```suggestion
        `touch base.txt`
```

2024-04-23 23:18 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        'touch ../../../../../../../../tmp/traversed'
```suggestion
        `touch ../../../../../../../../tmp/traversed`
```

2024-04-23 23:18 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        echo 'Your message here'
```suggestion
        `echo 'Your message here'`
```

2024-04-23 23:18 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        'jar -tvf <zip_filename>'
```suggestion
        `jar -tvf <zip_filename>`
```

2024-04-23 23:20 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        echo 'Your message here'
```suggestion
        `echo 'Your message here'`
```

2024-04-24 09:34 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +        `zip -r <zip_filename> <directoty_name>`
I don't think these instructions actually work, because you're just creating a zip of the folder here, rather than the file and a traversed path. I think you need to do something like this:

```
~$ mkdir -p a/b/c
~$ echo base > a/b/c/base
~$ echo traversed > traversed
~$ tree
.
├── a
│   └── b
│       └── c
│           └── base
└── traversed

~$ cd a/b/c
~/a/b/c$ zip test.zip base ../../../traversed
  adding: base (stored 0%)
  adding: ../../../traversed (stored 0%)

And then to verify:

~/a/b/c$ unzip -l test.zip
Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        5  2024-04-24 10:30   base
       10  2024-04-24 10:30   ../../../traversed
---------                     -------
       15                     2 files
```

Perhaps with a note that you may need more or less levels of directories, depending on how far you need to traverse. And since we're using `zip` to create the archive, it seems sensible to use `unzip` to verify it rather than `jar`. The tree command isn't needed (and could perhaps be removed) - it's more just to show the structure we're creating.

2024-04-24 09:36 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +    }
If we can link to something like a cheat sheet in the recommendations that's always good.

2024-04-24 22:14 UTC, ThunderSon requested changes
Slightly late review, let me know if any of my recommendations don't make sense. Hopefully we can merge this afterwards :)
Thank you for your contributions!

2024-04-24 22:14 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +    `~$ nzip -l test.zip`
Gave it a small clean up and transformed into one script that can be followed through the comments, as currently it's getting badly transformed into markdown.
```suggestion
```bash
# Open a new terminal and create a tree structure
# (more directory levels might be required based on the system being targeted)
mkdir -p a/b/c
# Create a base file
echo 'base' > a/b/c/base
# Create a traversed file
echo 'traversed' > traversed
# You can double check the tree structure using `tree` at this stage
# Navigate to a/b/c root directory
cd a/b/c
# Compress the files
zip test.zip base ../../../traversed
# Verify compressed files content
nzip -l test.zip
```
```

2024-04-24 22:14 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +- Validate that libraries being used have been [patched for this vulnerability.](https://github.com/snyk/zip-slip-vulnerability#affected-libraries)
We recommend these bits across the book as a whole, and this can be applied to all the test cases, whether it's discussing a SCA integration (so Snyk as you reference it), or through unit tests, so we don't need to mention it within a subcategory of a test file.
```suggestion
```

2024-04-25 19:53 UTC, rbsec commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +nzip -l test.zip
Typo, should be `unzip`

2024-04-25 19:55 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +nzip -l test.zip
I think after that line there's a missing triple quote as well

2024-04-25 20:02 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
> +nzip -l test.zip
Ya there should be triple backticks on the next line to end the bash code fence.

2024-04-28 02:17 UTC, kingthorin approved these changes
LGTM

2024-04-29 22:34 UTC, ThunderSon approved these changes
Thank you for the work here, this looks good to go!

2024-04-29 22:34 UTC, merged