merging files for bypassing authorization scheme
OWASP/wstg pull request #467
Opened 2020-05-06 16:18 UTC by DomKoe

This PR covers issue #265 and #407.

**What did this PR accomplish?**

- Merged the necessary files
- Added sentences, changed the order of the document and added different headings.

More can be added, if you have any wished what topics / specific cases you want to have added please let me know.

2020-05-06 16:33 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +|--------------|
These two changes should be reverted.

2020-05-06 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +In the following the most common approaches to bypassing authorization scheme will be shown and explained. First the horizontal and vertical bypassing approach and some more specific testings, like f
```suggestion
In the following are the most common approaches to bypassing authorization schemes will be shown and explained. First the horizontal, and vertical bypass approaches, then some more specific scenarios.
```

2020-05-06 16:36 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +#### How to test
```suggestion
#### How to Test
```

2020-05-06 16:37 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +1. Register/generate two users with the same role.
```suggestion
1. Register/generate two users.
```

The lead-in states "For each role" so it's clear this refers to a single roll.

2020-05-06 16:37 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +2. Generate and keep two different session tokens by authenticating the application (one session token for each user).
```suggestion
2. Generate and keep two different session tokens by authenticating (one session token for each user).
```

2020-05-06 16:38 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +4. An application will be considered vulnerable if the responses are the same, contain same private data or indicate successful operation on other users resource or data.
```suggestion
4. An application will be considered vulnerable if the responses are the same, contain same private data or indicate successful operation on other users' resource or data.
```

2020-05-06 16:38 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example, suppose that the 'viewCCpincode.jsp' function is part of every account menu of the application with the same role, and it is possible to access it by requesting the following URL:
```suggestion
For example, suppose that the `viewCCpincode.jsp` function is part of every account menu of the application with the same role, and it is possible to access it by requesting the following URL:
```

2020-05-06 16:39 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +If the response of the attacker’s request contains the same data (“pincode”:8432) the application is vulnerable. One can follow the same logic and the mentioned steps to replicate this testing approa
```suggestion
If the response of the attacker’s request contains the same data `(“pincode”:8432`) the application is vulnerable. One can follow the same logic and the mentioned steps to replicate this testing approach.
```

2020-05-06 16:40 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +The following table illustrates the system role on banking site. Each role bind with specific permissions for the event menu functionality:
```suggestion
The following table illustrates the system role on banking site. Each role binds with specific permissions for the event menu functionality:
```

2020-05-06 16:42 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example, suppose that the 'AddUser.jsp' function is part of the administrative menu of the application, and it is possible to access it by requesting the following URL:
This should be restored to proper code fencing.

2020-05-06 16:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +Further questions would be going into the following direction:
```suggestion
Further questions or considerations would go in the following direction:
```

2020-05-06 16:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example analyze an application that uses a shared directory to store temporary PDF files for different users. Suppose that documentABC.pdf should be accessible only by the user test1 with roleA.
This should be restored to proper code fencing.

2020-05-06 16:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +Some applications support non-standard headers such as X-Original-URL or X-Rewrite-URL in order to allow overriding the target URL in requests with the one specified in the header value.
This should be restored to proper code fencing.

2020-05-06 16:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +To detect the support for the header X-Original-URL or X-Rewrite-URL, the following steps can be applied.
This should be restored to proper code fencing.

2020-05-06 16:44 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +Once the support for the header X-Original-URL or X-Rewrite-URL was validated then the tentative of bypass against the access control restriction can be leveraged by sending the expected request to t
This should be restored to proper code fencing.

2020-05-06 16:44 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +[OWASP Application Security Verification Standard 3.0.1](https://github.com/OWASP/ASVS/tree/master/3.0.1), V4.1, 4.4, 4.9, 4.16.
Is there a reason to use 3.0.1 and not v4?

2020-06-14 11:25 UTC, kingthorin commented
@DomKoe are you planning to finish this?

2020-06-23 16:50 UTC, DomKoe commented
Yes, I will be on it.

2020-07-14 02:05 UTC, kingthorin commented
@DomKoe still planning to finish this?

2020-08-04 16:12 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +[OWASP Application Security Verification Standard 3.0.1](https://github.com/OWASP/ASVS/tree/master/3.0.1), V4.1, 4.4, 4.9, 4.16.
Updated it to v4 and changed the link

2020-08-04 16:13 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +#### How to test
Done

2020-08-04 16:14 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +|--------------|
Done

2020-08-04 16:15 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example analyze an application that uses a shared directory to store temporary PDF files for different users. Suppose that documentABC.pdf should be accessible only by the user test1 with roleA.
I used single back ticks again for the proper code fencing. If there is a different way, please let me know. I oriented myself on this https://community.openhab.org/t/how-to-use-code-fences/38383.

2020-08-04 16:15 UTC, DomKoe commented
Sorry for the hold up.

2020-08-04 16:22 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +
Seems like something is up with your merge/rebase

2020-08-04 17:48 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +- [Port Swigger Burp Suite](<https://portswigger.net/burp>
```suggestion
- [Port Swigger Burp Suite](https://portswigger.net/burp)
```

2020-08-04 17:50 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +[OWASP Application Security Verification Standard 3.0.1](https://github.com/OWASP/ASVS/tree/master/4.0), V4.1, 4.4, 4.9, 4.16.
The text says "3.0.1" but then links 4.0? Also they've recently published a [reference standard](https://github.com/OWASP/ASVS/#how-to-reference-asvs-requirements) which should be used here.

2020-08-05 17:07 UTC, kingthorin commented
Okay the last part that I see is that if this is merging content then the other content should be replaced (more than one file should be impacted here.)

If this replaces (merges) an entire scenario then a placeholder can be setup similar to: https://github.com/OWASP/wstg/search?q=merged&unscoped_q=merged

2020-08-05 18:28 UTC, DomKoe commented
It does not, the merge was my bad.

2020-08-05 19:14 UTC, kingthorin commented
So is there more work coming, or should the #407 references be removed?

2020-08-05 19:52 UTC, DomKoe commented
You can remove the #407 reference.

2020-08-05 22:50 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +|--------------|
```suggestion
|ID          |
|------------|
```

2020-08-05 22:52 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +#### How to test
```suggestion
#### How to Test
```

2020-08-05 22:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +#### Testing scheme
```suggestion
#### Testing Scheme
```

2020-08-05 23:05 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +| Customer      | Read Only        |        |
```suggestion
|      ROLE     |     PERMISSION    | ADDITIONAL PERMISSION |
|---------------|-------------------|-----------------------|
| Administrator | Full Control      | Delete                |
| Manager       | Modify, Add, Read | Add                   |
| Staff         | Read, Modify      | Modify                |
| Customer      | Read Only         |                       |
```

2020-08-05 23:07 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +Then, the following HTTP request is generated when calling the `viewCCpincode` function:
```suggestion
For example, suppose that the `viewCCpincode.jsp` function is part of every account menu of the application with the same role, and it is possible to access it by requesting the following URL: `https://www.example.com/account/viewCCpincode.jsp`. Then, the following HTTP request is generated when calling the `viewCCpincode` function:
```

2020-08-05 23:08 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +Then, the following HTTP request is generated when calling the `deleteEvent` function:
```suggestion
Suppose that the `deleteEvent.jsp` function is part of the administrator account menu of the application, and it is possible to access it by requesting the following URL: `https://www.example.com/account/deleteEvent.jsp`. Then, the following HTTP request is generated when calling the `deleteEvent` function:
```

2020-08-05 23:09 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +If the response of the attacker’s request contains the same data (`“message”:”Event was deleted”`) the application is vulnerable.
```suggestion
If the response of the attacker’s request contains the same data `{“message”:”Event was deleted”}` the application is vulnerable.
```

2020-08-05 23:10 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example, suppose that the 'AddUser.jsp' function is part of the administrative menu of the application, and it is possible to access it by requesting the following URL:
```suggestion
For example, suppose that the `AddUser.jsp` function is part of the administrative menu of the application, and it is possible to access it by requesting the following URL:
```

2020-08-11 19:02 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +In the following are the most common approaches to bypassing authorization schemes will be shown and explained. First the horizontal, and vertical bypass approaches, then some more specific scenarios
Can we have this more towards bullet points? Maybe combined with the above points? Not something to say "We'll be doing X and Y later", we don't need that. Just, how we're going to test kinda thing

2020-08-11 19:17 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example, suppose that the `viewCCpincode.jsp` function is part of every account menu of the application with the same role, and it is possible to access it by requesting the following URL: `https
Can we change the function names to something more recent?
`/account/cards` or `/account/details`, or something similar, without the JSP extension.

2020-08-11 19:18 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example, suppose that the `viewCCpincode.jsp` function is part of every account menu of the application with the same role, and it is possible to access it by requesting the following URL: `https
I've never seen as well pincode as such being provided, so it's a weird example to a degree too.

2020-08-11 19:26 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +### Testing for Vertical Bypassing Authorization Schema
Maybe mention recon in this step, as a normal user won't readily see the sections? Maybe have another PR for this, do as you see fitting. This could be an improvement to the content.

2020-08-17 14:03 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +### Testing for Vertical Bypassing Authorization Schema
Done

2020-08-17 14:03 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +For example, suppose that the `viewCCpincode.jsp` function is part of every account menu of the application with the same role, and it is possible to access it by requesting the following URL: `https
Examples are changed.

2020-08-17 14:05 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +In the following are the most common approaches to bypassing authorization schemes will be shown and explained. First the horizontal, and vertical bypass approaches, then some more specific scenarios
I changed it to bullet points, I would like to keep it in, as for people not as familiar with the topic, they include a minimal reminder what we are going to do.

2020-08-17 14:06 UTC, DomKoe commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +- Is it possible to access administrative functions if the tester is logged in as a user with standard privileges?
Done

2020-08-17 14:24 UTC, DomKoe commented
Now everything is up to date, pending review.

2020-08-20 10:37 UTC, kingthorin commented
LGTM

2020-09-13 13:27 UTC, kingthorin requested changes
Minor tweaks.

2020-09-13 13:27 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +3. For every request, change the relevant parameters and the session token from token one to token two and diagnose the responses for each token.
```suggestion
2. Establish and keep two different sessions active (one for each user).
3. For every request, change the relevant parameters and the session identifier from token one to token two and diagnose the responses for each token.
```

Tokens seems kinda dated, there are other session tracking mechanisms that might be applicable.

It's fine that the example uses cookies, but if the lead-in is more generic (as suggested) then hopefully readers will be less likely to fixate.

2020-09-13 13:27 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +3. For every request, change the session token from the original token to another role session token and diagnose the responses for each token.
```suggestion
2. Establish and maintain two different sessions based on the two different roles.
3. For every request, change the session identifier from the original to another role's session identifier and evaluate the responses for each.
```

2020-09-13 13:27 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +4. An application will be considered vulnerable if the weaker privileged token contains the same data, or indicate successful operations on higher privileged functions.
```suggestion
4. An application will be considered vulnerable if the weaker privileged session contains the same data, or indicate successful operations on higher privileged functions.
```

2020-09-13 13:27 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +The application will be considered vulnerable if any other role rather than administrator could access the administrator menu. Sometimes, developer perform authorization validation at the GUI level o
```suggestion
The application will be considered vulnerable if any role other than administrator could access the administrator menu. Sometimes, developers perform authorization validation at the GUI level only, and leave the functions without authorization validation, thus potentially resulting in a vulnerability.
```

2020-09-13 13:27 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
> +Various applications setup resource controls based on user roles. Let's take an example CVs uploaded on a careers form to an S3 bucket.
```suggestion
Various applications setup resource controls based on user roles. Let's take an example resumes or CVs (curriculum vitae) uploaded on a careers form to an S3 bucket.
```

2020-09-13 13:27 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
>  - [Port Swigger Burp Suite](https://portswigger.net/burp)
```suggestion
- [OWASP Zed Attack Proxy (ZAP)](https://www.zaproxy.org/)
  - [ZAP add-on: Access Control Testing](https://www.zaproxy.org/docs/desktop/addons/access-control-testing/)
- [Port Swigger Burp Suite](https://portswigger.net/burp)
  - [Burp extension: AuthMatrix](https://github.com/SecurityInnovation/AuthMatrix/)
  - [Burp extension: Autorize](https://github.com/Quitten/Autorize)
```

2020-09-13 15:51 UTC, ThunderSon approved these changes
Nothing additional from my side.

2020-09-13 16:13 UTC, kingthorin approved these changes

2020-09-13 16:20 UTC, merged