DRAFT: Rewrite of TLS testing guide
OWASP/wstg pull request #555
Opened 2020-08-31 10:41 UTC by rbsec

As per #551, rewriting the TLS testing guide to be more succinct and up to date. This is very much a draft PR to track progress, so please don't merge.

@ThunderSon any initial comments are welcome - I've never written a guide for WSTG before, so not sure about the style approach.

2020-08-31 11:30 UTC, kingthorin commented
The project's style guide is available [here](https://github.com/OWASP/wstg/blob/master/style_guide.md), and template info is available [here](https://github.com/OWASP/wstg/tree/master/template).

2020-09-05 15:15 UTC, ThunderSon commented
I will start looking at this next week. Thanks mate.

2020-09-07 19:16 UTC, kingthorin requested changes

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +Mixed active content is when active resources (such as scripts to CSS) are loaded over unencrypted HTTP and included into a secure (HTTPS) page. This is dangerous because it would allow an attacker t
```suggestion
Mixed active content is when active resources (such as scripts or CSS) are loaded over unencrypted HTTP and included into a secure (HTTPS) page. This is dangerous because it would allow an attacker to modify these files (as they are sent unencrypted), which could allow them to execute arbitrary code (JavaScript or styles) in the page. Passive content (such as images) loaded over an insecure connection can also leak information or allow an attacker to deface the page, although it is less likely to lead to a full compromise.
```

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +Note that modern browsers will block active content being loaded from insecure sources into secure pages.
```suggestion
> Note: Modern browsers will block active content being loaded from insecure sources into secure pages.
```

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +#### Redirecting From HTTP to HTTPS
```suggestion
#### Redirecting from HTTP to HTTPS
```
https://capitalizemytitle.com/#Chicago

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +However, this if an attacker is able to intercept this initial request, they could redirect the user to a malicious site, or use a tool such as [sslstrip](https://github.com/moxie0/sslstrip) to inter
```suggestion
However, if an attacker is able to intercept this initial request, they could redirect the user to a malicious site, or use a tool such as [sslstrip](https://github.com/moxie0/sslstrip) to intercept subsequent requests.
```

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +* Main scanning tools (Nessus, Nmap, SSL Labs, sslscan, sslyze, etc)
```suggestion
* Scanning tools (Nessus, Nmap, SSL Labs, sslscan, sslyze, O-Saft, etc)
```

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +* STARTTLS
```suggestion
* STARTTLS
```

I'm not clear on the implication here, if you're going to test services that use STARTTLS aren't you going to use openssl or something that was already listed?

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +The presence of a new service, listening in a separate tcp port may introduce vulnerabilities such as infrastructure vulnerabilities if the [software is not up to date](../02-Configuration_and_Deploy
```suggestion
The presence of a new service, listening on a separate tcp port may introduce infrastructure vulnerabilities if the [software is not up to date](../02-Configuration_and_Deployment_Management_Testing/01-Test_Network_Infrastructure_Configuration.md). Furthermore, for the correct protection of data during transmission the Session Cookie must use the [Secure flag](../06-Session_Management_Testing/02-Testing_for_Cookies_Attributes.md), and some directives should be sent to the browser to accept only secure traffic (e.g. [HSTS](../02-Configuration_and_Deployment_Management_Testing/07-Test_HTTP_Strict_Transport_Security.md), and CSP).
```

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +* The victim's browser starts a new clear text connection to `http://somesecuresite/` and sends an HTTP request containing the cookie in the HTTP header in clear text
```suggestion
* The victim's browser starts a new clear text connection to `http://somesecuresite/` and sends an HTTP request containing the cookie in the HTTP header in clear text.
```

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +* While logged in, the victim opens a new browser window and goes to `http://examplesite/`
```suggestion
* While logged in, the victim opens a new browser window and goes to `http://examplesite/`.
```

2020-09-07 19:16 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +---
This doesn't seem to follow the template. 

Unless everything after the HR is to be removed. In which case this no longer seems to contain much actual testing information.

I'm kinda confused what's going on here.

2020-09-07 19:28 UTC, rbsec commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +---
@kingthorin the stuff below is the break is from the old guide - it will be deleted or incorporated into the new one, but I've not got that far yet. It's mostly there at the moment as a reminder to go through it.

2020-09-07 19:31 UTC, rbsec commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +* STARTTLS
@kingthorin mostly a reminder to include something about STARTTLS and any considerations around it (such as not all tools supporting it on all protocols, or the fact that you might actually have TLS available on "unencrypted" ports like 21.

2020-09-07 19:31 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +---
Oh okay 👍 That makes more sense 😉

2020-09-07 19:33 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +* STARTTLS
Okay

2020-09-07 19:40 UTC, kingthorin commented
> 
> 
> **The following mistakes were identified:**
> /home/runner/work/wstg/wstg/document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md 32:212 ✖ Incorrect usage of the term: “man-in-the-middle”, use “manipulator-in-the-middle” instead terminology

Would be addressed by the suggestion in: https://github.com/OWASP/wstg/pull/555#discussion_r484545497

2020-09-07 20:01 UTC, rbsec commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +It should be emphasised that while many of these attacks have been demonstrated in a lab environment, they are not generally considered practical to exploit in the real world, as they require a (usua
I disagree with the suggestion from textlint for a few reasons:

1. I've never heard this phrase used before in ~10 years in IT/security. Is this some WSTG specifically terminology?
2. When I Googled it, out of the first two pages of results, only 2/20 of them were using it in the context of security - the other 18 were all unrelated. This clearly isn't a common term.
3. It doesn't match the terminology used in any of the TLS-related RFCs, which all talk about `man-in-the-middle` attacks
4. "Manipulator" would mean that it is an active attack (rather than passive interception), which is not always true.

2020-09-10 20:23 UTC, ThunderSon commented
Had an overview of the new content, I like the new sectioning going through. At least a reader would see from the start "Hey they're using a 1k key", or the SAN is showing internal servers, let's grab them. I will give it a better review tomorrow.
If you want me to give a hand, let's coordinate on Slack to agree on which sections to help with, and if not, I'll gladly be on the review side :)

2020-09-12 06:24 UTC, ThunderSon reviewed
I like the current direction of the scenario. Let's keep going forward with it!

2020-09-12 06:25 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +* [Setting the Secure flag on cookies (WSTG-SESS-02)](../06-Session_Management_Testing/02-Testing_for_Cookies_Attributes.md)
Yeah ... Let's keep a note of this till the end. PDF generation is a pita with internal links, that's for sure.

2020-09-30 18:55 UTC, rbsec commented
@ThunderSon et al,

I've been having a think about the client certificate testing section, and whether it's appropriate to include here. It's a pretty niche area (I've only seen and tested it a handful of times), and testing it is a somewhat complex topic, especially if people aren't familiar with how it works in the first place. Perhaps it would be better left out, and maybe get its own section if people think it's worth doing?

I was also wondering how hard it is to rename sections in WSTG. The current title of **Testing for Weak SSL TLS Ciphers Insufficient Transport Layer Protection** isn't great - could this be changed to something simpler like **Testing for Weak Transport Layer Security** or **Testing for Transport Layer Security Weaknesses** or something?

2020-09-30 19:19 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
> +It should be emphasised that while many of these attacks have been demonstrated in a lab environment, they are not generally considered practical to exploit in the real world, as they require a (usua
The Zaproxy team did a twitter/slack poll (late July/early Aug) on this and the community settled on manipulator-in-the-middle. The WSTG decided to adopt the same.

Ref: https://github.com/OWASP/wstg/issues/536

I think you've since changed this to MitM which is fine.

2020-09-30 19:23 UTC, kingthorin commented
> I've been having a think about the client certificate testing section, and whether it's appropriate to include here. It's a pretty niche area (I've only seen and tested it a handful of times), and testing it is a somewhat complex topic, especially if people aren't familiar with how it works in the first place. Perhaps it would be better left out, and maybe get its own section if people think it's worth doing?

I'm fine with it being left out for now.

> I was also wondering how hard it is to rename sections in WSTG. The current title of **Testing for Weak SSL TLS Ciphers Insufficient Transport Layer Protection** isn't great - could this be changed to something simpler like **Testing for Weak Transport Layer Security** or **Testing for Transport Layer Security Weaknesses** or something?

It's not too horrible, just gotta make sure all the references are updated. I like both your suggestions, with a very minor preference to the first simply because it's shorter 😉

2020-10-03 11:47 UTC, ThunderSon commented
@rbsec Same thoughts as @kingthorin on both ends.
Once this is done, let's create a new issue and see the priority on it for client certificates and then go from there.
We can just set placeholders with a line or two on what each issue is if that could be done, since I don't believe there is any pointers or guidance on how to check for client certificates issues (or how people can screw up implementing it) out there.

2020-10-03 12:42 UTC, rbsec commented
The errors flagged above are in the existing checklist (I've not changed the lines it's complaining about).

2020-10-03 13:08 UTC, kingthorin commented
I'll address the checklist terminology issues in another PR. Only the document directory was checked when those terms were added.

2020-10-04 10:28 UTC, ThunderSon commented
@rbsec I did some minor tweaks to what you wrote. Each commit can be reviewed on its own. Let me know if this still fits what you had in mind.

2020-10-04 11:00 UTC, rbsec commented
@ThunderSon I'm happy with all those changes.

2020-10-04 11:13 UTC, ThunderSon commented
@kingthorin about the PDF, only the titles should match the file name for the parsing we have in the gh-action to publish the PDF. Am I wrong or mistaken on that? Can we validate that?

Otherwise, I am positive on this PR.

2020-10-04 11:59 UTC, kingthorin commented
We could do a test build of the PDF after this is merged, that job can be kicked off from the Github web UI now (the PDF gets attached to the workflow run).

2020-10-04 12:04 UTC, kingthorin approved these changes

2020-10-05 16:01 UTC, merged