update checklist excel to WSTG 4.1
OWASP/wstg pull request #559
Opened 2020-09-11 17:31 UTC by frozenSolid

Update checklist excel file to WSTG 4.1

This PR covers issue #558

- [X] This PR handles the issue and requires no additional PRs.
- [ X] You have validated the need for this change.

**What did this PR accomplish?**

- updated excel checklist to use 4.1 `WSTG-` numerators & added missing tests
- updated checklist/README.md to indicate update to v4.1 & sha256 hash
- renamed excel file itself to indicate v4.1

Thank you for your contribution!

2020-09-11 18:57 UTC, kingthorin commented
The broken link can be ignored, it won’t be applicable until the PR is merged.

2020-09-11 19:14 UTC, kingthorin requested changes
I didn't open in Excel (because I didn't have it handy). But the formatting (based on Google sheets import) no longer seems consistent.

![image](https://user-images.githubusercontent.com/7570458/92964044-74ed9400-f441-11ea-9da8-ba10f4e8cb0d.png)
![image](https://user-images.githubusercontent.com/7570458/92964076-80d95600-f441-11ea-99cc-e8ae117e87ab.png)

2020-09-11 19:14 UTC, kingthorin commented on checklist/README.md
>  - [OWASP Testing Checklist (Markdown)](https://raw.githubusercontent.com/OWASP/wstg/master/checklist/Testing_Checklist.md) (**Note:** this has been updated for v4.1)
```suggestion
- [OWASP Testing Checklist (Excel)](https://raw.githubusercontent.com/OWASP/wstg/master/checklist/WSTG-Checklist_v4.1.xlsx)
- [OWASP Testing Checklist (Markdown)](https://raw.githubusercontent.com/OWASP/wstg/master/checklist/Testing_Checklist.md)
```

The note is no longer necessary since both are in-sync with the current release.

2020-09-11 19:14 UTC, kingthorin commented on checklist/README.md
> +SHA-256: 228765a9ec88c13a4407a321766a57c92ffe1dca82a290dd269bd1ed93ccbcac
For reference: https://www.virustotal.com/gui/url/fe43c7bb998b64497a3a537373a7ad80c3d689eb71afda6978d53f3b54baea97/detection
https://www.virustotal.com/gui/url/fe43c7bb998b64497a3a537373a7ad80c3d689eb71afda6978d53f3b54baea97/details

2020-09-11 21:15 UTC, frozenSolid commented on checklist/README.md
>  - [OWASP Testing Checklist (Markdown)](https://raw.githubusercontent.com/OWASP/wstg/master/checklist/Testing_Checklist.md) (**Note:** this has been updated for v4.1)
> I didn't open in Excel (because I didn't have it handy). But the formatting (based on Google sheets import) no longer seems consistent.
> 
> ![image](https://user-images.githubusercontent.com/7570458/92964044-74ed9400-f441-11ea-9da8-ba10f4e8cb0d.png)
> ![image](https://user-images.githubusercontent.com/7570458/92964076-80d95600-f441-11ea-99cc-e8ae117e87ab.png)

good catch @kingthorin ! Formatting looked different in Mac Excel. I've edited the original in sheets and exported it and I am seeing more consistent/ correct formatting now.

2020-09-12 06:28 UTC, ThunderSon commented
I won't be able to properly test this as I don't have the office suite :disappointed: @kingthorin this is on you :yum:

2020-09-14 13:50 UTC, kingthorin commented on checklist/README.md
> +SHA-256: 30e08ef571b5ff623ddd0ab94406a58a8bf2fce8f484badb7117d0f525b8bc6d
For the record: https://www.virustotal.com/gui/url/6ec7cb3c9db265368fb490529026a37e398d63335288897e904549a60008933e/detection

2020-09-14 13:53 UTC, kingthorin approved these changes

2020-09-14 13:54 UTC, merged