Fix 317
OWASP/wstg pull request #575
Opened 2020-10-05 14:26 UTC by AlessiaMichelaDiCampi

This PR covers issue #317 .

- [x ] This PR handles the issue and requires no additional PRs.
- [ x] You have validated the need for this change.

**What did this PR accomplish?**

- Testing for session hijacking
- Testing for session fixation

Thank you for your contribution!

2020-10-05 15:04 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +The issue can be fixed by refreshing the session cookies after the authentication, otherwise the attack can be prevented by ensuring the cookie integrity, i.e. using full [HSTS](https://en.wikipedia.
How about doing this more inline?
```suggestion
The issue can be fixed by refreshing the session cookies after the authentication, otherwise the attack can be prevented by ensuring the cookie integrity, i.e. using full [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) adoption* or adding `__Host-` and `__Secure-` prefixes to the cookie name.

> * We refer to full HSTS adoption when a host activates HSTS for itself and all its sub-domains, and to partial HSTS adoption when a host activates HSTS just for itself.
> - Calzavara, S., Rabitti, A., Ragazzo, A., Bugliesi, M.: Testing for Integrity Flaws in Web Sessions.
```

Then remove the note and reference below?

2020-10-06 14:17 UTC, kingthorin commented
@AlessiaMichelaDiCampi @eleumasc do you mind if I push some fixes to this branch? The suggested note syntax still isn't great, because GitHub tries to render the hyphen and asterisk as bullets:
![image](https://user-images.githubusercontent.com/7570458/95213748-253e8600-07bd-11eb-9375-98fed4dcafde.png)

2020-10-06 14:19 UTC, AlessiaMichelaDiCampi commented
Hi, I've accepted your edit suggestion. The PR is blocked due to the Lint check #684 and #626. We created a new section (9 hijacking). How we can fix these two "problems" ?
Thanks in advance
Alessia Michela Di Campi    Il lunedì 5 ottobre 2020, 17:05:01 CEST, kingthorin <notifications@github.com> ha scritto:  
 
 


@kingthorin commented on this pull request.

In document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md:
>  
-- A web application authenticates a user without first invalidating the existing session ID, thereby continuing to use the session ID already associated with the user.
-- An attacker is able to force a known session ID on a user so that, once the user authenticates, the attacker has access to the authenticated session.
-
-In the generic exploit of session fixation vulnerabilities, an attacker creates a new session on a web application and records the associated session identifier. The attacker then causes the victim to authenticate against the server using the same session identifier, giving the attacker access to the user's account through the active session.
-
-Furthermore, the issue described above is problematic for sites that issue a session identifier over HTTP and then redirect the user to a HTTPS log in form. If the session identifier is not reissued upon authentication, the attacker can eavesdrop and steal the identifier and then use it to hijack the session.
+The issue can be fixed by refreshing the session cookies after the authentication, otherwise the attack can be prevented by ensuring the cookie integrity, i.e. using full [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) adoption<sup>[1](#myfootnote1)</sup> or adding `__Host-` and `__Secure-` prefixes to the cookie name.

How about doing this more inline?
⬇️ Suggested change-The issue can be fixed by refreshing the session cookies after the authentication, otherwise the attack can be prevented by ensuring the cookie integrity, i.e. using full [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) adoption<sup>[1](#myfootnote1)</sup> or adding `__Host-` and `__Secure-` prefixes to the cookie name.
+The issue can be fixed by refreshing the session cookies after the authentication, otherwise the attack can be prevented by ensuring the cookie integrity, i.e. using full [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) adoption* or adding `__Host-` and `__Secure-` prefixes to the cookie name.
+
+> * We refer to full HSTS adoption when a host activates HSTS for itself and all its sub-domains, and to partial HSTS adoption when a host activates HSTS just for itself.
+> - Calzavara, S., Rabitti, A., Ragazzo, A., Bugliesi, M.: Testing for Integrity Flaws in Web Sessions.

Then remove the note and reference below?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-06 14:21 UTC, AlessiaMichelaDiCampi commented
Hi, yes you can do it
    Il martedì 6 ottobre 2020, 16:18:15 CEST, kingthorin <notifications@github.com> ha scritto:  
 
 


@AlessiaMichelaDiCampi @eleumasc do you mind if I push some fixes to this branch? The suggested note syntax still isn't great, because GitHub tries to render the hyphen and asterisk as bullets:


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-06 15:24 UTC, kingthorin commented
Okay all that formatting/linting stuff should be addressed now. Please do a `git fetch origin` `git reset --hard origin/fix-317`.

I think the references look okay inline:
![image](https://user-images.githubusercontent.com/7570458/95222384-6dae7180-07c6-11eb-965a-d90ce185491b.png)

2020-10-06 15:26 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +3. Perform the operation under test;
I wasn't sure where "   then, clear all the other cookies from the browser;" actually fit in. Should it be step 3? Should it have an asterisk of it's own?

2020-10-07 15:15 UTC, AlessiaMichelaDiCampi commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +3. Perform the operation under test;
Hi, "then, clear all the other cookies from the browser;" is of the point 2

2020-10-08 17:58 UTC, kingthorin commented
Rebased current to pickup workflow changes.

2020-10-09 14:40 UTC, ThunderSon requested changes
In addition to the comments:
1. Please use `-` everywhere for unordered lists
2. Set the paper reference in the references section, and not across the document.

Great work, let's touch it up a bit more to make it more usable :)

2020-10-09 14:40 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +    * in case there is partial HSTS adoption*, the `Secure` attribute is not set and the Domain attribute is set to a parent domain; then, clear all the other cookies from the browser;
Can you provide an example of how the domain could be versus a secure one?

2020-10-09 14:40 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +4. Check: has the operation been performed? If yes, report as insecure;
What's the insecurity in here?

2020-10-09 14:40 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +7. Restore in the browser the cookies previously kept at step 2;
Again, you didn't mention "storing" the cookies.

2020-10-09 15:40 UTC, kingthorin commented
> Set the paper reference in the references section, and not across the document.

This was done as-is at my request because we don’t have a good non-HTML way to do footnotes. We can discuss further or tackle it separately.

2020-10-09 17:42 UTC, ThunderSon commented
Alright. We can take care of this in a different issue and then have a PR later on to manage it.

2020-10-09 21:38 UTC, kingthorin commented
Opened OWASP/wstg#580 so that we don't forget to loop back to it 👍

2020-10-09 22:10 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, us
"since the tokens were controlled by the attacker." ?

They do represent a logged in user (of the attacker's choosing), otherwise they'd be useless.

2020-10-09 22:19 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +10. Check: has the operation been performed? If yes, report as insecure.
I too am confused by what the issue might be at step four, it's Alice using Alice's tokens. If there are actually two issues here then a flowchart might help. Otherwise the steps and concerns just need to be clarified.
```diff
- 2. In case there is not full HSTS adoption, find the cookies which have not `__Host-` and `__Secure-` prefixes in the cookie name and were not freshly issued after the login process, then clear all the other cookies from the browser;
+ 2. In case there is only partial HSTS adoption, keep track of the cookies which do not have `__Host-` and `__Secure-` prefixes in the cookie name and were not freshly issued after the login process, then clear all the other cookies from the browser;
```

2020-10-09 22:20 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +We recommend using two different machines and/or browsers for Alice and the attacker. This allows one to decrease the number of false positives if the web application does fingerprinting to verify an
https://github.com/OWASP/wstg/blob/master/style_guide.md#andor

2020-10-09 22:23 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +### Black-Box Testing
"How to Test" should have title caps.

2020-10-09 22:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +The intuition behind the testing strategy for session hijacking is to simulate a scenario where Bob steals all Alice's cookies he might be exposed to.
Ya although `Alice` and `Bob` are IT Security superstars I'd be perfectly happy with attacker and victim.

2020-10-12 00:57 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +> Ref: Calzavara, S., Rabitti, A., Ragazzo, A., Bugliesi, M.: Testing for Integrity Flaws in Web Sessions.
Found this. Would it be useful?

https://link.springer.com/chapter/10.1007/978-3-030-29962-0_29

2020-10-16 14:47 UTC, scalzava commented
Hi all, just reading this now, sorry!

I plan to take a careful look at this entire thread on Monday, which is the first free slot in my calendar. I'll interact with Alessia to discuss how to fix issues and I'll provide my own comments where needed.

2020-10-19 07:37 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, us
I agree with @kingthorin here. I think his wording is fine.

2020-10-19 07:38 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +2. In case there is not full HSTS adoption, find the cookies which have not `__Host-` and `__Secure-` prefixes in the cookie name and were not freshly issued after the login process, then clear all t
Correct. We want to keep just those cookies and delete the others.

2020-10-19 07:41 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +4. Check: has the operation been performed? If yes, report as insecure;
Hey, if I understand correctly, the confusion might come from "were not freshly issued after the login process". By "freshly issued" we mean either of the following: 1) the cookie was not present before login or 2) the cookie was present before login, but its value changed upon login. Does this fix the issue? If it is clear, we can reason about a better wording.

2020-10-19 07:42 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +The intuition behind the testing strategy for session hijacking is to simulate a scenario where Bob steals all Alice's cookies he might be exposed to.
Yeah, we can even use Alice and Mallory, if we want to emphasize that the latter is malicious :)

2020-10-19 07:47 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +10. Check: has the operation been performed? If yes, report as insecure.
Hi guys, let me elaborate on this. The key idea of the testing strategy is the following: a cookie is at risk against session fixation whenever 1. it is not freshly issued upon login and 2. it does not have integrity. If both these conditions are true, the attacker can pick cookies from an unauthenticated session, put them into the victim's browser and wait for the victim to authenticate. Since those cookies won't be refreshed, the victim's session will run with attacker-controlled cookies.

Our testing strategy thus tries to assess whether an operation is allowed through just cookies "at risk", hence simulating session fixation. Cookies can have integrity in two cases: 1. HSTS is activated with includeSubDomains or 2. cookie prefixes are used.

Is it clearer now or should I elaborate more on this?

2020-10-19 07:48 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +    * in case there is partial HSTS adoption*, the `Secure` attribute is not set and the Domain attribute is set to a parent domain; then, clear all the other cookies from the browser;
Sorry, but I don't understand this comment. Can you provide more details?

2020-10-19 07:50 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +4. Check: has the operation been performed? If yes, report as insecure;
The key idea of the testing strategy is the following: if an operation is allowed with just cookies which might be disclosed to the attacker, then we have insecurity. Those conditions identify the scenarios which enable cookie leakage over HTTP against network attackers. Is it clearer now? Do you want us to complement each point with more details?

2020-10-19 07:51 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +> Ref: Calzavara, S., Rabitti, A., Ragazzo, A., Bugliesi, M.: Testing for Integrity Flaws in Web Sessions.
That's my paper :) Stefano Calzavara here. I will help you converge to a final version.

2020-10-19 07:53 UTC, scalzava commented
Folks, I've checked all the comments and provided inline responses. I hope I managed to answer all of them, but I'll keep an eye here and try to assist with further questions and remarks. I can also work directly on the markdown at some point if needed. Feel free to give me directions on what might help you.

2020-10-19 10:25 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, us
Updated the suggestion as per the comments.

2020-10-19 10:38 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +4. Check: has the operation been performed? If yes, report as insecure;
That's not the concern. Freshly issued is well understood (by me, at least).
It's the flow.
1 -> Login
If the tester logs in, they don't know if the token changed or not.
2 -> Discusses a condition, and not a step. This can be improved by saying "Is the token the same pre and post login?".
Then step 3 -> Remove all tokens that don't follow X and Y practices. It doesn't really matter if it is "freshly issued" or not. Making it more straight forward is better since these are steps, not hypothetical talk. How do you validate a freshly issues token, etc.
From there, we can move forward with the steps I believe better. Does this make sense?

2020-10-19 10:41 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +10. Check: has the operation been performed? If yes, report as insecure.
We understand this. Does the reader understand it though? Our comments are mainly coming on the point where we are detailing a strategy which is vague and if someone were to follow it to the letter, might not get the expected outcome.

A tester is gonna start: Login, done. Check if it is freshly issued ... Oh, I don't know. Delete all tokens that don't have X and Y, okay. Perform action, done. Check ... Umm why is it insecure?

It's how clear and direct the steps are. My earlier comment should make things a bit clearer from my perspective.

2020-10-19 10:44 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +The intuition behind the testing strategy for session hijacking is to simulate a scenario where Bob steals all Alice's cookies he might be exposed to.
Doesn't really matter, it's important to keep in mind though that this isn't a standalone paper/chapter. I usually saw victim and attacker.
@kingthorin it's interesting though if we maybe use Alice and Mallory across the whole guide, and define them at the start? Would that complicate things? Maybe have an issue to see the thoughts on it?

2020-10-19 10:44 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +4. Check: has the operation been performed? If yes, report as insecure;
My comment in here is similar to the previous ones.

2020-10-19 10:45 UTC, ThunderSon commented
@scalzava Hi Stefano. Thanks for putting the time to review our comments. I believe you missed 4, which are hidden and you need to expand them. Not major though :)
Replied inline.

2020-10-19 11:28 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +The intuition behind the testing strategy for session hijacking is to simulate a scenario where Bob steals all Alice's cookies he might be exposed to.
Ok, lets go wirh victim/attacker here an open an isdue for consistency throughout.

2020-10-19 11:40 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +4. Check: has the operation been performed? If yes, report as insecure;
OK, please feel free to rephrase. I'll double-check the new version and possibly suggest improvements.

2020-10-19 11:40 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +10. Check: has the operation been performed? If yes, report as insecure.
Now it's clear what you mean. Feel free to update it, then I'll double-check.

2020-10-19 11:44 UTC, scalzava commented
Thanks for the quick feedback! I'll be busy for a couple of days, then I'll be able to double-check the new version. If you feel comfortable implementing the changes, please go ahead and I'll take a look at the revision as soon as I can. If you need assistance, don't hesitate to comment here and I'll try to find some time to help.

2020-10-19 15:50 UTC, AlessiaMichelaDiCampi commented
Hi @ThunderSonwho has to upload updates? do we do it? thank u :)

2020-10-19 17:13 UTC, ThunderSon commented
Hello @AlessiaMichelaDiCampi !
We usually talk with the main author to update, but in this situation it's a bit different since this is a team effort.
If you're available and feel like tackling this, please do. We'll gladly review as many times as needed. Otherwise, let us know so we tackle this.

2020-10-20 10:24 UTC, scalzava commented
> Hello @AlessiaMichelaDiCampi !
> We usually talk with the main author to update, but in this situation it's a bit different since this is a team effort.
> If you're available and feel like tackling this, please do. We'll gladly review as many times as needed. Otherwise, let us know so we tackle this.

Okay, I plan to make a pass over this on Thursday, then I'll handle it for your review!

2020-10-21 10:08 UTC, scalzava commented
Folks, I've completed my revision of the material. I implemented many significant changes, trying to address the majority of the comments I've seen here. Now the testing strategies should be much more intuitive, clear and reproducible. Unfortunately, I could not commit due to authorization issues, but Alessia is uploading the files soon. Please wait for the green light from her before performing a second review. 

Apologies in advance if something is still unclear and for inadvertently introduced mistakes. Alessia and Samuele can take care of further editorial changes, but I'm more than willing to assist with other major changes if needed and I'll keep an eye on this issue. Let's keep in touch until convergence...

2020-10-21 11:23 UTC, kingthorin commented
Thanks!

2020-10-27 13:16 UTC, AlessiaMichelaDiCampi commented
Hi guys, how are you? Have you seen my last update? cheers!
    Il venerdì 23 ottobre 2020, 13:00:20 CEST, Alessia Di campi <alessiadicampi@yahoo.it> ha scritto:  
 
  Hi, I've just uploaded the two updated files. Let me know if is all ok now. Thank you!
    Il mercoledì 21 ottobre 2020, 13:23:44 CEST, kingthorin <notifications@github.com> ha scritto:  
 
 


Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-27 13:57 UTC, kingthorin commented
Thanks for the reminder, sorry I didn't get to go through it over the weekend. I'll try to get it done soon.

2020-10-28 17:36 UTC, ThunderSon requested changes
The update is nice. Thank you. Not so major comments.
Discussed this with people who are not :100: familiar with the concept to get their take on this and how starter friendly it is. Will get the feedback in a couple of days and forward it if need be.
Thanks!

2020-10-28 17:36 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +10. Check: has the operation at step 8 been performed in the victim's account? If yes, halt and report as insecure; otherwise, report as secure.
I am thinking, could there be any additional attack vectors poked at in here? Like if there is cookie overwriting, duplicates, which cookie the backend takes.
Just thinking out loud on this point.

2020-10-28 19:22 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, us
Fine, let's change it! I'm always confused with pronouns :)

2020-10-28 19:25 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +5. Check: has the operation at step 4 been performed? If yes, halt and report as insecure;
Not sure I understand this comment. If the session is under one of the Secure cookies, the session is secure against network attackers from a session hijacking perspective, hence the check at step 5 will fail as expected. Am I missing something here?

2020-10-28 19:27 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +10. Check: has the operation at step 8 been performed in the victim's account? If yes, halt and report as insecure; otherwise, report as secure.
Session hijacking comes from the lack of cookie confidentiality. There is another attack called cookie forcing, where the attacker sets their cookies in the victim's browser, so that the victim is forced into the attacker's session. This might be a problem, e.g., when the victim inputs private information into the session, which would be disclosed to the attacker. However, this is a different attack and would require yet another testing strategy. Did I get this correctly?

2020-10-28 19:28 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +    * in case there is partial HSTS adoption: the `Secure` attribute is set or the `Domain` attribute is not set;
Do you want us to provide more context on the Domain attribute? Or do you think that the strategy is somewhat flawed?

2020-10-28 19:30 UTC, scalzava commented
Great to hear that we are on the right track! I answered all the comments above, let's see whether we can converge. 

Feel free to perform editorial changes as you feel appropriate and perform minor revisions. If something major is needed from our side, don't hesitate to point us to clear actions on what you would like us to change. Cheers.

2020-11-01 09:12 UTC, AlessiaMichelaDiCampi commented
Hi guys, just to know. Is everything ok? Do we need to do some modifications or you are publishing our contribution? 
Thank you, cheers!    Il mercoledì 28 ottobre 2020, 20:30:33 CET, Stefano Calzavara <notifications@github.com> ha scritto:  
 
 


Great to hear that we are on the right track! I answered all the comments above, let's see whether we can converge.

Feel free to perform editorial changes as you feel appropriate and perform minor revisions. If something major is needed from our side, don't hesitate to point us to clear actions on what you would like us to change. Cheers.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-01 10:38 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +    * in case there is partial HSTS adoption: the `Secure` attribute is set or the `Domain` attribute is not set;
More context. Why are we setting or not setting the Domain attribute? How is this part of the test or related to it?

2020-11-01 10:41 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +5. Check: has the operation at step 4 been performed? If yes, halt and report as insecure;
I was mistaken, apologies. I went through it once more and got it resolved.

2020-11-01 10:43 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +10. Check: has the operation at step 8 been performed in the victim's account? If yes, halt and report as insecure; otherwise, report as secure.
Yes, exactly. I am interested in just linking to other test strategies, not discuss them.
Something to the line of:
> As you validate this check, you might be verifying that these attacks are applicable <tests in here>

This can be an issue to map things with this new update to this scenario, not necessarily part of this PR. What do you think about it?

2020-11-01 10:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, us
Will do this before merging so that commits don't happen both ways

2020-11-01 11:01 UTC, ThunderSon commented
Hi @AlessiaMichelaDiCampi ! For now, the only comment that needs tackling from your side is the one relating to the Domain attribute. We'll take care about the formatting and the small bits around wording to make this more uniform to the guide.
I am chatting with additional people to review this (to get more beginner views on it) and we'll share them with you (or they will, whichever works). Thanks!

2020-11-02 08:14 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +10. Check: has the operation at step 8 been performed in the victim's account? If yes, halt and report as insecure; otherwise, report as secure.
I think it would be great to have a testing strategy for cookie forcing. However, I don't think it can be easily accommodated into the present strategy. Since OWASP has an interest in this line of work, I plan to find some motivated students and push further this research line on testing strategies for secure session management. We will be in touch :)

2020-11-02 08:15 UTC, scalzava commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +    * in case there is partial HSTS adoption: the `Secure` attribute is set or the `Domain` attribute is not set;
I will take care of that and send the revised version to Alessia.

2020-11-02 08:42 UTC, scalzava commented
I've made the requested changes about the Domain attribute and provided a revised version to Alessia, which will commit it soon. We'll keep an eye on this issue to help with further edits which might be required before the final merge.

Also, elaborating on a comment above: there's room for more testing strategies and I plan to assign them to students, e.g., as bachelor theses. When I think I'll have something valuable to share, I'll ping you and see together whether that could be integrated into the Testing Guide. We also have other projects which might be of interest to the community, so let's keep in touch!

2020-11-02 09:06 UTC, n17h31sm commented
Hi everyone, I was asked for my beginner perspective by @ThunderSon.
On that matter I have а comment regarding testing for session fixation. To me as a complete beginner on the topic the introduction was very abstract and overcomplex that I could not understand what we are going to do. It cleared out just when I went through the examples.  

My proposition is to change the following:

>In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, using different techniques. If the victim later authenticates at the target website and the cookies are not refreshed upon login, she will be identified by the session cookies chosen by the attacker, who will then become able to impersonate the victim (since her cookies are known to the attacker).

To something more simple like:

>In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, thus when the victim successfully authenticates, their privileges are associated with the cookies that the attacker forced into the browser and from there on the attacker can use them to impersonate the victim.

Let me know what are your opinions on this.

2020-11-02 12:42 UTC, scalzava commented
> Hi everyone, I was asked for my beginner perspective by @ThunderSon.
> On that matter I have а comment regarding testing for session fixation. To me as a complete beginner on the topic the introduction was very abstract and overcomplex that I could not understand what we are going to do. It cleared out just when I went through the examples.
> 
> My proposition is to change the following:
> 
> > In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, using different techniques. If the victim later authenticates at the target website and the cookies are not refreshed upon login, she will be identified by the session cookies chosen by the attacker, who will then become able to impersonate the victim (since her cookies are known to the attacker).
> 
> To something more simple like:
> 
> > In the generic exploit of session fixation vulnerabilities, an attacker can obtain a set of session cookies from the target website without authenticating and force them into the victim's browser, thus when the victim successfully authenticates, their privileges are associated with the cookies that the attacker forced into the browser and from there on the attacker can use them to impersonate the victim.
> 
> Let me know what are your opinions on this.

I think this misses a very important point, i.e., the fact that session cookies are not refreshed upon login. This is not a detail, because it means that cookies that the attacker got for an unauthenticated session will be actually used to identify an authenticated session (of the victim).

2020-11-02 12:54 UTC, ThunderSon commented
I'll try and make ends meet.
In the first line, the following is said:
> Session fixation is enabled by the insecure practice of preserving the same value of the session cookies before and after authentication.

In the proposed text I can see it removed since that is what the definition of session fixation is in the previous sentence.

I have no hard opinions on this. If kept, more emphasis is put on the point (since it is mentioned in a different language), if removed, it's part of the definition, correct?

2020-11-02 14:07 UTC, scalzava commented
I see what you mean. Sorry, but there was no reference to the first line in Nikoleta's comment, hence I assumed it was removed. If that is kept, I think we can make the rest of the discussion lighter along Nikoleta's lines.

2020-11-02 14:28 UTC, ThunderSon commented
No worries. When read like that it sounds a bit misleading. @kingthorin might you be able to chime in on this to take a final call on this part?

2020-11-02 14:35 UTC, kingthorin commented
I think given the existing content of the paragraph/sentence ahead the proposed text is fine.

2020-11-02 18:32 UTC, ThunderSon commented
Alright. The WSTG team will handle this and ensure that everything stays readable. We'll be waiting for Alessia's commit before giving this the last touch. Once both of us are satisfied with it, we'll release it :)

2020-11-03 08:07 UTC, AlessiaMichelaDiCampi commented
Hi, I've done just now the commit :)    Il lunedì 2 novembre 2020, 19:33:06 CET, ThunderSon <notifications@github.com> ha scritto:  
 
 


Alright. The WSTG team will handle this and ensure that everything stays readable. We'll be waiting for Alessia's commit before giving this the last touch. Once both of us are satisfied with it, we'll release it :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-07 00:50 UTC, victoriadrake approved these changes

2020-11-10 08:35 UTC, scalzava commented
Hi guys, I was looking into the guide to involve another student into an OWASP collaboration and I realized that this PR has not been integrated yet. Considered Victoria's approval, this was a surprise to me, though I'm not familiar with the typical integration process (first time collaboration here). Shall we just wait or are further actions required? Thanks!

2020-11-10 11:04 UTC, kingthorin commented
@scalzava It's just waiting on me doing another review pass, I hope to get that knocked off today.

Also if you could have a quick look after Victoria's changes to ensure you're still happy with the content that'd be great.

2020-11-10 12:10 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
> +6. Observe whether the operation at step 5 been performed successfully. If so, the attack was successful.
```suggestion
6. Observe whether the operation at step 5 has been performed successfully. If so, the attack was successful.
```

2020-11-10 12:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
> +## How to test
```suggestion
## How to Test
```

2020-11-10 12:19 UTC, kingthorin approved these changes

2020-11-12 01:40 UTC, merged

2020-11-12 02:42 UTC, victoriadrake commented
Congratulations on the merge to everyone involved! 🎉 Thank you for your contribution to the WSTG!

2020-11-12 19:53 UTC, AlessiaMichelaDiCampi commented
Hello, thank you very much to you!
    Il giovedì 12 novembre 2020, 03:43:12 CET, Victoria Drake <notifications@github.com> ha scritto:  
 
 


Congratulations on the merge to everyone involved! 🎉 Thank you for your contribution to the WSTG!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.