GraphQL API testing guide
OWASP/wstg pull request #577
Opened 2020-10-06 06:50 UTC by 1Oreo

This PR covers issue  #553 .

- [X] This PR handles the issue and requires no additional PRs.
- [X] You have validated the need for this change.

**What did this PR accomplish?**

- Created section 12-API testing
- Created GraphQL testing guide

2020-10-06 10:28 UTC, ThunderSon commented
You have a `~~~` instead of triple ticks, if you can fix that.
So I have a proposition. How about the test is split inside a folder for GraphQL, where every test scenario takes its own file? More concise, more focused. What do you think?

2020-10-06 10:39 UTC, ThunderSon commented
@PauloASilva I believe you'd be interested in having a look at this :)
If you know any additional GraphQL experts as well, be my guest in inviting them!

2020-10-06 11:14 UTC, PauloASilva commented
Thanks for pinging @ThunderSon.

@1Oreo may I suggest you to check OWASP/CheatSheetSeries/pull/434 to understand the current testing guide coverage: the PR is full of good references (may more will be available through git history).

Cheers,
Paulo A. Silva

2020-10-07 09:10 UTC, 1Oreo commented
@ThunderSon I've resolved the issue you mentioned (using "~"), and some terminology linter issues.
I can understand why separating the file into smaller pieces will be good (they will be more focused as well as easier for more contributors to add GraphQL related test).
I'm fine either way, when you're done reviewing and know how to best proceed, ping me.
I've also looked at the cheatsheet PR, so also let me know if we want to include it as a reference, and add content to the wstg file.

2020-10-07 23:31 UTC, kingthorin commented
Note the code fencing still needs a highlighting hint. The linter workflow is failing to comment due to an output/content issue (which I’ll look into and address).

<details><summary>Current linting issues</summary>

```console
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:39 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
7
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:239:1 MD033/no-inline-html Inline HTML [Element: img]
8
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:240:1 MD033/no-inline-html Inline HTML [Element: img]
9
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:241:1 MD033/no-inline-html Inline HTML [Element: img]
10
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:323 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
11
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:334:4 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
12
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:334 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "``` "]
13
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:387 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
14
document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:450 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]

```

</details>

See the template directory for details on embedding images.

2020-10-08 06:57 UTC, 1Oreo commented
@kingthorin I've resolved all of the linter issues except for the images one.
The problem I had is the screenshots I took were not very wide, which resulted in being a huge zoomed-in picture and I did not find any other way to resize them (if you'll look at the file, all of the other images are included regularly within markdown using []()).
I can revert them back but I think it'll look quite bad.
Is there another solution you can direct me to?

2020-10-08 18:00 UTC, kingthorin commented
I think the images will turnout fine for the web deployment (ex: https://owasp.org/www-project-web-security-testing-guide/latest/6-Appendix/F-Leveraging_Dev_Tools.html) and PDF generation, I wouldn't worry about how they look on GitHub we don't really expect people to use GH as a primary means of consuming that material.

2020-10-09 12:49 UTC, 1Oreo commented
ack, so I'll convert it to the normal way of importing images and push the update to the PR.

2020-10-15 15:10 UTC, ThunderSon requested changes
As the first look, on top of the direct review points:
1. We can join the generic attacks under a section saying that. (Injection, AuthZ/N, etc.)
2. Please fix the JSON response (like close it properly, we'll see later to how to represent a bigger response). It's breaking on the representation side.
3. Let's add the graphQL batching attack: https://lab.wallarm.com/graphql-batching-attack/
4. Pointers at mutations with weak access control maybe?

I clearly can see this scenario shorter and more concise, but it looks like a starting place for graphql. This should take a couple of rounds before it gets accepted, so I hope that doesn't really bother you.

Rick should be doing a review soon, just as they're more free with life overall. Everything is open for discussions, and if I can help somehow let me know :)

2020-10-21 13:06 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```graphql
It's actually from [Medium](https://medium.com/@the.bilal.rizwan/graphql-common-vulnerabilities-how-to-exploit-them-464f9fdce696) and I added it to the references section as well as a link before the payload itself.

2020-10-21 13:20 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```json
I can also write down the full reply (but it was REALLY long that's why I tried shorting it). Let me know if you want me to do that if there isn't a quick fix for closing jsons at the moment.

2020-10-21 13:22 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +#### Using the GraphiQL
OK that actually sounds good to me. I was worried that the images will take up the entire page (that's why I first implemented them using plain HTML). I'll delete it and write down exactly what you say, it is already referenced.

2020-10-21 13:39 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +In this example, every user (even un-authenticated) can gain access to auth tokens of every veterinarian listed in the database. These tokens can be used to perform additional actions the scheme allo
I fixed the text as well as added the example to let the readers understand that the tokens and the request do not match.

2020-10-21 13:42 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```json
So, for the update to the PR I will push in a minute, I closed the brackets so the JSON will actually be properly closed, even though it lacks a lot of the response (in length). If you think we should put the entire response I can do that as well, just ping me.

2020-10-21 15:02 UTC, kingthorin commented
I believe you removed references to these 4 images, so could you remove the files themselves from the PR?
```console
![GraphiQL1](images/GraphiQL1.png)
![GraphiQL2](images/GraphiQL2.png)
![GraphiQL3](images/GraphiQL3.png)
![GraphiQL4](images/GraphiQL4.png)
```
(Unless I missed something, please correct me if I'm wrong.)

2020-10-22 06:27 UTC, 1Oreo commented
Deleted and pushed again, I did delete it but I guess I forgot to add the change before pushing. Should be fixed now.

2020-10-23 15:29 UTC, kingthorin requested changes
There's a bunch of places where paragraphs need to be actual paragraphs instead of a collection of sentences grouped together on separate lines. I can tackle that later if needed.

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +GraphQL is the implementation of the API layer of an application, and as such, it usually forwards the requests to a backend API or the database directly. This allows you to utilize any underlying vu
```suggestion
GraphQL is the implementation of the API layer of an application, and as such, it usually forwards the requests to a backend API or the database directly. This allows you to utilize any underlying vulnerability such as SQL injection, command injection, cross-site scripting, and basically, everything you expect to find in web applications, using GraphQL just changes the entry point of the malicious payload.
```

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The application is vulnerable by design in the `dogs(namePrefix: String, limit: Int = 500): [Dog!]`  since the parameter "namePrefix" is concatenated in the SQL query. Concatenating user input is a c
```suggestion
The example application is vulnerable by design in the query `dogs(namePrefix: String, limit: Int = 500): [Dog!]`  since the parameter "namePrefix" is concatenated in the SQL query. Concatenating user input is a common malpractice of applications which exposes them to SQL injection.
```

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Another thing you can do, is use tools like sqlmap to look for injection paths and even automating the extraction of data from the database.
```suggestion
Another thing you can do, is use tools like sqlmap to look for injection paths and even automate the extraction of data from the database.
```

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Reflection of input might cause XSS, but that is up to how the application is implemented, wether in encodes the output, so the best practice would be to test for XSS using a payload from [WSTG](http
```suggestion
Reflection of input might cause XSS, but that is up to how the application is implemented, whether in encodes the output, so the best practice would be to test for XSS using a payload from [Testing for Reflected Cross Site Scripting](../07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.md).  
```

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Input validation alone will be good, but it will not block everything (there is no 100% security), and additional measures should be implemented as well.
This should be summarized in a few bullets and added to "Remediation" below.

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +GraphQL exposes a very simple interface, to allow developers use nested queries and nested objects. This ability can also be used in a malicious way, by calling a deep nested query similar to a recur
or Memory?

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +
469 thru 503.

This is great information but it's too remediation or developer centric. It would be better (I think) to turn this into a set of bullets: "Testers should consider testing for bypasses of the following types of controls or limits:" or something like that..... I'm open to your feedback/ideas.

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +
Actually include "Detailed Error Message" in that too.

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The remediation for these types of vulnerabilities is both input validation and awareness of the a possible issue, since authorization problems might also occur.
```suggestion
```

I think this is un-necessary, the next section is remediation, which as mentioned above should have bullets for all the things we want testers (and devs) to be aware of.

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +4. Sending generic error messages
Are these actually ordered? If not please use asterisks and finish them with periods.

2020-10-23 15:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +- [GraphQL addon for (OWASP) ZAP](https://www.zaproxy.org/blog/2020-08-28-introducing-the-graphql-add-on-for-zap/)
```suggestion

- [InQL (Burp Extension)](https://portswigger.net/bappstore/296e9a0730384be4b2fffef7b4e19b1f)
- [GraphQL Raider (Burp Extension)](https://portswigger.net/bappstore/4841f0d78a554ca381c65b26d48207e6)
- [GraphQL (Add-on for OWASP ZAP](https://www.zaproxy.org/blog/2020-08-28-introducing-the-graphql-add-on-for-zap/)
```

2020-10-23 16:14 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +
Edit: Typo + comma, and set the introspection link inline

2020-10-23 16:15 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +  __schema {
After I did my research, I linked to a certain gist that had that same body. I found this in several spots. It goes out to ask for all types of queries and possible types.

2020-10-23 20:27 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +  __schema {
Okay, fair enough.

2020-10-27 07:02 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +4. Sending generic error messages
done

2020-10-27 07:05 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +This tool creates an ERD representation of the GraphQL scheme, allowing you to get a better look into the moving parts of the system you're testing.
added (and it wasn't enterprise rate discount :D)

2020-10-27 07:06 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +You can even download the schemes to use in Voyager.
schema, changed it all over the doc, thanks!

2020-10-27 07:07 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +GraphQL exposes a very simple interface, to allow developers use nested queries and nested objects. This ability can also be used in a malicious way, by calling a deep nested query similar to a recur
you're right, I added a memory and noted that other compute resources might be abused as well (disk? for example).

2020-10-27 07:14 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Input validation alone will be good, but it will not block everything (there is no 100% security), and additional measures should be implemented as well.
Just to clarify, do you mean delete these lines and just add input validation in the remediation section? (which it already contains), or to add some of the information from these lines to the remediation section?
Both would be OK for me, I tried to add every remediation action into the remediation section but maybe we would want to add some more information to the bullets there, since it doesn't go into details very deeply.

2020-10-27 07:17 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +
I can turn it into bullets and make it a bit more brief. In that case, do you think it should be under remediation or keep the structure as it is and just write a short description and an appropriate link?

2020-10-27 14:45 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +
If it's tester centric then it can stay here as bullets, if it's remediation centric then it should be relocated.

2020-10-27 14:46 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Input validation alone will be good, but it will not block everything (there is no 100% security), and additional measures should be implemented as well.
The comment was about everything 404 thru 410.

2020-10-27 15:08 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +
OK I agree, I'm moving it to remediation and try to make it tester centric (and what doesn't fit will be removed).
I think I'll push an update in a couple of minutes.
Thanks for the review!

2020-10-27 15:58 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Introspection queries are the way GraphQL lets you ask what queries are supported, which data types are available, and many more details you will need when approaching a test of a GraphQL deployment.
Re:

>document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md:27:200 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]

It allows 2 because the old school typewriter rule was period space space between sentences. If it's the end of a paragraph it should actually be 0.

So while what you've done is "allowed" by the linter it isn't actually the spirit of what should be done here 😉

2020-10-27 16:33 UTC, 1Oreo commented
@kingthorin I've implemented all of your comments and pushed a new commit.
@ThunderSon  you can also see if everything is in order.
Thank you both for the reviews.

2020-10-29 11:05 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Introspection queries are the way GraphQL lets you ask what queries are supported, which data types are available, and many more details you will need when approaching a test of a GraphQL deployment.
hmmm, I have to say the lesson on typewriters was interesting! and well, this is my first time writing something long in Markdown while applying all the linter rules so thanks for directing me in the right way (I have missed this comment 2 days ago, probably while I was sending another commit).
Are there any additional fixes you see in the last version of the PR @kingthorin ?

2020-10-29 11:09 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Introspection queries are the way GraphQL lets you ask what queries are supported, which data types are available, and many more details you will need when approaching a test of a GraphQL deployment.
I went over the doc (to see if I did that in any other places) and it seems this was the only case. I've pushed another commit, let me know how it looks, thanks again!

2020-10-29 16:07 UTC, kingthorin commented
Thanks, I'll review it tonight.

Just taking a quick look it seems like there are a bunch of places individual sentences could still be turned into paragraphs. Ex: The 3 lines/sentences here could be one (not shortened or re-worded just put together with fewer line feeds):
![image](https://user-images.githubusercontent.com/7570458/97600290-47ec4500-19df-11eb-8a1e-1a354337dd50.png)

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Some vectors are unique to GraphQL (Introspection Query for example) and some are not (SQL Injection for example).
```suggestion
GraphQL has become very popular in modern APIs. It provides simplicity, and nested objects, which facilitate faster development. Every technology, while having advantages can also expose the application to new attack surfaces. The purpose of this scenario is to provide some common misconfigurations and attack vectors on applications which utilize GraphQL. Some vectors are unique to GraphQL (Introspection Query for example) and some are not (SQL Injection for example).
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +There are a couple of ways to extract that and visualize the output:
```suggestion
> "It's often useful to ask a GraphQL schema for information about what queries it supports. GraphQL allows us to do so using the [introspection](https://graphql.org/learn/introspection/) system!"

There are a couple of ways to extract that and visualize the output, as follows.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The most straight-forward way is to send an HTTP request (using a proxy like Burp) with the following payload, taken from an article on [Medium](https://medium.com/@the.bilal.rizwan/graphql-common-vu
```suggestion
The most straight-forward way is to send an HTTP request (using a personal proxy) with the following payload, taken from an article on [Medium](https://medium.com/@the.bilal.rizwan/graphql-common-vulnerabilities-how-to-exploit-them-464f9fdce696) :
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Extracting information from the drawing allows you to see you can query the dogs table for example. It also shows which properties a "dog" has:
```suggestion
This tool creates an Entity Relationship Diagram (ERD) representation of the GraphQL schema, allowing you to get a better look into the moving parts of the system you're testing. Extracting information from the drawing allows you to see you can query the dogs table for example. It also shows which properties a "dog" has:
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The documentation contains the data types, mutations, and basically every piece of information you can extract using Introspection.
```suggestion
GraphiQL is a web-based IDE for GraphQL. It is part of the GraphQL project, and it is mainly used for debugging or development purposes. The best practice is to not allow users to access it on production deployments, however, if you are testing a staging environment you might have access to it and it can save you some time playing around with introspection queries (although you can, of course, use introspection in the GraphiQL interface).

GraphiQL has a docs section, which uses the data from the schema in order to created a documentation of the GraphQL instance that is being used. The documentation contains the data types, mutations, and basically every piece of information that can be extracted using Introspection.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +
```suggestion
GraphQL Playgrounds is a GraphQL client, which can be used to test different queries, as well as dividing GraphQL IDEs into different playgrounds, grouped by theme or by assigning a name to them. Much like GraphiQL, Playgrounds can create documentation for you, without the need for manually sending introspection queries and processing the response(s) but with one great advantage, it doesn't need GraphiQL interface to be available. Another upside for this tool, is that it works just by directing the tool to the GraphQL node via a URL (there is also the option of using it locally with the data file) and then the magic happens without any user interaction. GraphQL Playgrounds can be used to test for vulnerabilities directly, you don't need to use a personal proxy to send HTTP requests, and so you can use this tool in order to interact and asses GraphQL and use a personal proxy for other, more advanced payloads.  

> Note that in some cases you will need to set the HTTP headers at the bottom, to include session ID or other mechanism of authentication, but this still allows creating multiple "IDEs" with different permissions to verify if there are in fact authorization issues.

```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Since GraphQL is usually bridges to the backend APIs of the system, its better to enforce strict access control, which leads to the next topic.
```suggestion
Introspection is a useful tool which allows users to gain more information about the GraphQL deployment, however, this will also allow malicious users to gain access to the same information. Best practice is to limit the access to the introspection queries, since, some tools or requests might fail if this feature is disabled altogether. Since GraphQL usually bridges to the backend APIs of the system, its better to enforce strict access control, which leads to the next topic.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The next thing you should check, once you have access to the schema and know what sensitive information there is to extract, is sending queries which will not be blocked due to insufficient privilege
```suggestion
Introspection is the first place to look for Authorization problems. As noted, introspection should be restricted since it allows for data extraction and data gathering. The next thing a tester should check, once they have access to the schema and know what sensitive information there is to extract, is sending queries which will not be blocked due to insufficient privileges. GraphQL does not enforce permissions by default, and so it is up to the application to perform authorization enforcement.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +In this example, every user (even un-authenticated) can gain access to auth tokens of every veterinarian listed in the database. These tokens can be used to perform additional actions the schema allo
```suggestion
Testing the authorization implementation varies from deployment to deployment since each schema will have different sensitive information, and hence, different targets to focus on. In this example, every user (even un-authenticated) can gain access to auth tokens of every veterinarian listed in the database. These tokens can be used to perform additional actions the schema allows, such as associating or disassociating a dog from any specified veterinarian (using mutations), while there is no matching of the auth token to the veterinarian which appears in the request. An example would be, to use the token that was extracted (which belongs to Julien), and use it to perform an action as Benoit, who has the number 2 ID.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +You can refer to other guides within the OWASP testing guide to get some ideas.
```suggestion
You can refer to other scenarios within the OWASP testing guide to get some ideas.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The example application is vulnerable by design in the query `dogs(namePrefix: String, limit: Int = 500): [Dog!]`  since the parameter "namePrefix" is concatenated in the SQL query. Concatenating use
```suggestion
The example application is vulnerable by design in the query `dogs(namePrefix: String, limit: Int = 500): [Dog!]`  since the parameter `namePrefix` is concatenated in the SQL query. Concatenating user input is a common malpractice of applications which exposes them to SQL injection.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The following query extracts information from the CONFIG table within the database:
```suggestion
The following query extracts information from the `CONFIG` table within the database:
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Another thing you can do, is use tools like sqlmap to look for injection paths and even automate the extraction of data from the database.
```suggestion
The query contains the secret which signs JWTs in the example application, which is very sensitive information. Please note that in order to know what to look for you will need to collect information and learn about how the application is built as well as how the database tables are organized. Another thing a tester can do, is use tools like sqlmap to look for injection paths, and even automate the extraction of data from the database.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +As noted, GraphQL only creates another layer on top of the application, so other tests from WSTG might be useful.
```suggestion
Cross-Site scripting occurs when the browser treats data that should be displayed as code that should be executed, creating the opportunity to run malicious code in a user's browser. Reflection of input might cause XSS, but that is up to how the application is implemented, whether in encodes the output, so the best practice would be to test for XSS using a payload from [Testing for Reflected Cross Site Scripting](../07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.md). As noted, GraphQL only creates another layer on top of the application, so other tests from WSTG might be useful.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +**Note**: There are also scalars in GraphQL, which are usually used for custom data types which do not have native data types (DateTime for example). These types of data do not have out of the box va
```suggestion
> Note: There are also scalars in GraphQL, which are usually used for custom data types which do not have native data types (DateTime for example). These types of data do not have out of the box validation as well, and you should look at them as well while testing.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Abusive queries can cause issues like DoS for GraphQL deployments and hence, should be tested as part of a security test for GraphQL deployments.
```suggestion
There a multiple security measures which can be implemented to prevent these types of queries, which will be listed in the remediation section. Abusive queries can cause issues like DoS for GraphQL deployments and hence, should be tested as part of a security test for GraphQL deployments.
```

2020-10-30 03:24 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +As part of the testing, error messages should be checked, by sending unexpected data, and the responses should be searched for additional information which might be revealed using this technique.
```suggestion
GraphQL can encounter unexpected errors during runtime. When an error like that occurs, the server may send an error response, which can reveal internal error details or application configuration/data/assets, allowing a malicious user to acquire more information on the application. As part of the testing, error messages should be checked, by sending unexpected data, and the responses should be searched for additional information which might be revealed using this technique.
```

2020-11-01 14:07 UTC, 1Oreo commented
@kingthorin implemented your paragraph suggestions. Is there anything else I need to fix?

2020-11-01 14:34 UTC, ThunderSon commented
@1Oreo please stand by as we do more rounds on this. I should have a review in either today or tomorrow (not sure how my days will go). Kind of doing a rotational reviews between me and rick to gain 3 views on this new scenario :)

2020-11-01 14:36 UTC, 1Oreo commented
np @ThunderSon. Make sure to ping me when I'm needed.

2020-11-01 16:17 UTC, ThunderSon requested changes
There is still the batching attacks, as I previously mentioned in an earlier comment.
The following can be used: https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#batching-attacks
Once that is done we can open an issue with the CS team to refer here.

2020-11-01 16:17 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +|WSTG-APIS-01|
@kingthorin I feel like APIT would be a more fitting one? API Testing. What do you think? We need more input on this as well to name our new section :yum:

2020-11-01 16:17 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```graphql
@kingthorin We need to see if this should stay as is, or if we create a gist and set these in. That way we'd have them separate and the query gets updated without having the guide updated.

2020-11-01 16:17 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +#### Using GraphQL Playgrounds
The tool is named GraphQL Playground, shouldn't it be without the `s` across the guide?

2020-11-01 16:17 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +![Playgrounds1](images/Playgrounds1.png)\
These need an update as well, if you agree on the figure quotes, update the alt text accordingly and the image names as well.

2020-11-01 16:17 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Cross-Site scripting occurs when the browser treats data that should be displayed as code that should be executed, creating the opportunity to run malicious code in a user's browser. Reflection of in
That end note in this line should be used for the injection section as a whole, not in this particular sub-section.

2020-11-01 16:17 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +### Abusive Queries
I see that abusive might be a bit "vague". All testing queries are to some degree abusive. Maybe we can just reference this as DoS Queries?

2020-11-01 16:20 UTC, ThunderSon commented
@PauloASilva @inonshk @bigshebang @ErezYalon
We are closing to this being merged in, after the GraphQL CS got merged in.
Would you be able to provide us with a review on the content being set in order to gain more point of views on this matter?

2020-11-01 18:06 UTC, ThunderSon commented
@RiieCco I believe you worked on the offensive GraphQL webinar as well a month ago. Would you provide us with a quick review? :blush:

2020-11-01 18:46 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +#### Using GraphQL Playgrounds
If it's name really doesn't have an `s` then yes, I didn't check.

2020-11-01 18:47 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```graphql
I'm fine with it like this. Using s gist see s disjointed to me.

2020-11-01 19:20 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```graphql
Didn't copy that Alpha, come again. You had a bit of static in that second sentence :p

2020-11-01 19:28 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +|WSTG-APIS-01|
I’m not picky. I don’t think that’s as obvious but I’m also not terribly stuck in it either way.

2020-11-01 19:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```graphql
🤪 fixed

2020-11-04 10:34 UTC, RiieCco commented
@ThunderSon,

Looks really good to me, nothing to add to there really!

Maybe one thing for convenience is pointing "Abusive Queries" to the Graphql voyager example.
because from Graphql voyager you can really easily determine where exactly you can find "nested objects"

I also have a small list of labs that might be added for people to play around with trying to exploit these type of vulns? :-)

https://owasp-skf.gitbook.io/asvs-write-ups/kbid-285-graphql-dos
https://owasp-skf.gitbook.io/asvs-write-ups/kbid-285-graphql-idor
https://owasp-skf.gitbook.io/asvs-write-ups/kbid-285-graphql-injections
https://owasp-skf.gitbook.io/asvs-write-ups/kbid-285-graphql-introspection
https://owasp-skf.gitbook.io/asvs-write-ups/kbid-285-graphql-mutations

2020-11-10 08:29 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +|WSTG-APIS-01|
changed to APIT

2020-11-10 08:30 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +```graphql
leaving as is for now, if you think we should change it let me know

2020-11-10 08:32 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +#### Using GraphQL Playgrounds
hmmm I don't know when it was incepted into my brain but fixed now.

2020-11-10 08:34 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +Cross-Site scripting occurs when the browser treats data that should be displayed as code that should be executed, creating the opportunity to run malicious code in a user's browser. Reflection of in
I've moved it to the general injection section.

2020-11-10 08:34 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +### Abusive Queries
I see your point, I'll change it to DoS since that is exactly what they try to cause.

2020-11-10 08:36 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +### Abusive Queries
Also, I'll implement RiieCco's comment on referencing the graphql voyager for nested objects.

2020-11-10 08:52 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +![Playgrounds1](images/Playgrounds1.png)\
done

2020-11-10 09:45 UTC, 1Oreo commented
@ThunderSon I have (finally) added the batching attack section, while also implementing fixes from the last round of reviews.
Thanks for the changes you made with your own commits.

2020-11-10 19:21 UTC, kingthorin approved these changes
Looks good, thanks ⭐

2020-11-11 16:41 UTC, bigshebang commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +A tool such as GraphQL Voyager can be used to get a better understanding of the GraphQL endpoint:
A link to this tool would be nice.

2020-11-11 16:58 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +A tool such as GraphQL Voyager can be used to get a better understanding of the GraphQL endpoint:
It's in the "Tools" section isn't it?

2020-11-11 17:01 UTC, bigshebang commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +[GraphQL Playground](https://github.com/graphql/graphql-playground) is a GraphQL client, which can be used to test different queries, as well as dividing GraphQL IDEs into different playground, group
Some wording and punctuation changes.

```suggestion
[GraphQL Playground](https://github.com/graphql/graphql-playground) is a GraphQL client, which can be used to test different queries, as well as dividing GraphQL IDEs into different playgrounds, grouped by theme or by assigning a name to them. Much like GraphiQL, Playground can create documentation for you without the need for manually sending introspection queries and processing the response(s), but with one great advantage: it doesn't need the GraphiQL interface to be available. Another upside for this tool is that it works just by directing the tool to the GraphQL node via a URL (there is also the option of using it locally with the data file) and then the magic happens without any user interaction. GraphQL Playground can be used to test for vulnerabilities directly, so you don't need to use a personal proxy to send HTTP requests. This means you can use this tool for simple interaction with and assessment of GraphQL but turn to a personal proxy for other, more advanced payloads.
```

2020-11-11 17:05 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +[GraphQL Playground](https://github.com/graphql/graphql-playground) is a GraphQL client, which can be used to test different queries, as well as dividing GraphQL IDEs into different playground, group
Good suggestion. I've tweaked your colon change to be followed by a capital.

2020-11-12 01:43 UTC, bigshebang commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +A tool such as GraphQL Voyager can be used to get a better understanding of the GraphQL endpoint:
I meant an inline link here, but it isn't in the tools section either.

2020-11-12 08:55 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +A tool such as GraphQL Voyager can be used to get a better understanding of the GraphQL endpoint:
My bad, added it both inline and in the tools section.

2020-11-12 08:58 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +A tool such as GraphQL Voyager can be used to get a better understanding of the GraphQL endpoint:
Added thanks for catching this.

2020-11-12 10:43 UTC, kingthorin approved these changes
Thanks for those tweaks

2020-11-13 15:36 UTC, n17h31sm commented
@1Oreo @ThunderSon 

From my beginners PoV, it seems really good to me, it is easy to follow, covers the most important stuff and has references for further understanding and experimenting. Also it is just the right balance between enough information and not being cluttered. Kudos! 👍 💯

2020-11-14 19:42 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The most straightforward way is to send an HTTP request (using a personal proxy) with the following payload, taken from an article on [Medium](https://medium.com/@the.bilal.rizwan/graphql-common-vuln
Do we have permission from the original source to include this?

2020-11-14 21:16 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The most straightforward way is to send an HTTP request (using a personal proxy) with the following payload, taken from an article on [Medium](https://medium.com/@the.bilal.rizwan/graphql-common-vuln
The medium article is referenced, and the content below is not just simply snatched, which makes this okay and not violating that person's article.

2020-11-15 08:26 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +> "It's often useful to ask a GraphQL schema for information about what queries it supports. GraphQL allows us to do so using the [introspection](https://graphql.org/learn/introspection/) system!"
From the graphql.org site, the link is on the word introspection and it is the sentence which starts the introspection info page.

2020-11-15 08:29 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +In the example application, a single request can be sent in order to extract all of the veterinary names using the guessable ID (it's an increasing integer). An attacker can then utilize the names in
Deleted.

2020-11-15 08:30 UTC, 1Oreo commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +The most straightforward way is to send an HTTP request (using a personal proxy) with the following payload, taken from an article on [Medium](https://medium.com/@the.bilal.rizwan/graphql-common-vuln
I'm leaving these 2 comments unresolved, if there is anything else I need to do, ping me. For the time being, I've deleted WAF from the file, and pushing the latest version.

2020-11-15 11:59 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +> "It's often useful to ask a GraphQL schema for information about what queries it supports. GraphQL allows us to do so using the [introspection](https://graphql.org/learn/introspection/) system!"
```suggestion

Introspection queries are the way GraphQL lets you ask what queries are supported, which data types are available, and many more details you will need when approaching a test of a GraphQL deployment.

The [GraphQL website describes Introspection](https://graphql.org/learn/introspection/):

2020-11-15 12:00 UTC, victoriadrake approved these changes

2020-11-15 12:27 UTC, kingthorin approved these changes

2020-11-15 12:28 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +- [GraphQL (Add-on for OWASP ZAP](https://www.zaproxy.org/blog/2020-08-28-introducing-the-graphql-add-on-for-zap/)
```suggestion
- [GraphQL (Add-on for OWASP ZAP)](https://www.zaproxy.org/blog/2020-08-28-introducing-the-graphql-add-on-for-zap/)
```

2020-11-15 12:32 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +- [User side testing (XSS and other vulnerabilities)](https://github.com/OWASP/wstg/tree/master/document/4-Web_Application_Security_Testing/11-Client-side_Testing)
```suggestion
- [Client-side Testing](../11-Client-side_Testing) (XSS and other vulnerabilities)
```

2020-11-15 12:35 UTC, kingthorin approved these changes

2020-11-15 12:46 UTC, rejahrehim commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +_Figure 12.1-1: GraphQL Voyager_
*Figure 12.1-1: GraphQL Voyager*

2020-11-15 12:50 UTC, rejahrehim requested changes

2020-11-15 12:50 UTC, rejahrehim commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +_Figure 12.1-2: GraphQL Playground High Level API Docs_
*Figure 12.1-2: GraphQL Playground High Level API Docs*

2020-11-15 12:50 UTC, rejahrehim commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +_Figure 12.1-3: GraphQL Playground API Schema_
*Figure 12.1-3: GraphQL Playground API Schema*

2020-11-15 12:50 UTC, rejahrehim commented on document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
> +_Figure 12.1-4: GraphQL Auth Query API_
*Figure 12.1-4: GraphQL Auth Query API*

2020-11-15 15:29 UTC, rejahrehim approved these changes

2020-11-15 15:31 UTC, merged