Feature json checklist 376
OWASP/wstg pull request #584
Opened 2020-10-12 17:54 UTC by rejahrehim

This PR is part of issue #376

- [ ] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

-  Initial commit for JSON checklist generator 
- Github action to send PR with updated JSON checklist

Current format

```
{
    "categories": {
        "Information Gathering": {
            "id":"WSTG-INFO",
            "tests":[
                {
                "name":"Conduct Search Engine Discovery Reconnaissance for Information Leakage",
                "id":"WSTG-INFO-01",
                "Reference":"https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/01-Information_Gathering/01-Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage.html"
                }]
       }
}
```

Need to update `"Objectives": "<Grab objectives>",` and `"CRE_ID": "<CRE_IDn>"`
We have to decide how to handle `Objectives` and `CRE_ID`

2020-10-12 23:16 UTC, kingthorin requested changes

2020-10-12 23:16 UTC, kingthorin commented on .github/workflows/build-json.yml
> +name: Deploy Latest WSTG Json Checklist
```suggestion
name: Deploy Latest JSON Checklist
```

2020-10-12 23:16 UTC, kingthorin commented on .github/workflows/build-json.yml
> +        node-version: 12.x
Any reason not to do `13.x` or even `14.x`?

2020-10-12 23:16 UTC, kingthorin commented on .github/workflows/build-json.yml
> +    - name: Install dependencies
```suggestion
    - name: Install Dependencies
```

2020-10-12 23:16 UTC, kingthorin commented on .github/workflows/build-json.yml
> +    - name: Run Json Build
```suggestion
    - name: Run JSON Build
```

2020-10-12 23:16 UTC, kingthorin commented on .github/workflows/build-json.yml
> +        git add checklist/Testing-checklist.json
```suggestion
        git add checklist/checklist.json
```

2020-10-12 23:16 UTC, kingthorin commented on .github/workflows/build-json.yml
> +        git commit -m "Publish Latest Json checklist $SHORT_DATE" -m "Updates based on $SRC_BASE"
```suggestion
        git commit -m "Publish Latest JSON checklist $SHORT_DATE" -m "Updates based on $SRC_BASE"
```

2020-10-12 23:16 UTC, kingthorin commented on json/scripts/make-json.sh
> +mv testing-checklist.json ../../checklist/Testing-checklist.json
```suggestion
mv testing-checklist.json ../../checklist/.
```

2020-10-13 04:38 UTC, rejahrehim commented on .github/workflows/build-json.yml
> +        node-version: 12.x
Updated to 14.x

2020-10-13 04:39 UTC, rejahrehim commented on .github/workflows/build-json.yml
> +        git add checklist/Testing-checklist.json
File name updated to `checklist.json`

2020-10-13 04:39 UTC, rejahrehim commented on json/scripts/make-json.sh
> +mv testing-checklist.json ../../checklist/Testing-checklist.json
File name updated to `checklist.json`

2020-10-13 09:45 UTC, kingthorin approved these changes
Looks good, thanks ⭐

2020-10-13 10:39 UTC, kingthorin commented
Should add a check that the file is actually changed before trying to raise the PR. I've done so elsewhere, will dig up the necessary details in a few hours.

2020-10-13 11:41 UTC, kingthorin commented on .github/workflows/build-json.yml
> +        hub pull-request --no-edit
```suggestion
        ## If there are changes: comment, commit, PR
        if ! git diff-index --quiet HEAD --; then 
          git remote set-url origin https://$GITHUB_USER:${{ secrets.wstg_deploy_token }}@github.com/OWASP/wstg.git
          git add checklist/checklist.json
          git commit -m "Publish Latest JSON checklist $SHORT_DATE" -m "Updates based on $SRC_BASE"
          git push --set-upstream origin $BRANCH_STAMP
          hub pull-request --no-edit
        fi
```

2020-10-13 11:41 UTC, kingthorin commented on .github/workflows/build-json.yml
> +
```suggestion
```

2020-10-13 13:50 UTC, kingthorin reviewed
Looks good, thanks ⭐

2020-10-16 15:35 UTC, ThunderSon commented
Any artifact that can be reviewed from my side?

2020-10-16 15:49 UTC, ThunderSon reviewed
Basic comments.
Another question, can this JSON file be somewhat done differently than just parsing line by line like this? Like a template that gets injected with the required data. Not a hard requirement now, but I can see this becoming bad for however wanna push this work forward later down the line.

2020-10-16 15:49 UTC, ThunderSon commented on json/scripts/make-json.sh
> +            fi
Wouldn't setting this condition at the closing end better in terms of formatting?

2020-10-16 15:49 UTC, ThunderSon commented on json/scripts/make-json.sh
> +                    fi
Same comment for this

2020-10-16 15:49 UTC, ThunderSon commented on json/scripts/make-json.sh
> +                    tname=$(head -n 1 $file)
From a small research, I believe this is a better format.
```suggestion
                    read -r tname < $file
```

2020-10-19 04:34 UTC, rejahrehim commented on json/scripts/make-json.sh
> +            fi
Tried, but getting the number of entries is bit complected.

2020-10-19 04:34 UTC, rejahrehim commented on json/scripts/make-json.sh
> +                    fi
Tried, but getting the number of entries is bit complected.  Also, We have to exclude `README.md` Files.

2020-10-19 09:08 UTC, kingthorin approved these changes

2020-10-19 10:11 UTC, ThunderSon approved these changes
Thanks! :)

2020-10-19 10:12 UTC, merged