Improper Error Handling Scenario
OWASP/wstg pull request #601
Opened 2020-10-22 12:09 UTC by ThunderSon

This PR closes #590 .

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Rewrite the error handling scenarios into one.
- Describe the issues pertaining to error handling

After this is validated, the 2 other scenarios can be removed.

2020-10-22 16:14 UTC, ThunderSon commented
@kingthorin I added a playground section, I am considering this for every test. There are juice shops and SKF labs that we can easily reference where possible.

@bkimminich is referencing Juice Shop like this good for you?

2020-10-22 16:15 UTC, ThunderSon commented
@kingthorin should we map to parts of the information mapping chapter as well?

2020-10-30 02:59 UTC, kingthorin requested changes
Looking good. Thanks for the contribution.

Shall we put a placeholder in for WSTG-ERRH-02?

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +All types of applications (web apps, web servers, databases, etc.) will generate errors for various reasons. A lot of the times, developers ignore handling these errors, or push away the idea that a
```suggestion
All types of applications (web apps, web servers, databases, etc.) will generate errors for various reasons. Developers often ignore handling these errors, or push away the idea that a user will ever try to trigger an error purposefully (*e.g.* sending a string where an integer is expected). When the developer only consider the happy path, they forget all other possible user-input the code can receive but can't handle.
```

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +Most applications present them with error codes (and these codes can be understood from documentation), and they are shown usually as exceptions.
I'm not sold on this line. It could be dropped, if not it should be rewritten. As-is it kinda suggests both error codes and exceptions are the 'norm'.

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +- Controls bypass where a certain exception is not restricted by the logic set around the happy path.
```suggestion
- Controls bypass where a certain exception is not restricted by the logic set around the happy path.
- Gain insight into internal hostnames, IPs, or file system/disk location details. (Which may lead to other types of attack or social engineering issues.)
```

Or something like that, I'm not 100% happy with my suggested addition but hopefully if gives you some ideas :wink:

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +- Analyse the different codes returned.
```suggestion
- Identify existing error output.
- Analyze the different output returned.
```

I think we established earlier it isn't limited to codes.

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +In order to bring these error messages out, a tester must:
```suggestion
In order to trigger error messages, a tester must:
```

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +  - Even if errors are handled on the application level, breaking the HTTP RFC makes the integrated web server to show itself since it has to handle the request, and developers forget to override the
```suggestion
  - Even if errors are handled on the application level, breaking the HTTP RFC may make the integrated web server show itself since it has to handle the request, and developers forget to override these errors.
```

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +Applications are the most susceptible to let out a wide variety of error messages, which range from stack traces, memory dumps, mishandled exceptions, and generic errors. This happens due to the fact
```suggestion
Applications are the most susceptible to let out a wide variety of error messages, which include: Stack traces, memory dumps, mishandled exceptions, and generic errors. This happens due to the fact that applications are custom built most of the time and the developers need to observe and handle all possible error cases (or have a global error catching mechanism), and these errors can appear from integrations with other services.
```

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +   - If fuzzing isn't an option, handpick the viable input that have the highest chance to break a certain parser (*e.g.* a closing bracket for a JSON body, a large text where only a couple of charac
```suggestion
   - If fuzzing isn't an option, handpick viable inputs that have the highest chance to break a certain parser (*e.g.* a closing bracket for a JSON body, a large text where only a couple of characters are expected, CLRF injection with parameters that might be parsed by servers and input validation controls, special characters that aren't applicable for file names, etc.).
```

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +4. Understand the service responding with the error message and try to make a more refined fuzz list to bring out more juice from that service (it could be a database, a standalone service, etc.).
```suggestion
4. Understand the service responding with the error message and try to make a more refined fuzz list to bring out more information or error details from that service (it could be a database, a standalone service, etc.).
```

2020-10-30 02:59 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling.md
> +For remediation, check out the [proactive controls C10](https://owasp.org/www-project-proactive-controls/v3/en/c10-errors-exceptions) and the [error handling cheat sheet](https://cheatsheetseries.owa
```suggestion
For remediation, check out the [Proactive Controls C10](https://owasp.org/www-project-proactive-controls/v3/en/c10-errors-exceptions) and the [Error Handling Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html).
```

2020-10-30 09:25 UTC, ThunderSon commented
Done and dusted. Let me know if there's anything more to improve

2020-10-30 09:39 UTC, kingthorin commented
I think the only thing outstanding would be link/index updates.

2020-10-30 10:30 UTC, ThunderSon commented
Thanks for reminding me. Last commit handles that.

2020-10-30 11:22 UTC, kingthorin approved these changes
Thanks!

2020-10-30 11:23 UTC, merged