v4.2 Prep Work
OWASP/wstg pull request #613
Opened 2020-11-13 12:19 UTC by kingthorin

- Create `.github/www/v42`
- Update `.github/www/stable/prepend.txt` to include the new breadcrumb component.
- Update credits and history.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

2020-11-13 12:22 UTC, kingthorin commented
I'll rebase this PR after: https://github.com/OWASP/wstg/pull/612is merged.

2020-11-13 22:17 UTC, ThunderSon requested changes

2020-11-13 22:17 UTC, ThunderSon commented on document/2-Introduction/README.md
> +Linking to Web Security Testing Guide scenarios should be done using versioned links not `stable` or `latest` which will definitely change with time. However, it is the project team's intention that
```suggestion
Linking to Web Security Testing Guide scenarios should be done using versioned links not `stable` or `latest` which will definitely change with time. However, it is the project team's intention that versioned links not change. For example: `https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server.html`. Note: the `v42` element refers to version 4.2.
```

2020-11-13 22:17 UTC, ThunderSon commented on document/6-Appendix/E-History.md
> +- Matteo Meucci: OWASP Testing Guide Lead since 2007-2020.
```suggestion
- Matteo Meucci: OWASP Testing Guide Lead 2007-2020.
```

2020-11-14 15:41 UTC, ThunderSon commented
@kingthorin not sure you committed the changes? It looks similar.

2020-11-14 17:29 UTC, kingthorin commented
It is the same it’s just rebased to pickup the change on the failing link.

2020-11-14 17:33 UTC, ThunderSon commented
@kingthorin you set the conversations are resolved without having any changes in. Is that what you wanted?

2020-11-14 17:34 UTC, kingthorin commented
Yup I had accidentally overwritten their commits, fixed now.

2020-11-14 17:40 UTC, ThunderSon commented on document/1-Frontispiece/README.md
> +## Version 4.2
I think before merging, we need to change the description of this part.
Let's review the change logs (when you can generate them, no rush), and let's set it accordingly.

2020-11-14 17:44 UTC, kingthorin commented on document/1-Frontispiece/README.md
> +## Version 4.2
Yup that does make sense, I did  have a quick look at it when I was putting this PR together but I couldn't think of what I'd rather say so I just forged ahead anyway.

I think doing it after prepping change notes and repo history is a good move.

2020-11-14 17:44 UTC, kingthorin commented on document/1-Frontispiece/README.md
> +## Version 4.2
Let's tackle that as along PR though. It'll probably take me a few days (if not longer) to tackle the notes, then swing back around to this.

2020-11-14 19:24 UTC, ThunderSon approved these changes

2020-11-14 19:26 UTC, merged