SSI Duplicate
OWASP/wstg pull request #618
Opened 2020-11-14 17:57 UTC by n17h31sm

This PR covers issue #593 .

- [x] This PR handles the issue and requires no additional PRs.

**What did this PR accomplish?**

- Removed the unneeded information from the introduction and merged the sufficient parts into one
- Cleaned the methodology testing paragraphs
- Added some more references

2020-11-14 21:42 UTC, ThunderSon requested changes
I don't feel like the gray testing paragraph is worth it.
Can you remove it and my salvage what could be salvaged, and remove the headers "Black box testing" and "Grey box testing". They're not needed.

2020-11-14 21:42 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +### Testing examples
Can we remove this section from this part and use what's mainly needed in the How to Test section?

2020-11-14 21:42 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +There are more directives and variables which you can find [here](http://www.cheat-sheets.org/sites/ssi.su/)
Refer to this instead: https://httpd.apache.org/docs/current/howto/ssi.html

2020-11-14 21:43 UTC, ThunderSon requested changes

2020-11-14 21:43 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> -## Test Objectives
This is needed. Please set this back in as well :)

2020-11-16 14:35 UTC, n17h31sm commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> -## Test Objectives
This is now moved to the introduction before the how to test

2020-11-16 16:06 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> -## Test Objectives
This is needed as a section before the ## How to Test. It's the format we parse our checklist against.

2020-11-16 21:06 UTC, n17h31sm commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> -## Test Objectives
## Test Objectives section returned

2020-11-18 10:22 UTC, ThunderSon commented
Looks good. I will send a commit when you finish your reviews to clean up some minimal stuff (links, refs, etc.)

2020-11-19 01:06 UTC, victoriadrake reviewed
Copy editing.

2020-11-19 01:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +To test this we have to find all the pages where user input is allowed. Possible input vectors may also include Headers and Cookies. Determine how the input is stored and used, i.e if the input is re
```suggestion
First find all the pages where user input is allowed. Possible input vectors may also include headers and cookies. Determine how the input is stored and used, i.e if the input is returned as an error message or page element and if it was modified in some way. Access to the source code can help you to more easily determine where the input vectors are and how input is handled.
```

2020-11-19 01:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +Once we have a list of potential injection points, we can check if the input is correctly validated. We need to make sure that we can inject characters used in SSI directives:
```suggestion
Once you have a list of potential injection points, you may determine if the input is correctly validated. Ensure it is possible to inject characters used in SSI directives:
```

2020-11-19 01:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +Testing if the SSI Injection is exploitable is very simillar to testing for XSS using
```suggestion
Testing to see if SSI injection is exploitable is very similar to testing for XSS. You may use a string like the following:
```

2020-11-19 01:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +For SSI Injection we can use the directives listed below.
```suggestion
For SSI injection we can use the directives listed below.
```

2020-11-19 01:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +Returns the value of the variable. [List of SSI include variables](https://httpd.apache.org/docs/current/howto/ssi.html)
```suggestion
This example returns the value of the variable. [See list of SSI include variables](https://httpd.apache.org/docs/current/howto/ssi.html).
```

2020-11-19 01:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +If the supplied file is a CGI script the directive will include the output of the CGI script. But the directive may also be used to include the content of a file or list files in a directory.
```suggestion
If the supplied file is a CGI script, this directive will include the output of the CGI script. This directive may also be used to include the content of a file or list files in a directory.
```

2020-11-19 01:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +There are more directives and variables which you can find [here](https://httpd.apache.org/docs/current/howto/ssi.html)
```suggestion
You can find more directives and variables [here](https://httpd.apache.org/docs/current/howto/ssi.html).
```

2020-11-19 01:07 UTC, victoriadrake approved these changes

2020-11-19 21:00 UTC, ThunderSon commented
I did various updates as I read through the document and updated some references.
@n17h31sm please let me know if the changes are good with you as well.

2020-11-20 00:06 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md
> +The below example returns the value of the variable. Check the [references](#references) section to better assess the system at hand with every server's documentation.
```suggestion
The below example returns the value of the variable. The [references](#references) section has helpful links with server-specific documentation to help you better assess a particular system.
```

2020-11-20 10:57 UTC, n17h31sm commented
I checked the changes, it seems fine to me as well. Maybe just also commit @victoriadrake proposed change.

2020-11-20 11:05 UTC, kingthorin approved these changes
Thanks

2020-11-20 11:10 UTC, ThunderSon approved these changes
Vic's way with words is always better, no doubts about that!

2020-11-20 11:12 UTC, merged

2020-11-20 11:18 UTC, victoriadrake commented
Glad to be able to help! Thank you for your contribution, @n17h31sm! Congratulations on the merge! :tada: