Last Test Objectives -- SESS, INPV, BUSL
OWASP/wstg pull request #620
Opened 2020-11-16 12:31 UTC by ThunderSon

This PR closes #602 

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Set all SESS test objectives that were missing.
- Set BUSL test objectives.
- Format INPV tests objectives

2020-11-16 20:57 UTC, kingthorin requested changes

2020-11-16 20:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/03-Test_Integrity_Checks.md
> +- Determine who should be allowed to modify or read that data in each componenet
```suggestion
- Determine who should be allowed to modify or read that data in each component.
```

2020-11-16 20:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/03-Test_Integrity_Checks.md
> +- Attempt to insert, update, or edit delete the data values with invalid data into each component by users that should not be allowed per the business logic workflow.
```suggestion
- Attempt to insert, update, or delete data values used by each component that should not be allowed per the business logic workflow.
```

2020-11-16 20:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/04-Test_for_Process_Timing.md
> +- Develop and execute the mis-use cases.
```suggestion
- Develop and execute misuse cases.
```

2020-11-16 20:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/05-Test_Number_of_Times_a_Function_Can_Be_Used_Limits.md
> +- Assess if their is a logical limit set on the functions and if it is properly validated.
```suggestion
- Assess if there is a logical limit set on the functions and if it is properly validated.
```

2020-11-16 20:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/06-Testing_for_the_Circumvention_of_Work_Flows.md
> +- Review the project documentation for methods to skip or go to steps in the application process in a different order from the intended business logic flow.
```suggestion
- Review the project documentation for methods to skip or go through steps in the application process in a different order from the intended business logic flow.
```

2020-11-16 21:18 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/05-Test_Number_of_Times_a_Function_Can_Be_Used_Limits.md
> +- Assess if their is a logical limit set on the functions and if it is properly validated.
Oof that was bad. Surprised you still respect me.

2020-11-19 11:01 UTC, kingthorin commented
> rick's lint

Hahahahahaha 😃

2020-11-19 11:03 UTC, kingthorin approved these changes

2020-11-19 11:03 UTC, merged