Fix link issues in PDF build 4.2
OWASP/wstg pull request #631
Opened 2020-11-20 15:45 UTC by rejahrehim

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Fix linking issue  in PDF while including links to the Appendix 
- Fix linking issue  in PDF while including external markdown URLs with fragment

2020-11-20 18:30 UTC, kingthorin approved these changes
Thanks

2020-11-20 18:32 UTC, ThunderSon commented
Still reviewing the PDF.
For now:
1. The links in the sidebar are broken (if they are related to this script).
2. In the GraphQL **References** section, Client-side Testing has a reference to localhost (maybe it happened cause of the - in client-side. Page 435 of the PDF, 432 in the book numbering

2020-11-21 05:50 UTC, rejahrehim commented
> Still reviewing the PDF.
> For now:
> 
>     1. The links in the sidebar are broken (if they are related to this script).
> 
>     2. In the GraphQL **References** section, Client-side Testing has a reference to localhost (maybe it happened cause of the - in client-side. Page 435 of the PDF, 432 in the book numbering

 I will update this PR with the fixes

2020-11-21 21:44 UTC, rejahrehim commented
> > Still reviewing the PDF.
> > For now:
> > ```
> > 1. The links in the sidebar are broken (if they are related to this script).
> > 
> > 2. In the GraphQL **References** section, Client-side Testing has a reference to localhost (maybe it happened cause of the - in client-side. Page 435 of the PDF, 432 in the book numbering
> > ```
> 
> I will update this PR with the fixes

These two issues fixed. @ThunderSon @kingthorin

2020-11-22 02:52 UTC, kingthorin approved these changes
Thanks

2020-11-23 17:51 UTC, ThunderSon commented
In the latest build, WSTG-CRYP-03 in the summary, the ASVS link isn't working properly. I am guessing other new github links don't work. I'll try and find more examples.

2020-11-24 16:55 UTC, rejahrehim commented
> In the latest build, WSTG-CRYP-03 in the summary, the ASVS link isn't working properly. I am guessing other new github links don't work. I'll try and find more examples.

Fixed

2020-11-26 21:39 UTC, ThunderSon requested changes
On line 246, it should `ABCDEF` now with the new appendix :)
Fantastic work mate.

2020-11-27 11:45 UTC, rejahrehim commented on .github/pdf/scripts/make-pdf.sh
> +    python -c "import re; import sys; print(re.sub(r'id=\"([^\n]+)\"', lambda m: m.group().replace(',', ''), sys.stdin.read()))"
Checked. It works !

2020-11-27 11:45 UTC, rejahrehim commented on .github/pdf/scripts/make-pdf.sh
> +    python -c "import re; import sys; print(re.sub(r'href=\"(#[^\"]*\.md)\"', lambda m: m.group().replace('_', '-'), sys.stdin.read()))"
Checked. It works !

2020-11-27 11:47 UTC, rejahrehim commented
> On line 246, it should `ABCDEF` now with the new appendix :)
Fixed 👍

2020-11-27 11:48 UTC, ThunderSon approved these changes
Thanks!

2020-11-27 11:49 UTC, merged