Review Pre-4.2
OWASP/wstg pull request #635
Opened 2020-11-23 21:11 UTC by ThunderSon

This PR contains:
- Ensure a certain structure was followed, which should be reflected in the template we recommend. All previous tests have been adjusted accordingly as well.
- Improve code highlighting language.
- Touch up code snippets where possible.
- Improve guide readability.
And various tweaks where possible.

Apologies for the huge single commit.

2020-11-23 21:23 UTC, ThunderSon commented
It's okay to ignore this for now. If this is a consistent response through the action we'll filter it.

2020-11-24 19:55 UTC, kingthorin requested changes

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/03-Test_Integrity_Checks.md
> +The application must be smart enough to check for relational edits and not allow users to submit information directly to the server that is not valid, trusted because it came from a non-editable cont
Can you tweak the first sentence. It's long and I'm not 100% sure what you're going for. If feels like there's an "and" missing at the comma or something.... 🤷

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/05-Test_Number_of_Times_a_Function_Can_Be_Used_Limits.md
> +The application should have checks to ensure that the business logic is being followed and that if a function/action can only be executed a certain number of times, when the limit is reached the user
I'm not sure we should suggest cookies as a prevention mechanism for function/access use since they're user controllable.

There are some lame brain account lockouts that use that and it's just scary/horrible.

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/07-Test_Defenses_Against_Application_Misuse.md
> +Build inactive defenses against application misuse.
You must have been getting tired or something..... "inactive defenses" is some sort of oxymoron.

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/08-Test_Upload_of_Unexpected_File_Types.md
> +The application may be expecting only certain file types to be uploaded for processing, such as `.csv`, `.txt` files. The application may not validate the uploaded file by extension (for low assuranc
```suggestion
The application may be expecting only certain file types to be uploaded for processing, such as `.csv` or `.txt` files. The application may not validate the uploaded file by extension (for low assurance file validation) or content (high assurance file validation). This may result in unexpected system or database results within the application/system or give attackers additional methods to exploit the application/system.
```

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/08-Test_Upload_of_Unexpected_File_Types.md
> +Applications should be developed with mechanisms to only accept and manipulate “acceptable“ files that the rest of the application functionality is ready to handle and expecting. Some specific exampl
```suggestion
Applications should be developed with mechanisms to only accept and manipulate "acceptable" files that the rest of the application functionality is ready to handle and expecting. Some specific examples include: deny lists or allow lists of file extensions, using "Content-Type" from the header, or using a file type recognizer, all to only allow specified file types into the system.
```

Standard non-curly quotes 👍

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/02-Testing_for_JavaScript_Execution.md
> +Consider the following DOM XSS exercise <http://www.domxss.com/domxss/01_Basics/04_eval.html>
```suggestion
Consider the following: [DOM XSS exercise](http://www.domxss.com/domxss/01_Basics/04_eval.html)
```

I don't think we parse this type of link properly in the PDF build so let's just avoid it.

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/03-Testing_for_HTML_Injection.md
> +Consider the following DOM XSS exercise <http://www.domxss.com/domxss/01_Basics/06_jquery_old_html.html>
```suggestion
Consider the following: [DOM XSS exercise](http://www.domxss.com/domxss/01_Basics/06_jquery_old_html.html)
```

I don't think we parse this type of link properly in the PDF build so let's just avoid it.

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
> +Some frame busting techniques try to break frame by assigning a value to the `parent.location` attribute in the “counter-action” statement.
```suggestion
Some frame busting techniques try to break frame by assigning a value to the `parent.location` attribute in the "counter-action" statement.
```

2020-11-24 19:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
>  #### Server-side protection: X-Frame-Options
```suggestion
#### Server-side Protection: X-Frame-Options
```

Can you check for others in this doc too? Pls & tks.

2020-11-24 19:55 UTC, kingthorin commented on document/6-Appendix/F-Leveraging_Dev_Tools.md
> +`*` Anything that applies to Google Chrome should be applicable to all Chromium based applications.
It "should" be obvious or known to testers that this now includes Edge but I didn't want to make assumptions that readers have a clue. I like the change you've made but I think we still need to call-out MS/Edge somehow.

> `*` Anything that applies to Google Chrome should be applicable to all Chromium based applications. (Which includes Microsoft rebadging Edge around 2019/2020.)

2020-11-24 21:07 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/07-Test_Defenses_Against_Application_Misuse.md
> +Build inactive defenses against application misuse.
I actually wanted to remove this .... Hahaha. Let me update this to something worthy.

2020-11-24 22:42 UTC, kingthorin approved these changes
LGTM

2020-11-25 12:11 UTC, ThunderSon commented
@kingthorin we should be good now. Everything is done as a "major" reform for the guide.

2020-11-25 12:27 UTC, kingthorin approved these changes

2020-11-25 12:27 UTC, merged