Chore/reporting
OWASP/wstg pull request #643
Opened 2020-11-28 22:55 UTC by ThunderSon

Fixes #639 

This PR improves the reporting page, makes it easy to use and directly implement by testers, with the addition of references to help them build and customize their reports.

2020-11-28 22:57 UTC, ThunderSon commented
@rbsec is this something that feels usable by a both a senior and a junior tester? Any improvements that you see?

2020-11-28 23:57 UTC, kingthorin requested changes

2020-11-28 23:57 UTC, kingthorin commented on document/5-Reporting/README.md
> +  - On certain engagements it is required to have the [CVSS](https://www.first.org/cvss/) score. If not required, sometimes it is good to have, and other times it just adds complexity to the report.
```suggestion
  - On certain engagements it is required to have a [CVSS](https://www.first.org/cvss/) score. If not required, sometimes it is good to have, and other times it just adds complexity to the report.
```

2020-11-28 23:57 UTC, kingthorin commented on document/5-Reporting/README.md
> +- A detailed description of what is the vulnerability, how to exploit it, and the damage it can inflict.
```suggestion
- A detailed description of what the vulnerability is, how to exploit it, and the damage that may result from its abuse.
```

2020-11-29 08:49 UTC, ThunderSon commented on document/5-Reporting/README.md
> +- A checklist of all the tests conducted, such as the [WSTG checklist](https://github.com/OWASP/wstg/tree/master/checklist). These can provided as attachements to the report.
```suggestion
- A checklist of all the tests conducted, such as the [WSTG checklist](https://github.com/OWASP/wstg/tree/master/checklist). These can be provided as attachments to the report.
```

2020-11-29 10:35 UTC, rbsec reviewed
@ThunderSon I've made various comments. These are all my (subjective) opinion - everyone has different ideas about what they like to see in reports - so feel free to ignore any that you disagree with.

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +Note: It is advised to secure the report by using a password or any similar technology as pentest reports are marked as sensitive information.
Talking about a password brings to mind the rubbish "password protection" that things like MS Access used to have, that you could trivially bypass. The key thing is that the report needs to be *encrypted*.

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +What this test will cover precisely. This is crucial in order to set the boundaries of the engagement.
This should be in the past tense, rather than the future tense.

It's also important to list any caveats on the scope (broken functionality, areas that you weren't allowed to test, other limitations)

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +The purpose of this engagement and the need for it.
This should include any specific questions that they were trying to answer, and also either here or the next section should include the perspective from which testing was carried out (authenticated, given a digital certificate, etc)

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- State of the application. A concise and direct conclusion that states whether the application is secure or not.
Not sure about this - can you ever state that an application is secure? Or just that you didn't find any significant issues

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- Key risks identified by the test.
When I see bad executive summaries, it's usually because they are just trying to summarise the contents of the report. That's fine for a *technical* summary, but not an *executive* summary. For example:

> The application is vulnerable to blind SQL injection, which allows a user to read any information from the database.

Is not good for an executive summary, because a CEO doesn't know care what SQL injection, and may not even know what a database is.

The key thing about an executive summary is that it need to explain the what the findings of the report mean *in business context*. This means talking about things like compliance with PCI DSS/GDPR/HIPAA, fines, reputational damage, etc.

Not "This is what I found", but more "This is why you should care about what I found".

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- Key recommendations for the organization.
If you're giving recommendations, these should generally be strategic rather than tactical.

A tactical recommendation would be "install the missing patches" - and you can give that in the issue section.

A strategic recommendation would be more like "implement a regular patching policy, and carry out authenticated patch scans to identify any that are missing".

Not "This is how to fix the issues" (because that's explained in the issues), but "This is how to stop the issues happening again".

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +This section is aimed at the technical team. It should include all the necessary information to understand the vulnerability, replicate it, and resolve it.
It can be good to split this into multiple sections - for example if you have two applications, or a webapp and a mobile app.

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- Exploitability, or likelihood. This states the persona that is capable of exploiting said vulnerability based on how easy it is to achieve it, the level of access, and the impact achieved, which is
I don't think "persona" is the right word here.

Would this perhaps look better as a nested list? Something like:

* The likelihood or exploitability of the issue, based on various factors such as:
  * How easy it is to exploit.
  * Whether public exploit code is available.
  * The level of access required.
  * Whether an attacker would be motivated to exploit it

Also, "impact" isn't really part of the exploitability/likelihood - it should be its own section

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +  - Possible values are "User", "Technical", "Hacker".
I disagree with this - I don't think "Exploitability: Hacker" tells you anything

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +  - Possible values are: "Informational", "Low", "Medium", "High", "Critical".
What is this based on? The way I've usually see it is that you have "impact" and "likelihood", and you work out the overall risk by (effectively) multiplying those. Should be explained in an appendix

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- A detailed description of what the vulnerability is, how to exploit it, and the damage that may result from its abuse.
This should include your screenshots, PoC code, etc

Should also be masking sensitive data (passwords, personal information, PANs, etc)

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- A detailed remediation on how to resolve the vulnerability, possible improvements that could help strengthen the posture, and missing security practices.
"A detailed remediation" doesn't quite read right, should be something like "Detailed steps on how to remediate the vulnerability"

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- Provide any additional resources that could help the reader to understand the vulnerability, such as an image, a video, a CVE, an external guide, etc.
Remove "Provide" - doesn't fit with the others

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +Findings can be delivered in normal format, like the above, it could be delivered in a table format that can formatted in various ways, or any other format that the testers see as fitting to deliver
You use the word "format" five times in one sentence

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- Reference ID, which can be used for communication between parties and for other references across the report.
Somewhere in here you should also be cross-referencing any other relevant issues (for example, from the lack of a CSP to the application being vulnerable to XSS). I prefer to do that in the issue body, but some reports have a list of "related issues" or something like that

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +This should be concise, providing the organization with high level points to go after, risks to consider before going live, etc.
This just sounds like it's repeating the executive summary?

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- the run down of the report in a page or two.
This seems to be mostly repeating the points below - perhaps remove or turn into a few sentences?

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +### 1.1 Objective
I like to have an introduction section in the report, which contains all the boring stuff:

- Contents page
- Details of who did the testing
- Distribution list/client contacts
- Version history
- A disclaimer somewhere to state that a pentest is a point-in-time assessment, and that you're not guaranteeing to have found every issue in the application.

You could also put things like the scope/timeline in here - because an executive doesn't really care about them most of the time.

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +## Appendices
Is it worth covering retesting somewhere? If you've tested the environment before, you also want a retest section that includes:

- A high-level summary of the change since the last test
- A table showing the resolution status of every issue
- Cross-references to any outstanding issues

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +## 2. Detailed Findings
Somewhere in this section there should be a table of all the risks with something like:

- Reference
- Title
- Risk level

These usually get copied into Excel spreadsheets and used to track the resolution status by the devs

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +Findings can be delivered in normal format, like the above, it could be delivered in a table format that can formatted in various ways, or any other format that the testers see as fitting to deliver
By "normal format" I presume you mean "text"?

One question that you should always ask when writing an issue is:

> Does this give enough information for the developer to understand and fix this issue?

And if not, then you need to add something.

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +- Tools used, scripts, and the relevant generated output.
I wouldn't normally bother with this, but quite a lot of companies do. Not really that useful to find out that they used Firefox, Chrome and Notepad on a test...

2020-11-29 10:35 UTC, rbsec commented on document/5-Reporting/README.md
> +The summary should contain, in the best possible form to deliver the message (*e.g.* graphs, tables, lists, etc.):
If you're going to include graphs, then make sure that they're actually useful. For example, don't put a pie chart showing risk levels (which is pretty common)

2020-11-29 12:22 UTC, ThunderSon commented on document/5-Reporting/README.md
> +- State of the application. A concise and direct conclusion that states whether the application is secure or not.
Sometimes an application can afford to go live and have patches along the way. A misconforming error mesage doesn't stop a release, but an authentication bypass does. Let me try and reword that.

2020-11-29 13:42 UTC, ThunderSon commented
@rbsec Loved the review. Should've covered most of the comments.

2020-11-29 14:33 UTC, rbsec commented on document/5-Reporting/README.md
> +- State of the application. A concise and direct conclusion that states whether the application is secure or not.
As a pentester, that's not really your decision to make. Your job is to explain the vulnerabilities that you found and how they can be exploited - it's up to the organisation to decide what those mean for them.

2020-11-29 14:44 UTC, ThunderSon commented on document/5-Reporting/README.md
> +- State of the application. A concise and direct conclusion that states whether the application is secure or not.
Valid point, let me remove it.

2020-11-29 15:29 UTC, rbsec approved these changes
I like the changes implemented - I think this is a big improvement over the old version. I've made a few minor comments about grammar, and a couple of suggestions for things to add - but generally I think this is pretty good.

2020-11-29 15:29 UTC, rbsec commented on document/5-Reporting/README.md
> +- Lack of accesses.
"Lack of access" or "Lack of access or credentials"

2020-11-29 15:29 UTC, rbsec commented on document/5-Reporting/README.md
> +*This test is a "point in time" assessment and as such the environment could have changed since the test was run. There is no guarantee that all possible security issues have been identified, and tha
Maybe replace "thus" with "As such" ?

2020-11-29 15:29 UTC, rbsec commented on document/5-Reporting/README.md
> +A disclaimer providing legal protection. The below example should be modified to your use case and shouldn't be used as is.
Bold this warning - we don't want anyone claiming this is legal advice we're giving

2020-11-29 15:29 UTC, rbsec commented on document/5-Reporting/README.md
>  Performing the technical side of the assessment is only half of the overall assessment process. The final product is the production of a well written and informative report. A report should be easy t
Reporting is very often overlooked, so might add a bold sentence like:

> **The quality of the technical testing is completely irrelevant if the client can't understand your findings.**

But up to you.

2020-11-29 15:29 UTC, rbsec commented on document/5-Reporting/README.md
> +Note: It is advised to secure the report and encrypt it to ensure that only the receiving party is able to use it.
I might also add a sentence after this along the lines of:

> This guide provides only suggestions about one possible approach to reporting, and should not be treated as as strict rules that most be followed. When considering any of the recommendations below, always ask yourself: *does this make my report better?*

2020-11-29 16:15 UTC, kingthorin commented
I like this rewrite and excellent feedback from @rbsec!  It might be worth a lead-in sentence that audience should be considered. What’s outlined seems like a very “Consultant delivering an assessment to a client” leaning format. Which is great but likely overkill for an internal assessment, etc

Note I haven’t fully re-read the content so if this is covered I apologize. Will do another full pass later today.

2020-11-29 16:31 UTC, rbsec commented
@kingthorin you're absolutely correct - my back is as an external pentester, so my comments are based on that view. However, I think that the majority of people who write reports are from a similar background. If you're just doing internal testing, then writing formal reports is often overkill - you should really be integrating more into the development process (for example, creating Jira issues directly).

I wonder if this document should perhaps be split into a couple of different ones?

* Consultancy style reports
* Bug bounty reports
* Internal reporting

@ThunderSon what do you tihnk?

2020-11-29 16:44 UTC, kingthorin commented
I think providing guidance on big bounty and other reporting would be a great move for the community in a future revision.

To keep this on point and moving I think an audience note can do the job “for now” 🤪

2020-11-29 17:24 UTC, ThunderSon commented
The main target now is for the consultancy reports.

I am with setting different reporting routes based on need, but that requires a structure that fits that need. Definitely for 4.3~5.

2020-11-29 19:14 UTC, victoriadrake commented on document/5-Reporting/README.md
> +*If this is a re-test, a subsection could be set with the findings summary of the previous test, the status of the identified vulnerabilities, and any cross-references with the current test.*
```suggestion
If this is a re-test, you might create a subsection that summarizes findings of the previous test, the updated status of previously identified vulnerabilities, and any cross-references with the current test.
```

2020-11-29 19:14 UTC, victoriadrake commented on document/5-Reporting/README.md
> +    - The values set in here should be detailed in an appendix to allow the reader to understand how each score was set.
```suggestion
  - Some suggested values are: Informational, Low, Medium, High, and Critical. Ensure that you detail the values you decide to use in an appendix. This allows the reader to understand how each score is determined.
```

2020-11-29 19:14 UTC, victoriadrake commented on document/5-Reporting/README.md
> +- Detailed description of what the vulnerability is, how to exploit it, and the damage that may result from its abuse. Any sensitive data should be masked (*e.g.* passwords, personal information, cre
```suggestion
- Detailed description of what the vulnerability is, how to exploit it, and the damage that may result from its exploitation. Any possibly-sensitive data should be masked, for example, passwords, personal information, or credit card details.
```

2020-11-29 19:14 UTC, victoriadrake commented on document/5-Reporting/README.md
> +**Note:** Always check if the issue provides enough information for the engineer reading this report and if they can take action based on it. If not, the issue should be better explained.
```suggestion
Format this section in a way that best delivers your message.

Always ensure that your descriptions provide enough information for the engineer reading this report to take action based on it. Explain the finding thoroughly and provide as much technical detail as might be necessary to remedy it.
```

2020-11-29 19:14 UTC, victoriadrake commented on document/5-Reporting/README.md
> +_This is not part of the report. More guidance to writing your reports._
```suggestion
This section is not part of the suggested report format. The below links provide more guidance to writing your reports.
```

2020-11-29 19:14 UTC, victoriadrake commented on document/5-Reporting/README.md
> +**The quality of the technical testing is completely irrelevant if the client can't understand your findings.**
```suggestion
A good report helps your client understand your findings and highlights the quality of your technical testing.
```

2020-11-29 19:24 UTC, rbsec commented on document/5-Reporting/README.md
> +**Note:** The summary should be constructive and meaningful, not full of jargon and destructive takeaways. In case graphs are used, make sure they help deliver a message in a clearer way than text wo
I don't really agree with the change to the strategic recommendations suggested here. Mitigating the *current* issues is generally more of a tactical recommendation (such as using HTML encoding to fix the XSS).

Strategic recommendations should address the underlying root cause of the issue (insecure development practices), and give them guidance on how to avoid having the same problems in future (implementing a secure development/defensive coding methodology, using frameworks that protect against these types of issues, etc).

2020-11-30 21:30 UTC, ThunderSon commented
I updated some sections based on your feedback, and tweaked some others to keep a certain meaning.

Let me know if this handles this PR.

2020-12-03 02:19 UTC, kingthorin commented on document/5-Reporting/README.md
> +| 1.0 | Initial report | DD/MM/YYYY | Foo Bar |
```suggestion
| 1.0 | Initial report | DD/MM/YYYY | J. Doe |
```

2020-12-03 02:19 UTC, kingthorin commented on document/5-Reporting/README.md
> +  - How easy it is to exploit it.
```suggestion
  - How easy it is to exploit.
```

2020-12-03 02:19 UTC, kingthorin commented on document/5-Reporting/README.md
> +  - Whether there is a working exploit code for it.
```suggestion
  - Whether there is working exploit code for it.
```

2020-12-03 02:21 UTC, kingthorin approved these changes

2020-12-03 02:22 UTC, merged