Update list of vulnapps in Appendix B
OWASP/wstg pull request #658
Opened 2020-12-05 08:55 UTC by bkimminich

Rationale: VWAD as directory first in list. Then in order of GitHub stars apps from VWAD which had recent (2020) updates and were not all from same technology stack. Bonus condition for OWASP projects was to have a migrated website to appear.

2020-12-05 09:58 UTC, ThunderSon requested changes

2020-12-05 09:58 UTC, ThunderSon commented on document/6-Appendix/B-Suggested_Reading.md
> +- [OWASP WebGoat](https://owasp.org/www-project-webgoat/)
Please plug in first the OWASP ones. I prefer them over DVWA. Some call me biased, but oh well :wink:

2020-12-06 20:32 UTC, kingthorin approved these changes
Thanks

2020-12-06 21:02 UTC, ThunderSon approved these changes
Thank youu!

2020-12-06 21:03 UTC, merged