DRAFT: Update tools appendix
OWASP/wstg pull request #661
Opened 2020-12-05 23:45 UTC by rbsec

Tidy up the tools appendix, as per discussion in #660 

Draft - do not merge yet.

2020-12-05 23:54 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [BlueClosure BC Detect](https://www.blueclosure.com)
Never heard of this

2020-12-05 23:54 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [Toad for Oracle](https://www.quest.com/toad)
Never heard of this, and not sure what it does. Doesn't really seem very webapp focused - remove?

2020-12-05 23:54 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [NGS Typhon](https://www.nccgroup.trust/uk/our-services/cyber-security/technology-solutions/)
This just seems to be an advert for a pentesting company - I don't see any tool here?

2020-12-05 23:54 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [MaxPatrol Security Scanner](https://www.ptsecurity.com/ww-en/products/maxpatrol/)
Never heard of this

2020-12-05 23:54 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [Parasoft SOAtest (more QA-type tool)](https://www.parasoft.com/products/soatest)
Doesn't seem to be a working site

2020-12-05 23:54 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [IndusFace WAS](https://www.indusface.com/web-application-scanning.php)
Never heard of this

2020-12-05 23:54 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
Are these relevant?

Also never heard of most of the code review tools above (but can't comment due to GitHub UI being a bit useless)

2020-12-05 23:56 UTC, rbsec commented
I've never heard of most of the commercial tools here, and there are some bigger names like HP WebInspect that seem to be missing. What's the rationale behind which companies and tools get included in this list (and effectively free advertising or even endorsement from OWASP) and which don't?

2020-12-06 00:39 UTC, kingthorin commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [Toad for Oracle](https://www.quest.com/toad)
Im familiar with Toad it's a sql*net client, but I don't think it's necessary to keep here.

Drop it.

2020-12-06 00:41 UTC, kingthorin commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [NGS Typhon](https://www.nccgroup.trust/uk/our-services/cyber-security/technology-solutions/)
Drop it, don't think the product exists anymore. A quick Google search shows lots of related early 2000s content.

2020-12-06 00:43 UTC, kingthorin commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [MaxPatrol Security Scanner](https://www.ptsecurity.com/ww-en/products/maxpatrol/)
Seems to be a compluance/audit tool. Was able to find up-to-date Gartner mentions of it.

2020-12-06 00:44 UTC, kingthorin commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [Parasoft SOAtest (more QA-type tool)](https://www.parasoft.com/products/soatest)
https://www.parasoft.com/products/parasoft-soatest/

2020-12-06 00:46 UTC, kingthorin commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [IndusFace WAS](https://www.indusface.com/web-application-scanning.php)
I'm ok with dropping it.

2020-12-06 00:49 UTC, kingthorin commented on document/6-Appendix/A-Testing_Tools_Resource.md
You mean Accepance Testing Tools?

If BDD was tyye only entry I'm good with it being dropped.

2020-12-06 00:50 UTC, kingthorin commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Selenium](https://www.seleniumhq.org)
Why drop the slash?

https://www.selenium.dev/ seems to be the primary now.

2020-12-06 00:53 UTC, kingthorin commented
I can tweak the SCA-Commercial section. Im familiar with a number of them, there's an entry or two that just don't make sense.

Obvious Commercial DAST misses should also be addressed.

2020-12-06 09:41 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Selenium](https://www.seleniumhq.org)
I gto rid of the slash because it's redundant (and not included for most of the other URLs) - I've updated it to the new .dev site

2020-12-06 11:02 UTC, kingthorin commented
What's with removing trailing slashes?

2020-12-06 11:18 UTC, rbsec commented
@kingthorin most of the domains don't have them, and they're completely redundant if you're not linking to a subdirectory - so I removed them for consistency.

2020-12-06 11:28 UTC, kingthorin commented
Okay that's fine, I just wanted to understand.

2020-12-10 13:47 UTC, ThunderSon requested changes

2020-12-10 13:47 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Burpsuite Free](https://www.portswigger.net/Burp/)
```suggestion
- [Burp Suite Community Edition](https://portswigger.net/burp/communitydownload)
```

2020-12-10 13:47 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +  - Burp Proxy is an intercepting proxy server for security testing of web applications it allows intercepting and modifying all HTTP(S) traffic passing in both directions, it can work with custom SS
```suggestion
  - Burp Suite is an intercepting proxy for security testing. It allows intercepting and modifying all HTTP(S) traffic passing in both directions, it can work with custom SSL certificates and non-proxy-aware clients.
```

2020-12-10 13:47 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Burpsuite Professional (Intruder)](https://portswigger.net/burp)
```suggestion
- [Burp Suite Professional (Intruder)](https://portswigger.net/burp/pro)
```

2020-12-10 13:47 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Google Hacking Diggity Project](https://resources.bishopfox.com/resources/tools/google-hacking-diggity/)
This is safe to be removed as Bishop Fox declared it obsolete and recommend theHarvester for similar needs.

2020-12-10 13:47 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [BlueClosure BC Detect](https://www.blueclosure.com)
Let's replace with [XSS Strike](https://github.com/s0md3v/XSStrike)

2020-12-10 13:51 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Burpsuite Professional (Intruder)](https://portswigger.net/burp)
Let's remove this. Or we can link to the community edition. Intruder can be used, but it is throttled.

2020-12-10 14:54 UTC, kingthorin commented
There's a conflict that needs to be addressed.

2020-12-10 17:36 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [BlueClosure BC Detect](https://www.blueclosure.com)
That project doesn't seem to have had any commits in the last 12 months - is it still alive?

2020-12-10 17:36 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Google Hacking Diggity Project](https://resources.bishopfox.com/resources/tools/google-hacking-diggity/)
It looks like there's still a lot of useful information there - even if the tools isn't updated any more, is the information still useful?

2020-12-10 17:36 UTC, rbsec commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [MaxPatrol Security Scanner](https://www.ptsecurity.com/ww-en/products/maxpatrol/)
Commercial, so has been removed.

2020-12-11 12:13 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
>  - [BlueClosure BC Detect](https://www.blueclosure.com)
Interesting. Didn't see that to be outdated. Let's ignore that, we can remove this section.

2020-12-11 12:14 UTC, ThunderSon commented on document/6-Appendix/A-Testing_Tools_Resource.md
> +- [Google Hacking Diggity Project](https://resources.bishopfox.com/resources/tools/google-hacking-diggity/)
I saw the information to be revolving around the tool. I'd refer to other books or PDFs that explain this better instead if we were to do that. It's no longer a "tool" though, so not part of this appendix.

2020-12-11 12:21 UTC, ThunderSon commented
@kingthorin I believe the linter is taking the outdated configuration version from their branch, and not from master.

2020-12-11 12:24 UTC, kingthorin commented
Yes, the PR would need to be rebased to pickup the changes.

2020-12-11 12:34 UTC, kingthorin commented
Still has a conflict which needs to be addressed as well.

2020-12-11 12:40 UTC, ThunderSon commented
@rbsec so a couple of things:
1. rebase against master to receive the latest update on the linter (4 indents for ULs)
2. The conflict, should be fixed with the rebase.
3. Check #677 and let's discuss if we should be adding tools through this PR, or through another different one.

2020-12-11 17:52 UTC, rbsec commented
@ThunderSon I think this is now ready to merge. I'm a little uncomfortable about Wappalyzer - the default behaviour is to collect information about all the sites you're browsing to with it, which isn't really ideal for pentesting.

2020-12-12 10:55 UTC, ThunderSon approved these changes
Amazing, thanks!

2020-12-12 11:01 UTC, kingthorin commented
> @ThunderSon I think this is now ready to merge. I'm a little uncomfortable about Wappalyzer - the default behaviour is to collect information about all the sites you're browsing to with it, which isn't really ideal for pentesting.

You could mention ZAP's implementation (same patterns no collection), and add a note about tue original.
https://www.zaproxy.org/docs/desktop/addons/technology-detection/

2021-01-09 04:55 UTC, merged