Fix 567
OWASP/wstg pull request #662
Opened 2020-12-07 10:42 UTC by n17h31sm

This PR covers issue #567 

- [X] This PR handles the issue and requires no additional PRs.

**What did this PR accomplish?**

- Cut the size of the example payloads
- Include the [PayloadsAllTheThings](https://github.com/swisskyrepo/PayloadsAllTheThings) cheatsheets instead

2020-12-07 10:46 UTC, n17h31sm commented
Hmm, if I use `+` instead of `%20` it is `404` for real. I don't have a problem accessing it with the urls that Actions thinks are broken. 
* If I don't encode the whitespace the link brakes.

2020-12-07 17:46 UTC, ThunderSon commented
Safe to ignore for now, we'll review what's going on.

2020-12-08 14:57 UTC, kingthorin requested changes

2020-12-08 14:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include.md
> +Another  common example is including content from an external source:
```suggestion
Another common example is including content from an external source:
```

2020-12-08 14:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include.md
> +You can find encoding techniques an ready to be used directory traversal payloads at [PayloadsAllTheThings - Directory Traversal](https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Direc
```suggestion
You can find encoding techniques and ready to use directory traversal payloads at [PayloadsAllTheThings - Directory Traversal](https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Directory%20Traversal)
```

2020-12-08 14:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include.md
> +#### Windows specific considerations
```suggestion
#### Windows Specific Considerations
```

2020-12-08 14:57 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include.md
> +**Note:** To successfully test for this flaw, the tester needs to have knowledge of the system being tested and the location of the files being requested. There is no point requesting `/etc/passwd` f
@ThunderSon should this be:
```md
> Note: To successfully test for this flaw, the tester needs to have knowledge of the system being tested and the location of the files being requested. There is no point requesting `/etc/passwd` from an IIS web server.
```

2020-12-09 18:35 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include.md
> +**Note:** To successfully test for this flaw, the tester needs to have knowledge of the system being tested and the location of the files being requested. There is no point requesting `/etc/passwd` f
I am considering not to use `>` for notes. It's representation is coming off a bit too zoned out in the PDF. Let's keep it as is for this one, I'm reviewing this to follow on across the whole guide. Maybe have a smaller text, or change it a bit like in books.

2020-12-09 18:37 UTC, kingthorin approved these changes
Thanks

2020-12-09 18:38 UTC, merged