remove Gray-box and code-review sections from 4.1 information gathering
OWASP/wstg pull request #664
Opened 2020-12-07 11:44 UTC by RiieCco

This PR covers issue #592.

- [ ] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

I have removed the "gray box" and "code-reviews" sections from chapter 4.1 information gathering

Thank you for your contribution!

2020-12-07 12:18 UTC, kingthorin commented
Why is this content being removed?

2020-12-07 12:22 UTC, RiieCco commented
@kingthorin, i was asked by @ThunderSon to remove these parts from WSTG and see if i could fit them in SKF
I got schooled in mean time for my bad Git etiquettes so i have to fix some things and redo the PR :-p

2020-12-07 12:29 UTC, kingthorin commented
Okay, no problem. Just caught me off guard. Thanks.

2020-12-07 19:13 UTC, kingthorin commented
I think the ASD content is still good and applicable here, I just need to review the entire chapter and see how best to leave it in.

2020-12-14 10:08 UTC, ThunderSon commented
@kingthorin Should we change the sub section titles and re-include the ASD text, or what do you think?

2020-12-15 15:12 UTC, kingthorin commented
Thanks for pinging me. Here's what I'd suggest:

1. Remove the "Gray-Box Testing" L3 and the associated paragraph.
1. Keep the ASD content by: Bumping up "OWASP Attack Surface Detector" heading to be an L3, and contained "How to Use" heading to be an L4.

2021-04-03 16:17 UTC, kingthorin commented
@RiieCco are you able to tackle the latest feedback or would you like me to finish this off?

2021-04-03 16:31 UTC, RiieCco commented
@kingthorin, i think this one is better to be finished of by you i guess, i lack vision to really know for sure what needs to stay and can go. I had a rough couple of months but i have some extra time on my hands to at least finish up the "deserialization" chapter. i made a very good rough first draft on that one. I will do a PR somewhere next week for review :-)!

2021-05-15 00:05 UTC, kingthorin commented
Yes Mr. Bot, I'm on this ⚡

2021-06-05 01:09 UTC, kingthorin approved these changes

2021-06-06 03:00 UTC, ThunderSon requested changes

2021-06-06 03:00 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/01-Information_Gathering/06-Identify_Application_Entry_Points.md
> +> In this example the tester would note all the parameters as they have before, however the majority of the parameters are passed in the body of the request and not in the URL. Additionally, note tha
```suggestion
It can be noted that the parameters are sent in several locations:

1. In the querystring: `service`
2. In the Cookie header: `SESSIONID`, `CustomCookie`
3. In the request body: `user`, `pass`, `debug`, `fromtrustIP`

Having a variety of injection locations provide the attacker with chaining possibilities that could improve the chances of finding a bug in the handling code.
```

2021-06-07 11:41 UTC, ThunderSon approved these changes

2021-06-07 11:47 UTC, merged