Testing for Content Security Policy
OWASP/wstg pull request #708
Opened 2021-01-03 11:15 UTC by DotDotSlashRepo

This PR covers issue #654

- [x] This PR handles the issue and requires no additional PRs. (Unless enhancements are needed)
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Add test case for CSP
- Link test case to **4.2 Configuration and Deployment Management Testing** main page

Thank you for your contribution!

2021-02-03 15:43 UTC, kingthorin requested changes
https://github.com/OWASP/wstg/blob/master/document/README.md should also be updated.

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +Content Security Policy is a declarative allow-list policy enforced through `Content-Security-Policy` header or equivalent `<meta>` element. It allows developers to restrict the sources from which re
```suggestion
Content Security Policy is a declarative allow-list policy enforced through `Content-Security-Policy` response header or equivalent `<meta>` element. It allows developers to restrict the sources from which resources such as JavaScript, CSS, images, files etc. are loaded. CSP is an effective defense in depth technique to mitigate the risk of vulnerabilities such as Cross Site Scripting (XSS) and Clickjacking.
```

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +Content Security Policy can be implemented through one of the below methods,
```suggestion
Content Security Policy can be implemented through one of two methods:
```

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- Meta element: `<meta http-equiv="Content-Security-Policy" content="policy">`
A note should be added here that not all directives can be applied via META, including but not necessarily limited to: `frame-ancestors`, `report-uri`, or `sandbox`

```suggestion
- Meta element: `<meta http-equiv="Content-Security-Policy" content="<policy>">`
```

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- Content-Security-Policy Header: `Content-Security-Policy: policy`
```suggestion
- `Content-Security-Policy` response header: `Content-Security-Policy: <policy>`
```

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +```
I like this detail but it seems more developer focused than tester focused, I'm not sure testers need this level of background info. If they do perhaps we can just link to MDN or something?

This might be good for the cheat sheet project.

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +To test for misconfigurations in CSP policy look for below insecure configurations by examining `Content-Security-Policy` HTTP response header or CSP meta element in a proxy tool:
```suggestion
To test for misconfigurations in content security policies look for below insecure configurations by examining `Content-Security-Policy` HTTP response header or CSP meta element in a proxy tool:
```

The P in the acronym is already policy. Saying CSP Policy is like saying SSN Number (Social Security Number Number) 😉

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- `unsafe-inline` directive enables inline scripts making the applications susceptible to Cross Site Scripting attacks.
```suggestion
- `unsafe-inline` directive enables inline scripts or styles making the applications susceptible to Cross Site Scripting attacks.
```

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- `unsafe-eval` directive allows eval() to be used in the application.
```suggestion
- `unsafe-eval` directive allows `eval()` to be used in the application.
```

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- Business critical applications require to use a CSP strict policy.
```suggestion
- Resources such as scripts can be allowed to be loaded from any origin by the use wildcard (`*`) source.
- Framing can be enabled for all origins by the use of wildcard (`*`) source for `frame-ancestors` directive.
- Business critical applications should require to use a strict policy.
```

2021-02-03 15:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +Configure a strong CSP policy which reduces the attack surface of the application. Developers can verify the strength of content security policy using online tools such as [Google CSP Evaluator](http
```suggestion
Configure a strong content security policy which reduces the attack surface of the application. Developers can verify the strength of content security policy using online tools such as [Google CSP Evaluator](https://csp-evaluator.withgoogle.com/).
```

2021-02-05 18:28 UTC, DotDotSlashRepo commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +```
Makes sense. I not very sure, how to cut it in a nice way though. 

But I think we can still callout strict policy, as it should be the ideal implementation of CSP.

2021-02-05 18:28 UTC, DotDotSlashRepo commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +To test for misconfigurations in CSP policy look for below insecure configurations by examining `Content-Security-Policy` HTTP response header or CSP meta element in a proxy tool:
:)

2021-02-05 18:42 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +```
Add the strict part to the remediation section?

2021-02-05 19:16 UTC, DotDotSlashRepo commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +```
Yes. That's good. I will work on that

2021-02-05 23:50 UTC, ThunderSon requested changes
I'd say this is missing some more content:
- Attacks against the report-to endpoint
- Bypasses to CSP like callbacks, uploaded files to allowed websites, policy injection (can link to header injection if you don't wanna drill into it), etc.

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +Content Security Policy is a declarative allow-list policy enforced through `Content-Security-Policy` response header or equivalent `<meta>` element. It allows developers to restrict the sources from
```suggestion
Content Security Policy (CSP) is a declarative allow-list policy enforced through `Content-Security-Policy` response header or equivalent `<meta>` element. It allows developers to restrict the sources from which resources such as JavaScript, CSS, images, files etc. are loaded. CSP is an effective defense in depth technique to mitigate the risk of vulnerabilities such as Cross Site Scripting (XSS) and Clickjacking.
```

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +Content Security Policy can be implemented through one of two methods:
```suggestion
CSP can be implemented through one of two methods:
```

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- `Content-Security-Policy` response header: `Content-Security-Policy: <policy>`
```suggestion
- CSP response header: `Content-Security-Policy: <policy>`
```

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +Content Security Policy supports directives which allow granular control to the flow of policies.
This whole part can be replaced with the CSP documentation, or the CSP cheat sheet, whichever you see as fitting to be added in the remediation, and not in the summary of the attack.
I believe this was discussed in another comment, just adding my 2 cents as well.

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +Review the Content-Security-Policy header or meta element to identify misconfigurations.
```suggestion
- Review the Content-Security-Policy header or meta element to identify misconfigurations.
```

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +To test for misconfigurations in content security policies look for below insecure configurations by examining `Content-Security-Policy` HTTP response header or CSP meta element in a proxy tool:
```suggestion
To test for misconfigurations in CSPs look for below insecure configurations by examining `Content-Security-Policy` HTTP response header or CSP `meta` element in a proxy tool:
```

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- `unsafe-inline` directive enables inline scripts or styles making the applications susceptible to Cross Site Scripting attacks.
```suggestion
- `unsafe-inline` directive enables inline scripts or styles making the applications susceptible to XSS attacks.
```

2021-02-05 23:50 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +
There is the bypass that occurs when URL whitelisting is used.
Let's say I whitelist a CDN to load my JS libraries, it could have a `jsonp` endpoint that can be used to bypass the CSP rules.

2021-02-10 09:51 UTC, phish commented
I thing we should add a `related to` section and say that the correct usage of a CSP can prevent most injection attacks that are listed in Chapter 4.11 Client-side Testing

2021-03-20 16:18 UTC, ThunderSon commented
Hello @DotDotSlashRepo ! Just checking if everything is good.
No worries if life has taken the best of your time.

2021-04-03 16:18 UTC, kingthorin commented
@DotDotSlashRepo Are you able to address the latest feedback?

2021-05-25 09:38 UTC, victoriadrake commented
I interrupted the bot. @DotDotSlashRepo  let us know if you want to continue this. Until then it’s up for grabs!

2021-05-25 11:05 UTC, kingthorin commented
I'll try to work on finishing this up.

2021-05-25 23:25 UTC, ThunderSon commented
Had a look at this. I will add more content to make it a more complete test before publishing this.

2021-05-26 00:28 UTC, kingthorin commented
Sounds great! It is pretty light but I didn’t have time to dig into examples.

2021-05-28 13:44 UTC, ThunderSon approved these changes

2021-05-28 13:44 UTC, merged