Add certificates as an information gathering technique to find vhosts
OWASP/wstg pull request #709
Opened 2021-01-09 10:09 UTC by rbsec

Looking at the CN and SAN on certificates is a common method to find vhosts when you all you is an IP address, so it's worth mentioning here.

2021-01-10 21:58 UTC, ThunderSon requested changes
Why was Bing and whois removed? Whois link could be updated as that one is dead as it seems, but I feel there's another reasoning

2021-01-10 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/01-Information_Gathering/04-Enumerate_Applications_on_Webserver.md
> +If the server accepts connections over HTTPS, then the Command Name (CN) and Subject Alternate Name (SAN) on the certificate may contain one or most hostnames. However, if the webserver does not have
Typo, I believe this should Common instead of Command

2021-01-10 23:20 UTC, rbsec commented on document/4-Web_Application_Security_Testing/01-Information_Gathering/04-Enumerate_Applications_on_Webserver.md
> +If the server accepts connections over HTTPS, then the Command Name (CN) and Subject Alternate Name (SAN) on the certificate may contain one or most hostnames. However, if the webserver does not have
Good spot - fixed.

2021-01-10 23:24 UTC, rbsec commented
Bing `ip:` was removed because Microsoft broke this functionality a while back (I think it was at least a year ago) - so it doesn't seem to reliably return any information any most whenever I've tried to use it. Happy to revert if you've had any success with this.

That whois site doesn't exist, so the link had to be removed to pass the linting check, otherwise this couldn't be merged.

2021-01-11 16:24 UTC, kingthorin commented
I think @ThunderSon's point was that there must be another functional whois service out there.

Also I just did some quick testing with Bing IP search. `https://www.bing.com/search?q=ip%3A104.16.149.244` seems to work fine, however if you visit bing.com and manually enter `ip:104.16.149.244` and search it adds a bunch of other params to the request and returns a blank page 👎 (That's fbi.gov BTW). For my two cents, given that the natural flow/use model of the site doesn't work I'm okay with dropping it. (Or it could be replaced with something else like: https://api.hackertarget.com/reverseiplookup/?q=104.16.149.244)

2021-01-11 19:00 UTC, rbsec commented
From the context I assume that whois site also had some kind of reverse IP lookup (otherwise it wouldn't really fit). Happy to add in HackerTarget or any other that you think are worth putting here.

You could often get the `ip:` data back from the Bing API - but sometimes it just failed to return it. Interesting that the direct URL search works. Doesn't exactly inspire confidence though...

@ThunderSon  did you have a specific service in mind to add?

2021-02-06 01:37 UTC, ThunderSon commented
Yep, the new link is the following `https://www.whois.com/whois/`.
Otherwise I am fine with taking bing out

2021-02-06 08:35 UTC, rbsec commented
@ThunderSon does that site do reverse IP lookup? When I tried putting a few IPs in it, it just shows the WHOIS for that IP, not a list of domains that point to it.

2021-02-06 12:24 UTC, ThunderSon commented
Yes, that was just as a whois replacement. For the reverse lookups, the only online service I use is this one: https://mxtoolbox.com/ReverseLookup.aspx

2021-02-06 13:39 UTC, rbsec commented
Is general WHOIS that relevant for this document? The link was removed from the "Reverse-IP Services" section, and the only reference to WHOIS is an (incorrectly captioned?) screenshot showing the reverse IP lookup of the OWASP domain.

2021-02-06 14:25 UTC, ThunderSon commented
Apologies, I was a bit out of context.
It's safe to ignore them then. You can even remove that image as it's old as hell.

2021-02-06 15:25 UTC, ThunderSon approved these changes

2021-02-06 15:32 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/01-Information_Gathering/04-Enumerate_Applications_on_Webserver.md
> +If the server accepts connections over HTTPS, then the Common Name (CN) and Subject Alternate Name (SAN) on the certificate may contain one or most hostnames. However, if the webserver does not have
```suggestion
If the server accepts connections over HTTPS, then the Common Name (CN) and Subject Alternate Name (SAN) on the certificate may contain one or more hostnames. However, if the webserver does not have a trusted certificate, or wildcards are in use, this may not return any valid information.
```

2021-03-15 00:53 UTC, kingthorin approved these changes

2021-03-15 00:53 UTC, merged