Added Test for XXE
OWASP/wstg pull request #710
Opened 2021-01-12 17:55 UTC by DotDotSlashRepo

This PR covers issue #8 

- [x] This PR handles the issue and requires no additional PRs. Refer TODOs
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Added test case for XXE

#### TODO
1. Edit top level page to link to test case.
2. This test case has overlap with WSTG-INPV-07 , XML injection. WSTG-INPV-07 is to be modified to eliminate duplication.

Thank you for your contribution!

2021-02-03 18:02 UTC, kingthorin requested changes

2021-02-03 18:02 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_XXE_Injection.md
> +Web application filters can be configured to detect common XXE attack payloads in HTTP request and reject such requests. Weak or poorly configured filters can be evaded using below techniques:
```suggestion
Web application filters can be configured to detect common XXE attack payloads in HTTP requests and reject such requests. Weak or poorly configured filters can be evaded using techniques outlined below:
```

2021-02-03 18:02 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_XXE_Injection.md
> +- For PHP applications, PHP filters such as `convert.base64-encode` can be used to evade filters , especially if the filter logic is to identify and filter URIs starting with `file:///`.
```suggestion
- Some XML implementations support the `PUBLIC` keyword which is similar to `SYSTEM` and can be used to create external entities.
- UTF-8 and UTF-16 encodings can be used to encode the XXE payloads to get around web filters.
- For PHP applications, PHP filters such as `convert.base64-encode` can be used to evade filters, especially if the filter logic is to identify and filter URIs starting with `file:///`.
```

2021-02-03 18:02 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_XXE_Injection.md
> +The following Java API may be vulnerable to XXE if they are not configured properly.
```suggestion
The following Java APIs may be vulnerable to XXE if they are not configured properly.
```

2021-02-05 18:34 UTC, DotDotSlashRepo commented
TODO

Edit top level page to link to test case.
This test case has overlap with WSTG-INPV-07 , XML injection. WSTG-INPV-07 is to be modified to eliminate duplication.
Need to re-order test case, XXE makes more sense to be after XML injection

@kingthorin : Can I go ahead with these ?

2021-02-05 18:46 UTC, kingthorin commented
I'm good with ypu addressing duplicate content. 
However re-ordering things should wait until we are headed to 5.x. Currently we are still planning further 4.x releases, so maybe just create an issue and we can assign it to the 5.x milestone.

2021-12-04 03:44 UTC, kingthorin commented
@DotDotSlashRepo do you intend to finish this?

2022-03-11 22:58 UTC, kingthorin commented
@DotDotSlashRepo do you intend to finish this?

2022-03-12 11:13 UTC, rejahrehim commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_XXE_Injection.md
> +- libxml2: xmlCtxtReadMemory,xmlCtxtUseOptions,xmlParseInNodeContext,xmlReadDoc,xmlReadFd,xmlReadFile ,xmlReadIO,xmlReadMemory, xmlCtxtReadDoc ,xmlCtxtReadFd,xmlCtxtReadFile,xmlCtxtReadIO
- libxml2: `xmlCtxtReadMemory`, `xmlCtxtUseOptions`, `xmlParseInNodeContext`, `xmlReadDoc`, `xmlReadFd`, `xmlReadFile`, `xmlReadIO`, `xmlReadMemory`, `xmlCtxtReadDoc`, `xmlCtxtReadFd`, `xmlCtxtReadFile`, `xmlCtxtReadIO`

2022-03-12 11:13 UTC, rejahrehim commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_XXE_Injection.md
> +- libxerces-c: XercesDOMParser, SAXParser, SAX2XMLReader
- libxerces-c: `XercesDOMParser`, `SAXParser`, `SAX2XMLReader`

2022-04-19 22:11 UTC, ThunderSon commented
@RiieCco might you have some time to give this a look?

@kingthorin what is still needed for this? I'll be giving this a look as well.

2022-04-19 22:15 UTC, kingthorin commented
Comments from Feb 5th and Rejah’s more recent comments.

2022-04-19 22:47 UTC, ThunderSon commented
Alright. Let's re-review that comment, as that seems to be creating an issue, and is not a blocker right now.
Let's try to recall the exact concern and then move this.
This is a good addition, I'll try to review this ASAP.

2022-04-19 23:20 UTC, kingthorin commented
I was this discussion:

> TODO
> Edit top level page to link to test case.
> This test case has overlap with WSTG-INPV-07 , XML injection. WSTG-INPV-07 is to be modified to eliminate duplication.
> Need to re-order test case, XXE makes more sense to be after XML injection

---

> I'm good with you addressing duplicate content.
> However re-ordering things should wait until we are headed to 5.x. Currently we are still planning further 4.x releases, so maybe just create an issue and we can assign it to the 5.0 milestone.

2023-01-04 15:10 UTC, closed without merging