merge sections 4.7.11.1 & 4.7.11.2
OWASP/wstg pull request #712
Opened 2021-01-14 09:00 UTC by Magii204

This PR covers issue #512.

- [ ] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

- local file inclusion is combined with remote file inclusion
-added the topic name testing for file inclusion

Thank you for your contribution!

2021-02-03 23:31 UTC, kingthorin requested changes
The main ToC and section ToC need to be updated as well. The removed content should implement a placeholder like: https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/01-Information_Gathering/09-Fingerprint_Web_Application.md

2021-02-03 23:31 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion.md
> +### Summary
This should follow the document template. 
```md
## Summary
## Test Objectives
### How To Test
#### Testing for Local File Inclusion
...
#### Testing for Remote File Inclusion
...
### Related Test Cases
### Remediation
### Tools
### References
```

2021-02-03 23:32 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion.md
> +### Summary
https://github.com/OWASP/wstg/blob/master/template/999-Foo_Testing/1-Testing_for_a_Cat_in_a_Box.md

2021-02-06 00:11 UTC, ThunderSon commented
Hi @Magii204 
I believe you misunderstood what Rick instructed.
The headers should follow in order, just like in any other document.
You can't have a `###` without a `##` prior to it.
An example:
```markdown
# Title
## Subtitle
### Subsection
```
This doesn't work:
```markdown
# Title
### Subsection
## Subtitle
```

We are not simply looking to copy the content from the test files into this one, we need them to properly merge together in their content and what they provide the reader with.

2021-02-06 15:10 UTC, kingthorin commented
The entire content needs to follow the document template. It’s not as simple as cramming two pages together. There should be a single summary, etc and local vs remote should be appropriate sub-sections.

2021-02-06 15:13 UTC, kingthorin requested changes
The entire content needs to follow the document template. It’s not as simple as cramming two pages together. There should be a single summary, etc and local vs remote should be appropriate sub-sections.

2021-02-06 16:25 UTC, Magii204 commented
Yes I will understood what you say.

2021-07-09 01:11 UTC, kingthorin commented
Rebased current and fixed up.

2021-07-09 01:11 UTC, kingthorin approved these changes

2021-08-07 12:11 UTC, victoriadrake requested changes
Edits for clarity. Looks good otherwise!

2021-08-07 12:11 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion.md
> +On PHP 7.2.0, the `zip://` wrapper was introduced to manipulate `zip` compressed files. This wrapper expects the following parameter structure: `zip:///filename_path#internal_filename` where `filenam
```suggestion
In PHP 7.2.0, the `zip://` wrapper was introduced to manipulate `zip` compressed files. This wrapper expects the following parameter structure: `zip:///filename_path#internal_filename`. The `filename_path` is the path to the malicious zip archive and `internal_filename` is the path of the malicious file placed inside the processed ZIP file. During the exploitation, it's common that the `#` would be encoded with its URL encoded value `%23`.
```

2021-08-07 12:11 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion.md
> +In order to test the LFI using this wrapper, the code to be executed should be Base64 encoded, for example: `<?php phpinfo(); ?>` would be encoded as: `PD9waHAgcGhwaW5mbygpOyA/Pg==` so the payload wo
```suggestion
In order to test for LFI using this wrapper, the code to be executed should be Base64 encoded. For example, `<?php phpinfo(); ?>` would be encoded as: `PD9waHAgcGhwaW5mbygpOyA/Pg==` and the payload would be represented as: `data://text/plain;base64,PD9waHAgcGhwaW5mbygpOyA/Pg==`.
```

2021-08-07 12:11 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion.md
> +This wrapper, which is not enabled by default, provides access to processes `stdio`, `stdout`, and `stderr`. Expecting to be used as `expect://command` the server would execute the provided command o
```suggestion
This wrapper, which is not enabled by default, provides access to processes `stdio`, `stdout`, and `stderr`. Given in the format `expect://command`, the server would execute the provided command using `BASH` and return the result.
```

2021-08-07 12:11 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion.md
> +Since RFI occurs when URLs passed to "include" statements are not properly sanitized, in a black-box testing approach, we should look for scripts which take filenames as parameters. Consider the foll
```suggestion
Since RFI occurs when URLs passed to `include` statements are not properly sanitized, in a black-box testing approach, we should look for scripts that take filenames as parameters. Consider the following PHP example:
```

2021-08-07 12:11 UTC, victoriadrake commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion.md
> +The most effective solution to eliminate file inclusion vulnerabilities is to avoid passing user-submitted input to any filesystem/framework API. If this is not possible the application can maintain
```suggestion
The most effective solution to eliminate file inclusion vulnerabilities is to avoid passing user-submitted input to any filesystem/framework API. If this is not possible, the application can maintain an allow list of files that may be included by the page, and then use an identifier (for example, the index number) to access the selected file. Any request containing an invalid identifier should be rejected so that there is no opportunity for malicious users to manipulate the path.
```

2021-08-07 12:18 UTC, kingthorin commented
Thanks @victoriadrake I’ll tackle those later today.

2021-08-08 13:55 UTC, victoriadrake approved these changes

2021-08-08 15:12 UTC, merged