ADD Self DOM Based Cross Site Scripting Testing #269
OWASP/wstg pull request #713
Opened 2021-01-16 15:49 UTC by Magii204

This PR covers issue #269.

- [ ] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

- Added test case for DOM Based XSS

TODO
1. Edit top level page to link to test case.

Thank you for your contribution!

2021-01-22 11:33 UTC, kingthorin commented
?

2021-01-23 03:53 UTC, Magii204 commented
I had solved ADD Self DOM Based Cross Site Scripting Testing#269 #713 
please review it and ask if any query ?

2021-01-24 22:03 UTC, kingthorin commented
Please remove the unrelated commits.

2021-01-28 11:33 UTC, kingthorin commented
Are you having a problem with git/Github? Please just ask if you need help.

2021-01-28 17:44 UTC, Magii204 commented
I can reset the commit fb2e462 but all commit are restored please help me how to remove unwanted commit.

2021-01-28 17:58 UTC, kingthorin commented
You can do an interactive rebase and pick or skip. https://git-scm.com/docs/git-rebase

If you're nervous about that just let me know and I can do it then describe how you pull down the updated version of the feature branch. Just let me know which commit IDs are relevant to this pull request.

2021-01-29 12:46 UTC, Magii204 commented
thank you so much @kingthorin

2021-02-03 23:40 UTC, kingthorin requested changes
Main ToC and section ToC need updates.
The Checklist (MD at least) should be updated, as well as the tests list in the reporting section.

2021-02-03 23:40 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Self_DOM_Based_Cross_Site_Scripting.md
> +A Self DOM-Based Cross-Site Scripting is a specific attack and needs prior knowledge of DOM-Based cross site scripting and successful social engineering. The term 'self' is a reference here to the fa
```suggestion
Self DOM-Based Cross-Site Scripting is a specific attack and needs prior knowledge of DOM-Based cross site scripting and successful social engineering. The term 'self' is a reference here to the fact, that the user needs to inject the payload into the input field, and thus execute the vulnerability themselves. The vulnerability is further specific, as the website's Content Security Policy (CSP) can block the execution of scripts.
```

2021-02-03 23:40 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Self_DOM_Based_Cross_Site_Scripting.md
> +We will use the term sink in the following. In computing, a sink, event sink or data sink is a class or function designed to receive incoming events from another object or function. Thus in order to
```suggestion
This scenario will use the term "sink" in the following manner: In computing, a sink, event sink or data sink is a class or function designed to receive input or events from another object or function. Thus in order to find possible vulnerabilities we first need to identify the sinks of the application we want to test.
```

2021-02-03 23:40 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Self_DOM_Based_Cross_Site_Scripting.md
> +In the following the execution of the code will be explained and the implications for the security of the code are shown.
```suggestion
Abuse of this functionality can be described as follows:
```

2021-02-03 23:40 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Self_DOM_Based_Cross_Site_Scripting.md
> + This type of code is typically used to remove HTML tags from a string, as the `textContent` property contains the String which was rendered by the browser when the HTML was parsed. This particular m
```suggestion
 This type of code is typically used to remove HTML tags from a string, as the `textContent` property contains the string which was rendered by the browser when the HTML was parsed. This particular method is inherently insecure because it uses `innerHTML`. When user input is provided to the `innerHTML` property, it is parsed by the web browser and can therefore lead to the execution of malicious JavaScript.
```

2021-02-04 12:04 UTC, Magii204 commented
I was done work by @kingthorin recommendation.

2021-04-03 16:22 UTC, kingthorin commented
@Magii204 are you able to address the latest feedback or do you need someone else to finish this up?

2021-07-30 18:02 UTC, kingthorin approved these changes

2021-07-30 18:03 UTC, merged