Merge ATHN-01 into CRYP-03
OWASP/wstg pull request #714
Opened 2021-01-17 06:48 UTC by Mindslave

This PR covers issue #563.

- [x ] This PR handles the issue and requires no additional PRs.
- [x ] You have validated the need for this change.

**What did this PR accomplish?**

- This PR removed duplicated content between ATHN-01 and CRYP-03 by merging them. Resulting in ATHN-01 being removed and CRYP-03 being extended. Most notably the 'Remediation' section and 'Example 4: Password Reset, Change Password or Other Account Manipulation over HTTP` from ATHN-01 are now part of CRYP-03.

2021-02-03 23:43 UTC, kingthorin approved these changes
LGTM, thanks

2021-02-06 00:30 UTC, ThunderSon requested changes
Can we possibly shorten the remediation? I believe it's a lot of chit chat and a lot of focus on incentives to implement it. It's not really our focus, we can maybe link to other references with just a line or two, or a small bullet list on major things to do.

2021-02-07 14:53 UTC, Mindslave commented
Yes I agree, a short and to the point Remediation section is better, I have cut it down to a single sentence and added a 'References' section.

2021-02-07 16:40 UTC, kingthorin approved these changes

2021-02-15 11:31 UTC, rbsec commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
>  - [Identity Finder](https://download.cnet.com/Identity-Finder-Free-Edition/3000-2144_4-10906766.html)
Given that this was last updated in 2013, and lists Windows 7 as the most recent supported operating system, perhaps time for it to get removed?

2021-02-15 12:43 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
>  - [Identity Finder](https://download.cnet.com/Identity-Finder-Free-Edition/3000-2144_4-10906766.html)
I agree

2021-02-15 20:31 UTC, Mindslave commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
>  - [Identity Finder](https://download.cnet.com/Identity-Finder-Free-Edition/3000-2144_4-10906766.html)
I agree as well, I was not aware that it's not up to date. I think it would be fine to leave a link to it in the references section and just remove it from the remediation, right?

2021-02-15 20:39 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
>  - [Identity Finder](https://download.cnet.com/Identity-Finder-Free-Edition/3000-2144_4-10906766.html)
I think it should just be removed. Ex drop line 137

2021-03-20 16:27 UTC, ThunderSon approved these changes
Thank you!
@kingthorin poking again for a quick look and feel free to merge.

2021-03-20 16:53 UTC, merged