Create naming schema section about CPE, SWID and PURL
OWASP/wstg pull request #720
Opened 2021-01-28 00:24 UTC by jespunya

This PR covers issue #360.

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Move the previous 5-Reporting/README.md to a new subsection under the 5-Reporting/0-Reporting_Structure/ folder.
- Create a new subsection of 5-Reporting at the folder document/5-Reporting/01-Naming/ with tackle naming schema with the introduction of CPE, SWID and PURL.
 
Thank you for your contribution!

2021-01-28 00:32 UTC, kingthorin commented
Headings should use title caps, and the section and primary index pages will require updates as well. These shouldn’t need individual directories, they should be positioned/named similar to other sections of the guide.

Was the original content just relocated or was it rewritten?

2021-01-28 00:39 UTC, jespunya commented
@kingthorin the original one was just moved.

2021-01-28 01:00 UTC, kingthorin commented
I believe the linter workflow is failing to comment due to backticks in the linting results. I'll look into fixing that separately.

2021-01-28 01:04 UTC, kingthorin commented
FYI if you're using VSC or Codespaces you can use the linter locally: https://github.com/OWASP/wstg/blob/master/CONTRIBUTING.md#how-to-set-up-your-contributor-environment

2021-01-28 01:04 UTC, jespunya commented
@kingthorin I have fixed several lint errors. Others I don't have a clear idea about how to fix them. 

On the other hand, I have fixed the files/folder structure as you mentioned & I have modified the original documentation (actually on the file 0-Reporting_Structure.md) to fix the mistakes detected by github actions (commit 27e420c).

2021-01-28 01:19 UTC, jespunya commented
@kingthorin Thanks for the VSC extension recommendation. All the lint errors had been fixed.

2021-01-28 03:56 UTC, kingthorin requested changes
Thanks for tackling this.

https://github.com/OWASP/wstg/blob/master/document/README.md should also be updated.

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +# Vulnerability naming schemes
```suggestion
# Vulnerability Naming Schemes
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +With a constantly growing number of IT assets to administrate, the security practitioners had required new and more powerful tools to perform automated and large scale analysis. Thanks to those softw
```suggestion
With a constantly growing number of IT assets to administer, security practitioners require new and more powerful tools to perform automated and large scale analysis. Thanks to software attention can be focused on the more creative and intellectually challenging problems. Unfortunately, having vulnerability assessment tools, antivirus software, and intrusion detection systems communicate its not an easy job. It has resulted in several technical complications, requiring a standardized way to identify each software flaw, vulnerability, or configuration issues identified. The lack of this interoperability capabilities can cause inconsistencies during the security assessment, confusing reporting, and extra correlation efforts among other problems that will produce an important waste of resources and time.
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +A naming scheme is a systematic methodology used to identify each one of those vulnerabilities in order to facilitate clear identification and information shearing. This goal is achieved by the defin
```suggestion
A naming scheme is a systematic methodology used to identify each one of those vulnerabilities in order to facilitate clear identification and information sharing. This goal is achieved by the definition of a unique, structured, and software-efficient name for each vulnerability. There are multiple schemes used to facilitate this effort, the most common are:
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +Software Identification Tag (`SWID`) is an International Organization for Standardization's standard defined by the ISO/IEC 19770-2:2015. It is used primarily to identify installed software and is th
```suggestion
Software Identification Tag (`SWID`) is an International Organization for Standardization's standard defined by in ISO/IEC 19770-2:2015. It is used primarily to identify installed software and is the preferred format of the NVD in front of `CPE`.
```


> preferred format of the NVD 

"...it is NIST's perferred format for the National Vulnerability Database (NVD) over the previous standard `CPE`." ? Or something like that? (So that NVD is spelled out as it's used a few times here, and that it's clear NIST is the authority which maintains it. :man_shrugging: )

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +Each `SWID` tag is represented as a standardized XML format. A `SWID` tag is composed for three groups of elements. The first block composed by 7 predefined elements required to be considered a valid
```suggestion
Each `SWID` tag is represented as a standardized XML format. A `SWID` tag is composed for three groups of elements. The first block composed by 7 predefined elements required to be considered a valid tag. Followed by an optional block which provides a set of 30 possible predefined elements that the tag creator can use to provide reliable and detailed information. Finally, the `Extended` group of elements provides the opportunity for the tag creator to define any non-predefined elements required to accurately define the described the asset. The high level of granularity provided by `SWID`, not only provides the capability to describe a given product of software, but also it's specific status on the software lifecycle.
```

I haven't looked this up so please make sure the edits maintain the accuracy of the description.

> define the described the asset

Would "software", "product", or something else be a better fit than "asset"?

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +- Red Hat Enterprise Linux version 8 for x86-64 architecutre:
```suggestion
- Red Hat Enterprise Linux version 8 for x86-64 architecture:
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +The Common Platform Enumperation scheme (CPE) is a structured naming scheme for information technology systems, software, and packages maintained by `NVD`. Commonly used in conjunction with the Commo
```suggestion
The Common Platform Enumeration scheme (`CPE`) is a structured naming scheme for information technology systems, software, and packages maintained by `NVD`. Commonly used in conjunction with the Common Vulnerabilities and Exposures identification codes (e.g. `CVE‑2017‑0147`). Despite being considered a deprecated scheme superseded by `SWID`, `CPE` is still widely used by several security solutions.
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +- _LANGTAG_ = cf. [RFC5646]
Do you think it might make more sense to have this as a code block with triple backticks?

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +Package URL standardizes how software package metadata is represented so that packages can universally be located regardless of what vendor, project, or ecosystem the packages belongs.
```suggestion
Package URL standardizes how software package metadata is represented so that packages can be universally located regardless of what vendor, project, or ecosystem the packages belongs.
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +A purl is a valid `RFC3986` ASCII string defnid URL composed seven elements. Each of them is separated by a defined character in order to make it easily manipulated by software.
Should "PURL" generally appear in uppercase? Is there a standard we should adhere to?

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +- _subpath_: extra subpath within a package, relative to the package root. (Optional).
I don't think this list needs to be double spaced. Other's don't seem to be.

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +The defintion for each components is:
```suggestion
The definition for each component is:
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +### Known implementations
```suggestion
### Known Implementations
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +- _JS_: <https://github.com/package-url/packageurl-js>
```suggestion
- _Golang_: <https://github.com/package-url/packageurl-go>
- _.NET_: <https://github.com/package-url/packageurl-dotnet>
- [packageurl-java](https://github.com/package-url/packageurl-java], [package-url-java](https://github.com/sonatype/package-url-java)
- [Python](https://github.com/package-url/packageurl-python)
- [Rust](https://github.com/package-url/packageurl-rs)
- [JavaScript](https://github.com/package-url/packageurl-js)
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +## Recommendation usages
```suggestion
## Recommendation Uses
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +_Note:_ Due to the deprecated status of `CPE`, it's recomended that the new projects implement `SWID` when they need to decide between both methods. Even though, `CPE` is known to be a widely used na
```suggestion
> Note: Due to the deprecated status of `CPE`, industry recommended seems to be that the new projects implement `SWID` when they need to decide between the two methods. Even though `CPE` is known to be a widely used naming schema within current active projects and solutions.
```

> between the two methods

Would "standards" or "schemes" be better than "methods"?

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +## Additional information
```suggestion
## References
```

To be consistent with the [template](https://github.com/OWASP/wstg/blob/master/template/999-Foo_Testing/2-Template_Explanation.md#references)

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +- _JS_: <https://github.com/package-url/packageurl-js>
Maybe move this to the references section?

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +- [NISTIR 8060 - Guidelines for the Creation of Interoperable Software Identification (SWID) Tags](https://nvlpubs.nist.gov/nistpubs/ir/2016/NIST.IR.8060.pdf)
```suggestion
- [NISTIR 8060 - Guidelines for the Creation of Interoperable Software Identification (SWID) Tags (pdf)](https://nvlpubs.nist.gov/nistpubs/ir/2016/NIST.IR.8060.pdf)
```

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/README.md
> +5.2 [Vulnerability naming schemes](1-Naming_Schemes.md)
```suggestion
5.2 [Naming Schemes](1-Naming_Schemes.md)
```

The link text needs to be consistent with the file name. (The file name should be `2-*` I believe)

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/README.md
> +5.1 [Reporting Structure](0-Reporting_Structure.md)
```suggestion
5.1 [Reporting Structure](0-Reporting_Structure.md)
```

The filename should be `1-*` I believe.

2021-01-28 03:56 UTC, kingthorin commented on document/5-Reporting/0-Reporting_Structure.md
> +# Reporting
I haven't really reviewed this content as I expect it to be unchanged. I'll diff it at some point before merge.

2021-04-03 16:25 UTC, kingthorin commented
@jespunya are you able to address the latest feedback or do you need someone else to finish this?

2021-04-10 10:54 UTC, jespunya commented on document/5-Reporting/README.md
> +5.2 [Vulnerability naming schemes](1-Naming_Schemes.md)
I think not, other sections like for example: `3-The_OWASP_Testing_Framework` starts from `0-*` too. It's subsections are: `3-The_OWASP_Testing_Framework/0-The_Web_Security_Testing_Framework.md` & `3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md`.

2021-04-10 10:54 UTC, jespunya commented on document/5-Reporting/README.md
> +5.1 [Reporting Structure](0-Reporting_Structure.md)
I think not, other sections like for example: `3-The_OWASP_Testing_Framework` starts from `0-*` too. It's subsections are: `3-The_OWASP_Testing_Framework/0-The_Web_Security_Testing_Framework.md` & `3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md`.

2021-04-10 14:32 UTC, jespunya commented on document/5-Reporting/1-Naming_Schemes.md
> +Each `SWID` tag is represented as a standardized XML format. A `SWID` tag is composed for three groups of elements. The first block composed by 7 predefined elements required to be considered a valid
I used the word "asset" to avoid the repetition of the "software" too many times, but you are right that "software" is more accurate and should be use on this case.

2021-04-10 14:35 UTC, jespunya commented on document/5-Reporting/1-Naming_Schemes.md
> +Software Identification Tag (`SWID`) is an International Organization for Standardization's standard defined by the ISO/IEC 19770-2:2015. It is used primarily to identify installed software and is th
I have pushed a new text to replace this sentence to explain the relation between `swid` and `cpe`. I hope this new text will clarify your questions. If it is so, I would flag this as resolved.

2021-04-10 14:41 UTC, jespunya commented on document/5-Reporting/1-Naming_Schemes.md
> +Each `SWID` tag is represented as a standardized XML format. A `SWID` tag is composed for three groups of elements. The first block composed by 7 predefined elements required to be considered a valid
The corrections from your suggested change had been added on the commit `817fbcdcdcafa17d8ff491352efb7e4c77ea725e`. I flag this conversation as resolved.

2021-04-10 15:40 UTC, jespunya commented on document/5-Reporting/0-Reporting_Structure.md
> +# Reporting
It was not correct since was not updated with the latest changes done on master, I have just updated it on commit `227959927882d4e349d1544c509727d0861b9675` .

2021-04-10 15:52 UTC, jespunya commented
> **Following links are broken:**
> FILE:document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
> [heavy_multiplication_x] https://owasp.org/www-community/attacks/Man-in-the-middle_attack → Status: 404

I have created the issue: https://github.com/OWASP/wstg/issues/736 where I will fix it as an independent PR.

2021-04-10 16:21 UTC, jespunya commented
> > **Following links are broken:**
> > FILE:document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
> > [heavy_multiplication_x] https://owasp.org/www-community/attacks/Man-in-the-middle_attack → Status: 404
> 
> I have created the issue: #736 where I will fix it as an independent PR.

2021-04-10 16:29 UTC, kingthorin commented on document/5-Reporting/README.md
> +5.2 [Vulnerability naming schemes](1-Naming_Schemes.md)
The link text absolutely need to align with the file name, otherwise links in the generated PDF won’t work

2021-04-10 16:30 UTC, kingthorin commented on document/5-Reporting/README.md
> +5.1 [Reporting Structure](0-Reporting_Structure.md)
As with section 3, the readme should become a section ToC. The current readme content should become the 0th document in the section.

2021-04-10 22:53 UTC, kingthorin commented
I've rebased this so that it doesn't include a bunch of unrelated commits and file changes. I'll do a full review in a few hours (and provide instructions on how you should update your local). [Please don't make or push any changes in the meantime.]

2021-04-11 02:17 UTC, kingthorin commented
I decided to just fix the remaining items instead of marking it up again.

Please do the following to get your local copy in-sync with these changes (assuming you're in the wstg repo directory in your computer, and that your fork is set as `origin`):
```console
git fetch origin
git reset --hard origin/master
```

2021-04-11 02:18 UTC, kingthorin approved these changes

2021-04-11 19:32 UTC, victoriadrake commented
This one should wait for v5, yeah?

2021-04-11 20:04 UTC, kingthorin commented
Hmmm it doesn’t actually impact on testing scenarios so o think we can add it now.

2021-04-11 21:30 UTC, jespunya commented
The related issue: https://github.com/OWASP/wstg/issues/360 was flaged on November to be part of the v5 as @ThunderSon proposed previously on the issue itself. Even though, for me both options would be ok.

2021-05-17 12:01 UTC, victoriadrake commented
Just waiting for v5.

2022-03-11 23:00 UTC, kingthorin commented
Does this really need to wait? (@ThunderSon)

2022-04-09 20:32 UTC, kingthorin commented
Poke @ThunderSon

2022-04-19 22:14 UTC, ThunderSon commented
Apologies on this. Are we certain on the reporting page? Is this happening because of the `master` branch? 🤔 
I believe this isn't breaking any previous versions, so it should be good.

2022-04-19 22:19 UTC, kingthorin reviewed
Once the file names are adjusted to match the proper section references the indexes will need to be tweaked

2022-04-19 22:19 UTC, kingthorin commented on document/5-Reporting/0-Reporting_Structure.md
> +# Reporting
This file should be named 1- not 0-

2022-04-19 22:19 UTC, kingthorin commented on document/5-Reporting/1-Naming_Schemes.md
> +# Vulnerability Naming Schemes
This file should be 2- not 1-

2022-04-19 22:50 UTC, ThunderSon commented
Why should they be changed? We are starting our chapters from the 0 numbering. How are you looking at this?

2022-04-19 23:18 UTC, kingthorin commented
There are only 0th items in chapters that have generic lead-ins. Ex: No 0th item: https://github.com/OWASP/wstg/tree/master/document/4-Web_Application_Security_Testing/01-Information_Gathering

Also 5.1 would never link a 0th page: `5.1 [Reporting Structure](0-Reporting_Structure.md)`

Actually I believe the only place we actually have a 0th page is in chapter 3.

2022-04-24 10:35 UTC, ThunderSon commented
I agree. Should we update chapter 3? I believe that'd break compatibility between v42 and v43 when it's released.
Can you please do the changes needed on this PR? Let's get this in :)

2022-04-30 18:45 UTC, kingthorin commented
I guess I'll have to pull this on my dev box and rebase it. Will do that shortly.

2022-04-30 22:56 UTC, kingthorin commented
@ThunderSon I believe this is ready now.

2022-05-29 04:30 UTC, kingthorin commented
@ThunderSon this one good to go?

2022-05-30 22:45 UTC, ThunderSon approved these changes
@kingthorin all yours!

2022-05-31 00:13 UTC, kingthorin commented
Thank you both!

2022-05-31 00:14 UTC, kingthorin approved these changes

2022-05-31 00:14 UTC, merged