DRAFT: Initial skeleton for a JWT testing guide.
OWASP/wstg pull request #744
Opened 2021-04-15 09:03 UTC by rbsec

Initial skeleton for a JWT testing guide, as discussed in issue #696.

I know that there's some debate about whether JWTs fall under session management. I put this in that folder because it seemed the most logical place (in reality that's what most people use them for) - very happy to move it somewhere else if there's consensus that it should be in another section. Whichever folder it ends up in will be more appropriate that the section in the "Testing APIs" document it's currently in.

This is just a skeleton for now, so key questions are:

- Do the points seem sensible?
- Is the structure sensible?
- Is there anything missing?

2021-04-16 17:07 UTC, kingthorin reviewed
Looks good over all.

Thanks for tackling this.

2021-04-16 17:07 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- [JSON Web Tokens Burp Extension](https://portswigger.net/bappstore/f923cbf91698420890354c1d8958fee6)
```suggestion
- [JSON Web Tokens Burp Extension](https://portswigger.net/bappstore/f923cbf91698420890354c1d8958fee6)
- [ZAP JWT Add-on](https://github.com/SasanLabs/owasp-zap-jwt-addon)
```

2021-04-16 17:07 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +# Testing JSON Web Tokens (JWTs)
```suggestion
# Testing JSON Web Tokens
```

We should do this clarification in the first paragraph, then linking is less convoluted.

2021-04-16 17:07 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- JWTs are cryptographically signed JSON tokens
```suggestion
- JSON Web Tokens (JWTs) are cryptographically signed JSON tokens
```

2021-04-16 17:07 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- `none` or `NoNe` algorithms may be allowed
RSA56? (That's top of head, I may have the wrong detail, but there is another weak 'standard')

2021-04-16 17:36 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- `none` or `NoNe` algorithms may be allowed
There's actually a whole ton of algorithms that you very rarely see, but most of them are related to JWE (encrypted tokens) rather than the more common JWTs.

[RFC 7518](https://www.rfc-editor.org/rfc/rfc7518.txt) has a list, and there's a slightly clearer table on the [IANA site](https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms).

I've never seen another other than RS256/HS256/ES256 used, and a full discussion of all the algorithms is probably going to get a bit complicated. Maybe something like "If the JWT is using anything other than RSxxx, HSxxx, or ESxxx then go and look into the algorithm properly" ?

2021-04-16 17:39 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- `none` or `NoNe` algorithms may be allowed
Ya a simple statement like that probably covers it

2021-05-02 09:22 UTC, rbsec commented
@ThunderSon and @kingthorin, I think this is now ready for an initial review.

2021-05-04 08:14 UTC, kousha1999 commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +There are also a wide range of [other algorithms](https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms) which may be used for encrypted tokens (JWEs), although these a
@rbsec I think there is an extra 's' at the end of paragraph.

2021-05-04 08:14 UTC, kousha1999 commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +This can be tested by modifying the signature algorithm (`alg`) in the JWT header to `none`, and resubmitting the JWT.
@rbsec @kingthorin Is it good to add an example?
also mention that signature must remove and the last '.' must remains.

2021-05-04 12:29 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +There are also a wide range of [other algorithms](https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms) which may be used for encrypted tokens (JWEs), although these a
Fixed

2021-05-04 12:29 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +This can be tested by modifying the signature algorithm (`alg`) in the JWT header to `none`, and resubmitting the JWT.
Good spot, I'd forgotten that. Fixed in 42454ca and added an example.

2021-05-04 14:42 UTC, kingthorin commented on Testing_for_APIs.md
> +The most commonly used token format is the JSON Web Token (JWT), defined in [RFC7519](https://tools.ietf.org/html/rfc7519). The [Testing JSON Web Tokens](/document/4-Web_Application_Security_Testing/
I know I owe a full review on this PR, but I just saw this and wanted to ask quickly :wink:

Is this all actually covered in the new content (or will it be?)

2021-05-04 14:48 UTC, rbsec commented on Testing_for_APIs.md
> +The most commonly used token format is the JSON Web Token (JWT), defined in [RFC7519](https://tools.ietf.org/html/rfc7519). The [Testing JSON Web Tokens](/document/4-Web_Application_Security_Testing/
Yes - the section in the API testing guide covered cracking weak HMAC keys and the `none` algorithm, both of which are included in the JWT guide.

2021-05-04 22:46 UTC, ThunderSon requested changes

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The signature is calculated using the algorithm defined in the JWT header, and then Base64 encoded and appened to the token. Modifying any part of the JWT should cause the signature to be invalid, an
```suggestion
The signature is calculated using the algorithm defined in the JWT header, and then Base64 encoded and appended to the token. Modifying any part of the JWT must cause the signature to be invalid, and the token to be rejected by the server.
```

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- If it is stored in the browser storage, it should [use the sessionStorage rather than localStorage](../11-Client-side_Testing/12-Testing_Browser_Storage.md).
I have thoughts on this, but I feel like it deserves its own issue. A lot of identity providers just use local storage when not using cookies, or basically a framework type of storage (which is something _similar_ to local storage). I'll open an issue on this because it affects more sections of the guide.

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- The JWT has a reasonable lifespan for the application.
@kingthorin should we link to the ASVS  here, or should we just keep this vague like this.

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The header of a defines the type of the token (typically `JWT`), and the algorithm used for the signature. A example decoded header is shown below:
```suggestion
The header of a token defines the type of that token (typically `JWT`), and the algorithm used for the signature. An example decoded header is shown below:
```

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +A more powerful option is to convert convert the JWT into a format that can be used by [John the Ripper](https://github.com/openwall/john) using the [jwt2john.py](https://github.com/Sjord/jwtcrack/bl
```suggestion
A more powerful option is to convert the JWT into a format that can be used by [John the Ripper](https://github.com/openwall/john) using the [jwt2john.py](https://github.com/Sjord/jwtcrack/blob/master/jwt2john.py) script. John can then be used to carry out much more advanced attacks against the key.
```

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +If the JWT is large, it may exceed the maximum size supported by John. This can be worked around by increasing the value of the `SALT_LIMBS` variable in `/src/hmacSHA256_fmt_plug.c` (or the equivalen
Is there a link for this guidance so that we are not held as an authority on this?

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The JSON Web Signature (JWS) standard allows the key used to sign the token to be embedded in the header. If the library used to validate the token supports this, and doesn't check the key against a
I felt like this should have been discussed earlier, and since it was mentioned I feel like it needs to. JWTs are almost all JWSs, and I feel like it might create some confusion at this stage for unaware readers. What do you think?

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- Use a secure and up to date library to handle JWTs.
We can add something to the lines of "be sure to validate the signature"

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The main way that an attacker would be able to obtain the public key is if the application re-uses the same key for both signing JWTs and as part of the TLS certificate. This key can be downloaded fr
This line/sentence feels a bit weird.
What do feel about the following suggestions:
1. Number the bullet points above.
2. Mention that the weird or troublesome point is point #2, as the public key must be public, unless they're misusing it (different thing .. haha). From the start of this sentence it feels like the issue is with the public key.
3. Start off by first discussing jwks and then the TLS cert re-use.

2021-05-04 22:46 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +In order to test this, modify the contents of the JWT, and then use the previously obtained public key to sign the JWT using the `HS256` algorithm. This is often difficult to perform when testing wit
not sure if the empty space was intended, but it was spot on.
```suggestion
In order to test this, modify the contents of the JWT, and then use the previously obtained public key to sign the JWT using the `HS256` algorithm. This is often difficult to perform when testing without access to the source code or implementation details, because the format of the key must be identical to the one used by the server, so issues such as empty space or CRLF encoding may result in the keys not matching.
```

2021-05-04 22:49 UTC, ThunderSon requested changes

2021-05-04 22:49 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The signature is calculated using the algorithm defined in the JWT header, and then Base64 encoded and appened to the token. Modifying any part of the JWT should cause the signature to be invalid, an
I deleted this by mistake.
```suggestion
The signature is calculated using the algorithm defined in the JWT header, and then Base64 encoded and appended to the token. Modifying any part of the JWT must cause the signature to be invalid, and the token to be rejected by the server.
```

2021-05-05 16:01 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The signature is calculated using the algorithm defined in the JWT header, and then Base64 encoded and appened to the token. Modifying any part of the JWT should cause the signature to be invalid, an
I used "should" here because it's making an assumption that the validation library is doing its job properly - which is often not the case.

2021-05-05 16:02 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +If the JWT is large, it may exceed the maximum size supported by John. This can be worked around by increasing the value of the `SALT_LIMBS` variable in `/src/hmacSHA256_fmt_plug.c` (or the equivalen
I've added a link to the [GitHub issue](https://github.com/openwall/john/issues/1904)

2021-05-05 16:07 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The main way that an attacker would be able to obtain the public key is if the application re-uses the same key for both signing JWTs and as part of the TLS certificate. This key can be downloaded fr
I've made some changes to this section in 202a12b to try and clear it up.

2021-05-05 16:08 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The JSON Web Signature (JWS) standard allows the key used to sign the token to be embedded in the header. If the library used to validate the token supports this, and doesn't check the key against a
I wonder if mentioning JWS at all here is just opening a can of worms? The whole JWE/JWS/JWT issue is somewhat confusing, and in reality almost everyone just refers to JWTs and ignores the rest of it.

I've slightly amended the wording in 202a12b and linked to the JWS RFC - do you think it needs more than that? If people want to really understand how all the different bits of the JWT spec fit together, they probably need to go and do some of their own reading.

2021-05-05 16:10 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- If it is stored in the browser storage, it should [use the sessionStorage rather than localStorage](../11-Client-side_Testing/12-Testing_Browser_Storage.md).
This came up a bit in the issue for this PR - but I don't think I really want to got into much detail here about it. In fact, it might be best to remove this recommendation entirely given some of the issues around sessionStorage..

2021-05-05 21:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +- If it is stored in the browser storage, it should [use the sessionStorage rather than localStorage](../11-Client-side_Testing/12-Testing_Browser_Storage.md).
Feel free to remove that, no hard feelings on this.

2021-05-05 21:55 UTC, ThunderSon reviewed
Looks good, happy with this version. The rest of the comments are optional.

2021-05-05 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The signature is calculated using the algorithm defined in the JWT header, and then Base64 encoded and appened to the token. Modifying any part of the JWT should cause the signature to be invalid, an
If the signature was to be checked and comes out as invalid, then it must cause it to ... Otherwise it's flat out ignored. I get what you're saying, just not the case for this paragraph as this is more on how it functions properly.

2021-05-05 22:00 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The JSON Web Signature (JWS) standard allows the key used to sign the token to be embedded in the header. If the library used to validate the token supports this, and doesn't check the key against a
Maybe having a tiny note somewhere, just so we don't get the "Why are you talking about JWTs and they are JWSs". We can link to the JOSE protocols as well in the references and call it a day as well. Let's definitely not dive anywhere into it.

2021-05-06 19:28 UTC, rbsec commented on document/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens.md
> +The JSON Web Signature (JWS) standard allows the key used to sign the token to be embedded in the header. If the library used to validate the token supports this, and doesn't check the key against a
I've updated the text to:

> The [JSON Web Signature (JWS) standard](https://tools.ietf.org/html/rfc7515) (which defines the header and signatures used by JWTs) allows the key used to sign the token to be embedded in the header.

And added a link to that RFC in the references. Do you think  it needs anything more than that?

2021-05-06 21:22 UTC, ThunderSon approved these changes
Happy with this as a first version.

2021-05-06 21:31 UTC, rbsec commented
@kingthorin and @ThunderSon - as well as the content here I assume there's also some admin stuff that'll need doing (adding to readmes, etc). Are you both happy with the filename/section/ID/etc?

2021-05-19 12:20 UTC, kingthorin commented
Yup seems good to me, @ThunderSon ?

2021-05-23 18:14 UTC, rbsec commented
@ThunderSon and @kingthorin I've added the guide into the checklists and session management readme - is there anything else that needs doing before this is ready to merge?

2021-05-24 22:43 UTC, ThunderSon commented on checklist/checklist.json
> +                ,{
@kingthorin do we have to remove this, or will the automation grab it on? @rbsec this is usually added by one of our scripts (for the future, thanks for doing it manually :) )

2021-05-24 22:44 UTC, kingthorin commented on checklist/checklist.json
> +                ,{
It should be reverted.

2021-05-24 22:53 UTC, ThunderSon commented on checklist/checklist.json
> +                ,{
If this isn't done by tomorrow night I'll take care of it and merge it in.

2021-05-25 07:40 UTC, rbsec commented on checklist/checklist.json
> +                ,{
Reverted in aed797a

2021-05-25 09:12 UTC, ThunderSon approved these changes
JWT is finally making it in :)

2021-05-25 09:13 UTC, merged