Rewrite of default password testing guide
OWASP/wstg pull request #753
Opened 2021-05-26 17:43 UTC by rbsec

As per discussion in #564, this guide had a lot of unnecessary fluff and padding.

2021-05-26 17:45 UTC, rbsec commented
That link is not broken - seems to be a bug with the link checker.

2021-06-06 03:10 UTC, ThunderSon approved these changes

2021-06-06 03:10 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
> +- Searching for "SOFTWARE default password".
Maybe just adding the brackets would help better? Just a suggestion
```suggestion
- Searching for "[SOFTWARE] default password".
```

2021-07-13 16:09 UTC, rbsec commented
@ThunderSon and @kingthorin - do there any further changes needed for this PR?

2021-07-13 17:23 UTC, kingthorin commented
Sorry this one has been waiting on my review, it's been in my GitHub inbox for weeks. I'll try to knock it off this week.

2021-07-16 01:17 UTC, kingthorin requested changes
Just a few minor typos

2021-07-16 01:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
> +- Installing the application of a virtual machine and inspecting it.
```suggestion
- Installing the application on a virtual machine and inspecting it.
```

2021-07-16 01:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
> +- The serial number of MAC address of the device.
```suggestion
- The serial number of MAC address or the device.
```

2021-07-16 01:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
> +If the username is unknown, there are various options for enumerating users, discussed in the [Testing for Account Enumeration](../03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_an
```suggestion
If the username is unknown, there are various options for enumerating users, discussed in the [Testing for Account Enumeration](../03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account.md) guide. Alternatively, try common options such as "admin", "root", or "system".
```

2021-07-16 01:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
> +- "admin", "password", "12345" or other [common default passwords](https://github.com/nixawk/fuzzdb/blob/master/bruteforce/passwds/default_devices_users%2Bpasswords.txt).
```suggestion
- "admin", "password", "12345", or other [common default passwords](https://github.com/nixawk/fuzzdb/blob/master/bruteforce/passwds/default_devices_users%2Bpasswords.txt).
```

2021-07-16 01:17 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
> +These type so of passwords are often difficult to identify from a black-box perspective, unless they can successfully be guessed or brute-forced. However, they are easy to identify when performing gr
```suggestion
These types of passwords are often difficult to identify from a black-box perspective, unless they can successfully be guessed or brute-forced. However, they are easy to identify when performing grey-box or white-box testing.
```

2021-07-16 14:09 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
> +- The serial number of MAC address of the device.
This was fixed in 5277707 - the commit above changes the wrong "of".

2021-07-16 14:09 UTC, rbsec commented
@kingthorin I've address all your comments.

2021-07-16 15:38 UTC, kingthorin approved these changes

2021-07-16 15:38 UTC, merged