Added Testing for Mass Assignment
OWASP/wstg pull request #760
Opened 2021-06-13 17:45 UTC by twicedi

This PR covers issue #748.

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Added Testing for Mass Assignment

Thank you for your contribution!

2021-06-13 18:29 UTC, kingthorin commented
I’m not sure why textlint didn’t pick it up in the most recent revision (I’ll sort that out) but neither blacklist nor whitelist (or their hyphenated or spaced variants) should be used.

2021-06-14 09:33 UTC, twicedi commented
I revised the wording of the paragraphs that contained "whitelist" and "blacklist".

2021-06-24 10:20 UTC, ThunderSon commented
Sorry for the delay from my end. I will be reviewing in the coming days :)

2021-06-28 22:24 UTC, ThunderSon reviewed
Looks good from the first run. Not approving yet because I want to give this a deeper analysis. I have some markdown modifications that I'll directly send, nothing major.

2021-07-02 10:49 UTC, rbsec reviewed
This looks good - I've made a few comments, but most of them are fairly minor things related to the style or specific wording.

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Modern web applications are very often based on frameworks. Many of these web application frameworks allow to automatically bind user input (in the form of HTTP request parameters) into internal obje
The second sentence would read better as:

Many of these web application frameworks allow automatic binding of user input (in the form of HTTP request parameters) to internal objects. This is often called autobinding.

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +However, due to the autobinding, an attacker can add the `isAdmin` parameter to the request, forcing the controller to automatically bind it to the model.
Rather than `forcing the controller to automatically bind it to the model`, perhaps `which the controller will automatically bind to the model`?

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +
These blank lines could be cut - you already have the `[...`]

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +```
It would to good to add a final sentence after this, something like:

The user is then created with the `isAdmin` property set to `true`, giving them administrative rights on the application.

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +In order to determine which part of the application is vulnerable to mass assignment, enumerate all parts of the application that accept content from the user and can potentially be mapped with a mod
Not just GET and POST, something like PUT would also be a likely option.

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +- custom JavaScript code
Capitalise the `c` at the start

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Another approach is to use wordlists in order to try to enumerate all the potential attributes. The enumeration can then be automated (e.g. via wfuzz, Burp Intruder etc.).
Are there specific lists included in these projects that would be worth linking to?

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +The impact of a mass assignment can vary depending on the context.
This seems to be repeating the previous point - I think you could remove this sentence

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +### Gray-Box Testing
Another thing to mention somewhere is comparing requests made by different user levels. If you see extra parameters being included in requests made by an administrative user, that might give you a hint to try as a low privileged/anonymous user

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Spring MVC allows to automatically bind user input into object. Identify the controllers that handle dispositive requests (e.g. find the occurences of `@RequestMapping`) then verify if controls are i
`dispositive requests` is not a phrase I've ever heard before. Is this a Spring specific thing?

2021-07-02 10:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Use build-in features, provided by frameworks, to define bindable and non-bindable fields. An approach based on allowed fields (bindable), in which only the properties that should be updated by the u
Should be "buil**t**-in", not "build-in".

2021-07-18 11:18 UTC, twicedi commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Another approach is to use wordlists in order to try to enumerate all the potential attributes. The enumeration can then be automated (e.g. via wfuzz, Burp Intruder etc.).
I have now added a link to the "common-columns.txt" list included inside sqlmap but I'll try to see if there are others.

2021-07-18 11:21 UTC, twicedi commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +### Gray-Box Testing
I have now added a new sentence under the black-box testing paragraph.

2021-07-18 11:23 UTC, twicedi commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Spring MVC allows to automatically bind user input into object. Identify the controllers that handle dispositive requests (e.g. find the occurences of `@RequestMapping`) then verify if controls are i
I have rephrased the sentence.

2021-07-18 12:46 UTC, rbsec commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +### Gray-Box Testing
Looks good.

2021-07-18 12:46 UTC, rbsec approved these changes

2021-07-19 18:55 UTC, kingthorin requested changes
A few tweaks.

Also various ToCs need to be updated.

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Following a classic example that can help to better understand the issue.
```suggestion
The following is a classic example that can help to illustrate the issue.
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +In order to determine which part of the application is vulnerable to mass assignment, enumerate all parts of the application that accept content from the user and can potentially be mapped with a mod
```suggestion
In order to determine which part of the application is vulnerable to mass assignment, enumerate all parts of the application that accept content from the user and can potentially be mapped with a model. This includes all HTTP requests (most likely GET, POST, and PUT) that appear to allow create or update operations on the back end.
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +One of the most simple indicator for potential mass assignments is the presence of bracket syntax for input parameter names, as for example:
```suggestion
One of the most simple indicators for potential mass assignments is the presence of bracket syntax for input parameter names, as for example:
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Then try to add an input related to a non-exiting attribute (e.g. `user[nonexistingattribute]`) and analyze the response.
```suggestion
When such patterns are encountered try to add an input related to a non-exiting attribute (e.g. `user[nonexistingattribute]`) and analyze the response/behavior.
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +If the application does not implement any control (e.g. list of allowed fields) it is likely that it will respond with an error (e.g. 500) due to the fact that the application does not find the attri
```suggestion
If the application does not implement any control (e.g. list of allowed fields) it is likely that it will respond with an error (e.g. 500) due to the fact that the application does not find the attribute associated to the object. More interestingly, those errors sometimes facilitate discovery of attribute names and value data types needed to exploit the issue, without access to the source code.
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +For example, very often, it is possible to exploit handlers that returns detail about an object in order to gather clues on the associated fields.
```suggestion
For example, very often, it is possible to exploit handlers that return details about an object in order to gather clues on the associated fields.
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Suppose for example an handler that returns the profile of the user (e.g.  `GET /profile`), this may include further attributes related to the user (in this example the `isAdmin` attribute looks part
```suggestion
Suppose for example a handler that returns the profile of the user (e.g.  `GET /profile`), this may include further attributes related to the user (in this example the `isAdmin` attribute looks particularly interesting).
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Then try to exploit handlers that allow to modify or create user adding the `isAdmin` attribute configured to `true`.
```suggestion
Then try to exploit handlers that allow the modification or creation of users, adding the `isAdmin` attribute configured to `true`.
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Another approach is to use wordlists in order to try to enumerate all the potential attributes. The enumeration can then be automated (e.g. via wfuzz, Burp Intruder etc.). The sqlmap tool includes a
```suggestion
Another approach is to use wordlists in order to try to enumerate all the potential attributes. The enumeration can then be automated (e.g. via wfuzz, Burp Intruder, ZAP fuzzer, etc.). The sqlmap tool includes a [common-columns.txt](https://github.com/sqlmapproject/sqlmap/blob/master/data/txt/common-columns.txt) wordlist that can be useful to identify potential sensitive attributes.
```

2021-07-19 18:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Access to the db schema or to the source code allows also to easily identify sensitive fields.
```suggestion
Access to the DB schema or to the source code allows also to easily identify sensitive fields.
```

2021-08-10 16:58 UTC, kingthorin commented
I haven't reviewed all those latest changes. Hope to get to that later today. However, the following still need to be updated:
- https://github.com/OWASP/wstg/blob/master/document/README.md
- https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/README.md

2021-09-17 14:28 UTC, kingthorin reviewed
Just a few minor things

2021-09-17 14:28 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Examples for sensitive properties:
"Examples of sensitive properties:"

2021-09-17 14:28 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Laravel Eloquent ORM provides a `create` method which allows to automatically assign attributes. However, latest versions of Eloquent ORM provide a default protection against mass assignment vulnerab
```suggestion
Laravel Eloquent ORM provides a `create` method which allows automatic assignment of attributes. However, the latest versions of Eloquent ORM provide default protection against mass assignment vulnerabilities requiring to explicitly specify allowed attributes that can be assigned automatically, through the `$fillable` array, or attributes that have to be protected (non-bindable), trough the `$guarded` array. Therefore by analyzing the models (classes that extend the `Model` class) it is possible to identify which attributes are allowed or denied and therefore point out potential vulnerabilities.
```

2021-11-07 14:10 UTC, ThunderSon commented
@kingthorin are you able to push your changes and merge this in? I don't see a reason for this to stay open especially that the main contribution has been done :)

2021-11-07 15:31 UTC, kingthorin commented
Sure, will tackle that later today

2021-11-07 15:32 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment.md
> +Examples for sensitive properties:
```suggestion
Examples of sensitive properties:
```

2021-11-07 15:37 UTC, kingthorin approved these changes

2021-11-07 15:39 UTC, merged