DRAFT - Update HTTP method testing.
OWASP/wstg pull request #853
Opened 2022-02-24 17:11 UTC by rbsec

As per discussion on #852, the HTTP methods testing could do with a few updates. I've not gone through and done a proper QA on grammar, so the main questions are:

* Is it accurate?
* Is the structure sensible?
* Is there anything that needs adding?

I'm also a bit unsure about the "Testing for Access Control Bypass" section. I've never seen this issue, and the reference for it seems to be an [Archive.org link to a paper from 2004](https://web.archive.org/web/20160616172703/http://www.kernelpanik.org/docs/kernelpanik/bme.eng.pdf).

Has anyone ever come across this, and is it relevant enough to keep in the guide? Or should it be cut out as a niche legacy issue?

Any thoughts, comments and suggestions are welcome.

2022-02-24 23:42 UTC, ThunderSon reviewed
I love the initial rewrite.
We can add as well POST in the restful parts that PUT was discussed in, as well as for restful purpose.
Do we want to mention PATCH? Pretty sure people will encounter it in tests.

I think this opens up a door to comparing POST - PUT - PATCH since they might create some confusion.

What do you think?

2022-02-25 16:52 UTC, rbsec commented
@ThunderSon I've added a section on `PATCH` in 78e01ac2524b8977dd67bd55b0ef9a07708589af - have a read and see what you think. My concern would be that it's a pretty niche thing (I'm struggling to remember when I last saw it), and while it might be interesting for web developers, is it really that relevant from a *security* perspective?

With regards to `POST`, I didn't include a section on the legacy/REST split, because I don't really think that there is a meaningful one? In both cases it's doing more or less the same thing, and your testing steps would be more or less the same. It's just `PUT` and `DELETE` that are very different between the two, and lead to lots of false positive issues.

As for the different between `PUT`, `PATCH` and `POST`, I have a brief comment on the difference between the first two in the new section. I could add some discussion of the difference between `PUT` and `POST`, and talk about stuff like idempotency: but is that really something that's useful in this guide?

---

On an unrelated note, do you think I should take the `Host: example.org` out of all the HTTP request examples? I don't really like using `HTTP/1.1` requests without a `Host` header (as they're invalid), but perhaps it's just noise here?

2022-02-27 15:59 UTC, kingthorin commented
> On an unrelated note, do you think I should take the Host: example.org out of all the HTTP request examples? I don't really like using HTTP/1.1 requests without a Host header (as they're invalid), but perhaps it's just noise here?

It's a single line that makes it more realistic, I'm good with them staying.

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +An alternatively way to test for supported methods is to simply make a request with that method type, and examine the server response. If the method is not permitted, the server should return a `405
alternatively ➡️ alternative

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +Note that some servers treat unknown methods as equivalent to `GET`, so they may response to arbitrary methods, such as the request shown below. This can occasionally be useful to evade a web applica
may response ➡️ may respond

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +There are also a variety of automated tools that can attempt to determine supported methods, such as the [`http-methods`](https://nmap.org/nsedoc/scripts/http-methods.html) Nmap script. However, thes
if this methods ➡️ if these methods

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +This allows an attacker to upload arbitrary files to the webserver, which could potential result in a full system compromise if they are allowed to upload executable code such as PHP files. However,
could potential ➡️ could potentially

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +This allows an attacker to upload arbitrary files to the webserver, which could potential result in a full system compromise if they are allowed to upload executable code such as PHP files. However,
> code such as PHP files.

Worth mentioning something about web shells, rce, whatever? (Just as slightly more concrete context.)

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +By contrast, the `PUT` and `DELETE` methods are commonly used by modern RESTful applications to create and delete objects. For example, the API request below could be use to create a user called "foo
be use to create ➡️ be used to create

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +A similar requests with the DELETE method could be used to delete an object.
requests ➡️ request

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +The `TRACE` method causes the server to echo back the contents of the request. This lead to a vulnerability called Cross-Site Tracing (XST) being published in [2003](https://www.cgisecurity.com/white
Is it worth noting that "TRACK" is MS's implementation?

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +The `CONNECT` method causes the web server to open a TCP connection to another system, and then to pass traffic from the client through to that system. This could allow an attacker to proxy traffic t
I dunno it isn't "wrong" in any way but to be more consistent with earlier content the second "CONNECT" should probably be code fenced as well.

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +The following JSON PATCH request would change the role of this user "admin", without modifying the email address:
```suggestion
The following JSON PATCH request could change the role of this user to "admin", without modifying the email address:
```

2022-02-27 16:35 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +- [Nmap http-methods NSE script](https://nmap.org/nsedoc/scripts/http-methods.html)
Thanks for tweaking this. I hadn't put any thought into it before, but this does seem to be correct from a quick check I just did. I'll look into implementing a textlint rule for this :wink:

2022-02-27 16:45 UTC, rbsec commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +This allows an attacker to upload arbitrary files to the webserver, which could potential result in a full system compromise if they are allowed to upload executable code such as PHP files. However,
I feel like the existing text is fairly explicit? It says that you can upload PHP code to compromise a system - surely anyone who's doing this kind of testing should understand that?

2022-02-27 16:55 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +This allows an attacker to upload arbitrary files to the webserver, which could potential result in a full system compromise if they are allowed to upload executable code such as PHP files. However,
I'm fine with that. We've generally been assuming close to zero knowledge, but I also overthink things sometimes. So let's leave it as-is. We can always tweak later if someone wonders/asks. You're right it shouldn't be much of a leap if you're already reading this stuff :wink:

2022-02-27 17:08 UTC, kingthorin commented
I'm good with this at this point, just needs the linter item addressed.

2022-02-27 17:11 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +| [`PUT`](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.4) | Upload a file. | Create an object.
```suggestion
| [`PUT`](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.4) | Upload a file. | Create an object. |
```

I believe the lack of trailing pipe is the issue the linter is having.

2022-02-27 17:12 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +The server should then response with a list of supported methods:
Need a blank line in here to address the linter issue.

2022-02-27 17:23 UTC, rbsec commented
@kingthorin what do you think of the [Testing for Access Control Bypass](https://github.com/OWASP/wstg/blob/93f73dcbab8f504658627a99bac68ac925a46991/document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md#testing-for-access-control-bypass) section?

I've never seen this, and it seems to be a very legacy issue with one reference from 2004. Do you think it's worth keeping, or shall we strip it out?

2022-02-27 17:37 UTC, kingthorin commented
Yes sadly I have seen that. I can't put a specific timeframe on it, but definitely in the last 5y. I agree 2004 is a bit disappointing reference wise. We could try to find something newer, I'll dig around.... (or maybe we drop the ref 🤷 )

2022-02-27 17:50 UTC, rbsec commented
@kingthorin fair enough, I've updated the examples to keep the style consistent, and to cut out some fluff.

I think this is now ready.

2022-02-27 18:07 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +Alternatively, it may be possible make direct requests to pages that cause actions, such as:
```suggestion
Alternatively, it may be possible to make direct requests to pages that cause actions, such as:
```

2022-02-27 18:36 UTC, kingthorin approved these changes

2022-02-27 21:58 UTC, ThunderSon requested changes

2022-02-27 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +| [`POST`](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.3) | Submit data. | |
How about we set here for POST "Add to an object" in restful?
It happens mostly in 2 cases:
1. Add items to for example a json object
2. Add a new entity to a parent `POST /api/people -- { <data here for new object> }`

2022-02-27 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +An alternative way to test for supported methods is to simply make a request with that method type, and examine the server response. If the method is not permitted, the server should return a `405 Me
I feel like removing "alternative way". Sometimes OPTIONS requests aren't truthful, or default set by a server, etc. So maybe a word of advice that test things out always?

2022-02-27 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +There are also a variety of automated tools that can attempt to determine supported methods, such as the [`http-methods`](https://nmap.org/nsedoc/scripts/http-methods.html) Nmap script. However, thes
Hmm, we know about "dangerous methods", but new readers won't. Should we add a link to safe methods?
https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP is an example

2022-02-27 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +Or with cURL
Really picky comment, but let's add a `:` at the end

2022-02-27 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +Although it may be reported by automated scanning tools, the presence of these methods on a RESTful API **is not a security issue**. However, this functionality may have other vulnerabilities (such a
```suggestion
Although it may be reported by automated scanning tools, the presence of these methods on a RESTful API **is not a security issue**. However, this functionality may have other vulnerabilities (such as weak access control), and should be thoroughly tested.
```

2022-02-27 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +As with the `PUT` method, this functionality may have access control weaknesses or other vulnerabilities. Additionally, applications may not performed the same level of input validation when modifyin
```suggestion
As with the `PUT` method, this functionality may have access control weaknesses or other vulnerabilities. Additionally, applications may not perform the same level of input validation when modifying an object as they do when creating one. This could potentially allow malicious values to be injected (such as in a stored cross-site scripting attack), or could allow broken or invalid objects that may result in business logic related issues.
```

2022-02-27 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +If a page on the application redirects users to a login page with a `302` code when they try and access it direct, it may be possible to bypass this by making a request with a different HTTP method,
Other than the suggestion, this feels a bit repetitive. Not a hard requirement to merge, just an observation.
```suggestion
If a page on the application redirects users to a login page with a `302` code when they attempt to access it directly, it may be possible to bypass this by making a request with a different HTTP method, such as `HEAD`, `POST` or even a made up method such as `FOO`. If the web application responds with a `HTTP/1.1 200 OK` rather than the expected `HTTP/1.1 302 Found` then it may be possible to bypass the authentication or authorization. The example below shows how a `HEAD` request may result in a page setting administrative cookies, rather than redirecting the user to a login page:
```

2022-02-27 22:09 UTC, rbsec commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +An alternative way to test for supported methods is to simply make a request with that method type, and examine the server response. If the method is not permitted, the server should return a `405 Me
Changed to "a more reliable way"

2022-02-27 22:11 UTC, rbsec commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +There are also a variety of automated tools that can attempt to determine supported methods, such as the [`http-methods`](https://nmap.org/nsedoc/scripts/http-methods.html) Nmap script. However, thes
Changed this to:

...dangerous methods (i.e, methods that may cause changes such as `PUT`...)

2022-02-27 22:13 UTC, rbsec commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +| [`POST`](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.3) | Submit data. | |
I'm not sure that's really accurate though? A REST API would normally use a `POST` request for a login page (for instance) - but that's not adding an item to an object, or creating a new entity.

2022-02-27 22:18 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +| [`POST`](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.3) | Submit data. | |
Hmmm, yeah. Let's stay without it since it serves so many purposes.

2022-02-27 22:20 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +There are also a variety of automated tools that can attempt to determine supported methods, such as the [`http-methods`](https://nmap.org/nsedoc/scripts/http-methods.html) Nmap script. However, thes
Mind if we add that to the references at the end? The updated sentence explains it well, just want to be sure that users have a clear reference for it.

2022-02-28 18:34 UTC, rbsec commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
> +There are also a variety of automated tools that can attempt to determine supported methods, such as the [`http-methods`](https://nmap.org/nsedoc/scripts/http-methods.html) Nmap script. However, thes
Added

2022-03-01 23:29 UTC, ThunderSon reviewed
LGTM!

2022-03-01 23:29 UTC, ThunderSon approved these changes

2022-03-01 23:30 UTC, merged