Fix 935
OWASP/wstg pull request #950
Opened 2022-07-05 06:03 UTC by manindar-mohan

This PR covers issue #<issue number>.

- [ *] This PR handles the issue and requires no additional PRs.
- [ *] You have validated the need for this change.

**What did this PR accomplish?**

- Content update of WSTG-CONF-12 mentioning the unsafe-hashes CSP directive

Thank you for your contribution!

2022-07-05 10:49 UTC, kingthorin requested changes

2022-07-05 10:49 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
> +- `unsafe-hashes` directive allows us to provide inline code, by computing a SHA-256 hash of our code.
```suggestion
- `unsafe-hashes` directive allows use of inline scripts/styles, assuming they match the specified hashes.
```

2022-07-05 10:50 UTC, kingthorin commented
Please add the link from the original ticket to the references section.

2022-07-06 04:50 UTC, manindar-mohan commented
Updated the PR

2022-07-06 10:06 UTC, kingthorin approved these changes

2022-07-06 10:06 UTC, merged