Fix 701
OWASP/wstg pull request #952
Opened 2022-07-13 07:39 UTC by manindar-mohan

This PR covers issue #<issue number>.

- [ *] This PR handles the issue and requires no additional PRs.
- [ *] You have validated the need for this change.

**What did this PR accomplish?**

- Mitigate Clickjacking by Content-Security-Policy Using frame-ancestors directive
- Reference [https://github.com/OWASP/wstg/issues/701]
Thank you for your contribution!

2022-07-20 01:16 UTC, manindar-mohan commented
Any issue I need to update? still, the pull request is pending.

2022-07-20 10:10 UTC, kingthorin commented
It hasn’t been forgotten, just some life stuff in the way. I’ll tackle it next week when things should be less hectic.

2022-08-02 13:23 UTC, kingthorin requested changes

2022-08-02 13:23 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
> +| Chrome            | 40              |
Is there really any benefit in including this information at this point. If it's been in available for 5+ years I'm not convinced this is worth including. If we "need" to say something I'd suggest more along the lines of:

> Supported in all mainstream modern browsers.

But I'm not sure that's is even of any benefit.

@ThunderSon @rbcsec thoughts? feedback?

2022-08-02 13:23 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
> +| Chrome            | 40              |
If this is kept "version" should get a capital as a column heading/title.

2022-08-06 13:20 UTC, manindar-mohan commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
> +| Chrome            | 40              |
The heading is changed to capital, if the browser compatibility section is not required let me know will remove it. I was following the standard from the same document.

2022-08-06 14:19 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
> +| Chrome            | 40              |
Hmmm ya I see that it's also on the XFO entry. I guess that clean-up can be done separately.

2022-08-06 14:23 UTC, merged