Add MFA testing guide
OWASP/wstg pull request #971
Opened 2022-09-10 14:34 UTC by rbsec

Initial draft of a guide on testing MFA (as per #949).

I've not gone through for a wording/grammar/spelling check yet - at this stage the key questions are:

- Does the structure it make sense?
- Is there anything wrong?
- Is there anything missing?
- Is there anything that should be removed?

Once we're happy with the content, it can have a proper QA.

2022-09-10 15:12 UTC, ThunderSon commented
wake up @kingthorin rbsec just created a new page 🔥 
Had to use the meme template haha. I'll be reviewing this very soon/shortly! Thanks for sending it in :)

2022-09-10 15:56 UTC, kingthorin commented
Great, will review shortly

2022-09-12 22:39 UTC, kingthorin commented
Hey crew, I haven’t forgotten this. Things have just gotten a bit stupid here. I may not get to this till next week. Sorry!

2022-09-20 22:53 UTC, ThunderSon requested changes
Great draft @rbsec !! Amazing information thrown in there
This is my first review of it :)

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Location | Source IP ranges and geolocation |
Should we mention the Behavioural factor as well since we're bringing in Location?

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
You mention 2SV but don't clarify the difference between 2FA and 2SV. Worried people would think it's the same. One has distinct "Factors", the other has distinct "Steps".

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
do we want to say SMS and phone calls, or SIM card? maybe mention those 2 within the SIM piece? Wdyt?

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Due to the complexity of implementing biometrics in a browser-based environment, "Something You Are" is rarely used for web applications. The most common second factor is "Something You Have".
Do we want to keep this with the enablement of WebAuthn? I believe it's gaining some good traction, especially with most systems implementing Face ID or Fingerprint scanners 🤔
I can try and see metrics around this if we agree on it.

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Note that requiring multiple examples of a single factor (such as needing both a password and a PIN) **does not constitute MFA**, although it may provide some security benefits over a simple password
Maybe mention this is 2SV?

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- The main login page.
Another would be for step-up authentication pages that requires a secondary factor in certain spots.

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Federated login providers.
We can add some details here around this, as in a "new" identity might be created, or override the MFA configuration on a user/pass identity, or allow the user to re-define their MFA factor

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If the authentication is done in multiple steps then it may be possible to bypass it by completing the first step of the authentication process (entering the username and password), and then force-br
I've seen some apps modify the session, and then persist it -- if that token is leaked after days, the MFA trigger doesn't happen (unless they have device authentication and blocks a token from being used on different devices). But maybe mentioning the "MFA session" lifetime and reviewing the type of application that's being tested could be important here.

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- When  is a specific HTTP header is set.
I believe this was the latest incident around this that broke a part of the internet: https://securityflow.io/how-i-could-exploit-the-cve-2022-1388/
If we wanna inline reference it here, or maybe in the references.

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Finally, if the MFA is implemented on a different system to the main application (such as on a reverse proxy, in order to protect a legacy application that does not natively support MFA), then it may
@kingthorin do we have any guidance on "bypassing proxies" or WAFs? Or is this something we should look to do? (writing comments directly, didn't check our docs yet)

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +There are also several business-logic related areas that should be reviewed, which will depend on the context and requirements of the application:
This line ends with ` :` - just checking if you meant to write more here, or a typo.

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- They are appropriately long and complex.
They are usually 6 digits 😅 I think MFA recovery codes don't follow the typical "long" and "complex" requirements we find elsewhere.

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- The user is notified when a code is used.
maybe add here `on a different channel` on top of the main one (just to make this explicit for the reader)

2022-09-20 22:53 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Valid Codes | Success rate after 1 hour | Success rate after 4 hours | Success rate after 12 hours | Success rate after 24 hours |
Love this table! Do you have a reference for it that we can mention or add somewhere for validity?

2022-09-21 08:06 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +There are also several business-logic related areas that should be reviewed, which will depend on the context and requirements of the application:
This line was from an earlier draft - removed.

2022-09-21 08:07 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- They are appropriately long and complex.
Recovery codes *should* be much longer than OTP codes because they don't change. For example, the GitHub ones are 10 hex characters with a hyphen in the middle, which is significantly stronger.

2022-09-21 08:10 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
In the days of VoIP, I'm not sure that we can really make a strong link between a SIM card and a phone number - but given the issues with SIMs I'm not really sure you could argue that a VoIP based phone is less secure for this. And it would raise the question about what exactly it is that you "have" for an email account...

2022-09-21 08:14 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Due to the complexity of implementing biometrics in a browser-based environment, "Something You Are" is rarely used for web applications. The most common second factor is "Something You Have".
I'm not really familiar with Face ID, but to what extent is it considered actually biometric? Are you actually authenticating with biometric data, or is it just being used to protect a local vault that contains your credentials? If it's the latter, is that really considered biometric?

2022-09-21 08:18 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If the authentication is done in multiple steps then it may be possible to bypass it by completing the first step of the authentication process (entering the username and password), and then force-br
Added

2022-09-21 08:18 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Federated login providers.
Added

2022-09-21 08:19 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Location | Source IP ranges and geolocation |
Are you thinking of stuff like typing speed/style (which would fall under biometrics)? Or the more risk-based factors like time of day, previous usage patterns, etc? Are those strictly a factor, and is there any good reference we can point to?

2022-09-21 08:21 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
Is there any actual agreement on this, or authoritative sources that we can point to? Because [NIST](https://www.nist.gov/blogs/cybersecurity-insights/whoa-oh-were-halfway-there-happy-nsticiversary) and [NCSC](https://www.ncsc.gov.uk/guidance/setting-2-step-verification-2sv) both say that they're synonyms.

2022-09-21 08:23 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If the authentication is done in multiple steps then it may be possible to bypass it by completing the first step of the authentication process (entering the username and password), and then force-br
If sessions are persisting for days, that seems more like a general session management issue than an MFA related one?

2022-09-21 08:25 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- When  is a specific HTTP header is set.
It's an interesting attack, but is it MFA related? I suppose if they've configured Apache with TOTP or something it might be - but it seems like a more general authentication bypass.

2022-09-21 08:52 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Valid Codes | Success rate after 1 hour | Success rate after 4 hours | Success rate after 12 hours | Success rate after 24 hours |
There isn't an external reference - these numbers were calculated based on the probability of independent attempts being successful (or technically, not being successful) - but it didn't seem worth taking up a couple of paragraphs to go through the maths behind it.

However, as the same time this guide gets brought live, I'm going to post an article that talks through this specific issue in more detail and shows the working - so once they're both live I'll add an XREF to it here?

2022-09-30 12:07 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
If they're used synonymously is it worth mentioning both?

2022-09-30 12:08 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
```suggestion
| Something You Have | Hardware or software tokens, certificates, email, SMS, and phone calls. |
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Are | Fingerprints, facial recognition, iris scans and handprint scans. |
```suggestion
| Something You Are | Fingerprints, facial recognition, iris scans, and handprint scans. |
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Location | Source IP ranges and geolocation |
```suggestion
| Location | Source IP ranges, and geolocation. |
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Due to the complexity of implementing biometrics in a browser-based environment, "Something You Are" is rarely used for web applications. The most common second factor is "Something You Have".
I believe WebAuthn does actually use the biometric.

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- API endpoints (from both the main web interface and mobile apps)
```suggestion
- API endpoints (from both the main web interface and mobile apps).
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- When  is a specific HTTP header is set.
I think there's something missing in this bullet, there's a weird double space and it doesn't quite read clearly.

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Finally, if the MFA is implemented on a different system to the main application (such as on a reverse proxy, in order to protect a legacy application that does not natively support MFA), then it may
Not that I recall.

Though it might be covered in one of the mapping/enumeration sections. I'm also not sure if we have anything on unmasking origins behind CDNs (which would also be a good to have).

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +The functionality used to manage MFA from inside the users account should be tested for vulnerabilities, including:
```suggestion
The functionality used to manage MFA from inside the user's account should be tested for vulnerabilities, including:
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +### One-Time Passwords (OTPs)
```suggestion
### One-Time Passwords
```

This will make the anchor shorter and it's expanded in the first line which is likely a better spot anyway.

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +The most common form of of MFA is the one of One-Time Passwords (OTPs), which are typically six-digit numeric codes (although they can be longer or shorter). These can either be generated by both the
```suggestion
The most common form of of MFA is the one of One-Time Passwords (OTPs), which are typically six-digit numeric codes (although they can be longer or shorter). These can either be generated by both the server and the user (for example, with an authenticator app), or can be generated on the server and sent to the user. There are various ways that this OTP can be provided to the user, including:
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Where the secret is generated on the server, it should be checked to ensure that it is sufficiently long and complex ([REF 4226](https://www.rfc-editor.org/rfc/rfc4226#section-4) recommends at least
```suggestion
Where the secret is generated on the server, it should be checked to ensure that it is sufficiently long and complex ([RFC 4226](https://www.rfc-editor.org/rfc/rfc4226#section-4) recommends at least 160 bits), and that it is generated using a [secure random function](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html#secure-random-number-generation).
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +TOTP codes are typically valid for 30 seconds, but some applications choose to accept multiple codes (such as the previous, current and next codes) in order to deal with differences between the syste
```suggestion
TOTP codes are typically valid for 30 seconds, but some applications choose to accept multiple codes (such as the previous, current, and next codes) in order to deal with differences between the system time on the server and on the user's device. Some applications may allow multiple codes on either side of the current one, which may make it easier for an attacker to guess or brute-force the code. The table below shows the chance of successfully brute-forcing an OTP code based on an attacker being able to make 10 requests a second, for applications that accept either only the current code, or multiple codes.
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Valid Codes | Success rate after 1 hour | Success rate after 4 hours | Success rate after 12 hours | Success rate after 24 hours |
Sounds good.

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +#### Email, SMS and Phone
```suggestion
#### Email, SMS, and Phone
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Is the transport mechanism (email, SMS or voice) secure enough for the application?
```suggestion
- Is the transport mechanism (email, SMS, or voice) secure enough for the application?
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Depending on the implementation, it may be possible for a user to spoof a trusted IP address by setting the `X-Forwarded-For` header, which could allow them to bypass this check. Note that if the app
```suggestion
Depending on the implementation, it may be possible for a user to spoof a trusted IP address by setting the `X-Forwarded-For` header, which could allow them to bypass this check. Note that if the application does not correctly sanitize the contents of this header, it may also be possible to carry out attack such as SQL injection here. If the application supports IPv6, then this should also be checked to ensure that appropriate restrictions are applied to those connections.
```

2022-09-30 12:29 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If a valid certificate can be obtained, then it should also be verified that the certificate can only be used for the user that it is issued for (i.e, that you can't use a certificate issued to Alice
Add something about checking revocation?

2022-10-01 14:49 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
TBH, I'm not sure if it confuses matters more or less having them - since no one can really agree on what they actually mean.

2022-10-01 14:52 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Due to the complexity of implementing biometrics in a browser-based environment, "Something You Are" is rarely used for web applications. The most common second factor is "Something You Have".
I've added a reference to it on this line.

2022-10-01 14:52 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Note that requiring multiple examples of a single factor (such as needing both a password and a PIN) **does not constitute MFA**, although it may provide some security benefits over a simple password
Unless we can clearly define the difference between MFA and 2SV (in a way that agrees with other sources), I think that would just confuse matters?

2022-10-01 14:53 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- When  is a specific HTTP header is set.
Fixed

2022-10-01 14:58 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If a valid certificate can be obtained, then it should also be verified that the certificate can only be used for the user that it is issued for (i.e, that you can't use a certificate issued to Alice
Added

2022-10-01 15:02 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Finally, if the MFA is implemented on a different system to the main application (such as on a reverse proxy, in order to protect a legacy application that does not natively support MFA), then it may
There's some stuff in 01-Information_Gathering/10-Map_Application_Architecture.md - I've added a link to that.

2022-10-02 21:18 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
For email, you can't consider that people have MFA on it. You have your credentials (user/pw), thus something you have. That's agreed upon in the standards and heavily discussed in the banking industry.
For the other one, I'll leave it to your judgement on if it needs changing or not, as we agree on the situation and it won't make a big difference.

2022-10-02 21:20 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Location | Source IP ranges and geolocation |
So behavioural biometrics can be those, maybe a mention about them? People might encounter them that's for sure. Not fussed about having a whole section about it. Web testing doesn't heavily rely on it, but definitely makes an appearance here and there.

2022-10-02 21:21 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Note that requiring multiple examples of a single factor (such as needing both a password and a PIN) **does not constitute MFA**, although it may provide some security benefits over a simple password
I'm gonna discuss this at the first comment, and then based on the result we see what to do here.

2022-10-02 21:32 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If the authentication is done in multiple steps then it may be possible to bypass it by completing the first step of the authentication process (entering the username and password), and then force-br
I see how you're looking at it. I can agree to it as the user "logged in" whether it's 1FA, 2FA, or NFA.

Should we outsource this issue to session management? We can mention "MFA bypass due to session leakage", and maybe a resolution to that is "3/NFA" for the session itself (most companies rely on device data, location, etc.)

What do you think?

2022-10-02 21:36 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- They are appropriately long and complex.
I hear you -- should we mention/link this somewhere: https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#backup-codes ?

My beef in this sentence was with "appropriate", as that can be skewed to the wrong side a lot of the times.

2022-10-02 21:43 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
What do you feel about us defining this matter?
2SV encompasses 2FA within it, but not the other way around.

We can't say that username -> password1 -> password2 is 2FA, but can say it is 2SV.
There's definitely 2 steps, yet the factor is the same.

I don't mind raising this up to the related bodies and having a conversation about this.
What are your own thoughts about this matter?

It might not be a big matter, but I believe we need to define this to avoid confusion.
We can merge this PR, and then have an issue on it to not derail this great effort here.

2022-10-05 11:22 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Is there any kind of challenge and response mechanism (such as providing a code on the website that the user needs to enter into the app)?
Number challenge (on top of push). Maybe we should mention the main naming for it?
 refs:
1. https://learn.microsoft.com/en-us/azure/active-directory/authentication/how-to-mfa-number-match
2. https://help.okta.com/en-us/Content/Topics/Mobile/ov-admin-config.htm#enable-number-challenge

2022-10-05 11:22 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Is there any rate limiting or mechanisms to prevent the user from being spammed with notifications?
Wanna refer/mention MFA fatigue attacks?

2022-10-05 11:24 UTC, ThunderSon commented
One thing I felt we might have missed on, MFA user confusion. Maybe the platform uses/sends specific variables and the app doesn't hard-link them to a specific user, allowing for the bypass.
If I missed the mention of this apologies, I skimmed the document and didn't see it 🤔

2022-10-06 16:34 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- They are appropriately long and complex.
I've changed it to "sufficiently long and complex to protect against brute-force attacks", which is the same language used in the cheat sheet (and added a link to it) - does that seem reasonable?

2022-10-06 16:35 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Location | Source IP ranges and geolocation |
I added it to the "something you are"

2022-10-06 16:37 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
TBH, I think that the issues around VoIP are just going to confuse matters. I've always felt that calling email "something you have" is a bit weak, but it seems pretty common, so we'll go with it.

2022-10-06 16:41 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Is there any kind of challenge and response mechanism (such as providing a code on the website that the user needs to enter into the app)?
Added the names in as a comment

2022-10-06 16:43 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Is there any rate limiting or mechanisms to prevent the user from being spammed with notifications?
I think that's kind of covered by this - is there a specific extra check you think is worth adding here?

2022-10-06 17:12 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
The problem is that trying to clearly define these is a bit of a minefield - because well known authorities like NCSC have published articles saying they're the same thing. And while you can find various blogs and articles talking about the differences, I didn't really see any authoritative sources (like NCSC or NIST) that clearly define them as different.

And if we try and define them ourselves, we end up with a load of arguments about edge cases - because (by strict definitions) you can have authentication that's 2SV and 1FA, and also that's 1SV and 2FA) - so you end up with a load of bickering about exactly what constitutes which.

But even if we did want to have that argument, the Web Security *Testing Guide* is not the place to be trying to come up with universally accepted definitions of things like this, and the exact differences between them are not generally something that an app tester needs to be focusing on.

---

So how about this:

* Adding "although these are not strictly the same thing" after `(2SV`) in the text above.
* Adding "although this may be considered to be 2SV" to the comments below about passwords + PINs.
* Leaving the MFA vs 2FA vs 2SV argument to someone else.

2022-10-06 17:13 UTC, rbsec commented
> One thing I felt we might have missed on, MFA user confusion. Maybe the platform uses/sends specific variables and the app doesn't hard-link them to a specific user, allowing for the bypass. If I missed the mention of this apologies, I skimmed the document and didn't see it thinking

Is there a specific attack/testing scenario that you're thinking of here?

2022-10-06 17:25 UTC, kingthorin commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
Sounds good to me.

2022-10-06 22:14 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
I hope you enjoyed writing that as much as I enjoyed reading it 😋 
I'm good with it as well.

2022-10-06 22:27 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
I'd say the email is mostly agreed upon to be something you know, based on username and password, more so than something you have (I've seen that way more). Most identity providers call it as such, and the banking industry (PSD2->SCA) refutes it altogether.

2022-10-06 22:28 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Is there any rate limiting or mechanisms to prevent the user from being spammed with notifications?
Not necessarily "extra" check, more of a reference to the attacks for the reader to see a direct scenario of its occurrence.

2022-10-06 22:33 UTC, ThunderSon commented
1. Person A generates MFA code A under User A, but doesn't consume the MFA code.
2. Person A has credentials of User B, logins in and uses MFA code A.

The problem here is the lack of mapping the code to the user that generates it.
Or mapping it to a certain token sent in the request, so modifying the above example:
1. Person A generates MFA code A + token A.
2. Person A logs in as User B, replaces token B with token A, and uses MFA code A.

Those are some scenarios I can think of right now.

2022-10-06 22:34 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- They are appropriately long and complex.
Yep, thank you for those changes! ❤️

2022-10-06 22:36 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If the authentication is done in multiple steps then it may be possible to bypass it by completing the first step of the authentication process (entering the username and password), and then force-br
I don't think it's a testing step in here. I agree it should be in session management. I didn't I guess resolve it cause I was taking your final thoughts. All's good 👍

2022-10-07 10:28 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
That's seems to be the exact opposite of what you said in your previous comment:

> You have your credentials (user/pw), thus something you have. That's agreed upon in the standards and heavily discussed in the banking industry.

2022-10-07 10:35 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
I'm sorry 😭 apologies for that. It's something you know

2022-10-07 17:23 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
Again, I think this is an area where we're going to struggle to make the argument against the likes of [NCSC](https://www.ncsc.gov.uk/collection/top-tips-for-staying-secure-online/activate-2-step-verification-on-your-email) and [NIST](https://www.nist.gov/itl/smallbusinesscyber/guidance-topic/multi-factor-authentication) who are both counting it as "something you have".

So again, how about we avoid the problem by sticking a `*` next to it and add a sentence like:

> Note that whether email counts as "something you have" depends on whether the email account is itself protected by MFA, so this may not truly represent a second factor.

2022-10-07 17:42 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +| Something You Have | Hardware or software tokens, certificates, email, SMS and phone calls. |
I want to be careful about this though. NCSC and NIST in those docs are targeting more not so technical audience, whereas from our outlook, we are talking technical to the best extent. For MFA vs MSV, it was an easier conversation that wouldn't impact things much, but this one is different. The bodies enforcing stricter security measures is clear on this piece with emails. We would be held up against those bodies versus the "cyber aware" guidance from either of NCSC and NIST.

I am going to stick with it being in "something you know" with your note, and flipping the note to be for "something you have". It aligns with how weak as an MFA factor the email OTP is on its own. The industry is moving slowly towards this from how MFA factors are being discussed everywhere.

Do you feel this would work? I've honestly reviewed this so many times in the protocols demanding strict security solutions and as you mentioned at the start, it was a heated debate, always falling into "something you know" at the end of it.

2022-10-07 23:49 UTC, ThunderSon commented
Let's give this one last review this week for the simple bits before bringing this in. Content is 👌

2022-10-17 21:58 UTC, ThunderSon reviewed
Text touch up

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Many applications implement multi-factor authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verifi
just capitalizing some letters
```suggestion
Many applications implement Multi-Factor Authentication (MFA) as an additional layer of security to protect the login process. This is also known as two-factor authentication (2FA) or two-step verification (2SV) - although these are not striclty the same thing. MFA means asking the user to provide *at least* two different [authentication factors](#types-of-mfa) when logging in.
```

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +Where an application supports both local and federated logins, it may be possible to bypass the MFA if there is not strong separation between these two types of accounts. For example, if a user regis
```suggestion
Where an application supports both local and federated logins, it may be possible to bypass the MFA if there is not strong separation between these two types of accounts. For example, if a user registers a local account and configures MFA for it, but does not have MFA configured on their account on the federated login provider, it may be possible for an attacker to re-register (or link) a federated account on the target application with the same email address by compromising the user's account on the federated login provider.
```

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If the application implements an MFA reset process, this should be tested in the same way that the [password reset process](09-Testing_for_Weak_Password_Change_or_Reset_Functionalities.md) is tested.
```suggestion
If the application implements an MFA reset process, this should be tested in the same way that the [password reset process](09-Testing_for_Weak_Password_Change_or_Reset_Functionalities.md) is tested. It is important that this process is *at least* as strong as the MFA implementation for the application.
```

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +The OTP is typically entered after the user has provided their username an password. There are various checks that should be performed, including:
```suggestion
The OTP is typically entered after the user has provided their username and password. There are various checks that should be performed, including:
```

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- How strong are OTPs (keyspace)?
I'm worried even my suggestion isn't really understood by new comers to the field with what `keyspace` meaning. Any thoughts?
```suggestion
- How strong are OTPs (character keyspace)?
```

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +    - Are multiple OTPs valid at once?
I feel this should be on the same level as the other checks. They are not strictly related to one another 🤔

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Can they be used more than once?
You switched OTPs with "they" in the last two checks. Maybe we should stay consistent with OTPs across them all?

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If there are no restrictions, then it may be possible to authenticate using a certificate from a different CA. If there are restrictions by they are badly implemented, it may be possible to create a
```suggestion
If there are no restrictions, then it may be possible to authenticate using a certificate from a different CA. If there are restrictions but they are badly implemented, it may be possible to create a local CA with the correct name ("Example Org Root Certificate Authority" in the example above), and to use this new CA to sign client certificates.
```

2022-10-17 21:58 UTC, ThunderSon commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +If a valid certificate can be obtained, then it should also be verified that the certificate can only be used for the user that it is issued for (i.e, that you can't use a certificate issued to Alice
```suggestion
If a valid certificate can be obtained, then it should also be verified that the certificate can only be used for the user that it is issued for (i.e, that you can't use a certificate issued to Alice to authenticate on Bob's account). Additionally, certificates should be checked to ensure that they have neither expired nor been revoked
```

2022-10-18 19:59 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +    - Are multiple OTPs valid at once?
Fixed

2022-10-18 19:59 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- How strong are OTPs (keyspace)?
Changed to "length and character keyspace"

2022-10-18 19:59 UTC, rbsec commented on document/4-Web_Application_Security_Testing/04-Authentication_Testing/11-Testing_Multi-Factor_Authentication.md
> +- Can they be used more than once?
Fixed

2022-10-18 20:00 UTC, rbsec commented
@ThunderSon I've addressed all your suggestions in the most recent commit(s).

2022-10-18 22:01 UTC, ThunderSon approved these changes
Thank you for the several rounds and iterations of work!
@kingthorin once you're happy with the content, this can be merged :)

2022-10-18 22:05 UTC, kingthorin commented
Will try to tackle that shortly.

2022-10-22 14:15 UTC, kingthorin approved these changes

2022-10-22 14:16 UTC, merged