Create C-Fuzzing.md
OWASP/wstg pull request #979
Opened 2022-10-08 04:03 UTC by maheshbasnet089

This PR covers issue #588 .

- [ ] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

This PR handles the issue and requires no additinal PRs afterward
All the introduction, why fuzzing needed , tools example , refrences and worlist are provide ini this pr 

Thank you for your contribution!

2022-10-08 12:07 UTC, kingthorin commented
This was meant to integrate with the existing Annex C, which may include the need to rename it and update links throughout the guide.

2022-10-08 13:16 UTC, maheshbasnet089 commented
Should I rename it to exact name of previous file (fuzzing-vector.md)?

2022-10-08 20:57 UTC, kingthorin requested changes
The file and all links throughout the doc should probably be updated to `C-Fuzzing.md` or `C-Fuzz_Overview.md`

@thunderson, any preference on the name?

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +Fuzzing the process or technique of sending huge number of request to the target website in a certain interval of time. In other word, it is also similiar to bruteforcing. Fuzzing is the process whic
```suggestion
Fuzzing the process or technique of sending a number of request to the target website in a certain interval of time. In other words, it is also similar to bruteforcing. Fuzzing is a process which can be achieved using tools like Wfuzz, ffuf, and so on. You need to provide the tool with the target url, parameter, endpoint, etc and some sort of inputs. Then the fuzzing tool crafts requests and send them to the target one after another. After the fuzzing has finished, the responses, timing, and status codes need to be analyzed for vulnerabilities.
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +Testing a website for vulnerability by feding input one by one manually can be hectic. In the present era where people have got less time and less patience level, these manually feding of testing inp
```suggestion
Testing for vulnerabilities by feeding input one by one manually can be hectic. In the present era where people have got less time and less patience level, the idea of manually feeding input for finding bugs/vulnerabilities in the target can be overwhelming. To reduce this overwhelming problem and to save time, fuzzing can be a big plus point. Fuzzing is an automated process where all the hard work is handled by a fuzzing tool. All an analyst has to do is look is the responses, timing, and the status codes after the process is done. Consider a site where there are a many input fields to test for XSS. In a manual approach, all we do is feed the input field with XSS payloads one by one, which would be much too hectic. In contrast, for an automated approach, all you need is to provide the XSS payload list to the fuzzer  and all input testing is handled by fuzzer.
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +## Tools to use for fuzzing
```suggestion
## Tools to Use for Fuzzing
```

https://capitalizemytitle.com/style/Chicago/

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +There are hundreds of tools available at the market for doing fuzzing thing. But some of the top rated, popular fuzzinig tools or fuzzer are enlisted below.
```suggestion
There are hundreds of tools available in the industry for doing fuzzing. But some of the top rated, popular fuzzing tools are listed below.
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +Wfuzz is the most popular fuzzing tool in the present days. Wfuzz works by replacing the wordlist value to the place where there is placeholder FUZZ. To understand it more cleary, lets see an example
```suggestion
### Wfuzz

[Wfuzz](https://github.com/xmendez/wfuzz) works by replacing the wordlist value to the place where there is placeholder `FUZZ`. To understand this more clearly let's consider an example:
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +In the above command, userIds.txt is the worldlist file containing all the numberic ID values. Here,we are telling wfuzz to fuzz the request to the example URL,note that FUZZ word in the URL, it will
```suggestion
In the above command, `userIds.txt` is a worldlist file containing numeric ID values. Here,we are telling wfuzz to fuzz the request to the example URL. Note that `FUZZ` word in the URL, it will act as a placeholder for wfuzz to replace with values from the wordlist. All the numeric IDs value of the `userIDs.txt` file will be inserted replacing `FUZZ` keyword.
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +Ffuf is the next web fuzzing tool written in Go language which is very fast and recursive in nature. It works same as a Wfuzz but in contrast it is recursive.Ffuf also works by replacing the placehol
```suggestion
### Ffuf

[Ffuf](https://github.com/ffuf/ffuf) is a web fuzzing tool written in the Go language which is very fast and recursive in nature. It works similar to Wfuzz but in contrast it is recursive. Ffuf also works by replacing the placeholder `FUZZ` with worldlist values. For example:
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +Here -w  is the flag for wordlist and -u is the flag for URL.The rest of the working mechanism is same as the wfuzz. It replaces FUZZ word with userIDs.txt values.
```suggestion
Here the `-w` is the flag for wordlist and `-u` is the flag for the target URL. The rest of the working mechanism is the same as the Wfuzz. It replaces the `FUZZ` placeholder with `userIDs.txt` values.
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +directory,DNS subdomains,AWS S3 bucket,Virtual hostnames and supports concurrency.To understand it more properly, lets seen an example.
```suggestion
### GoBuster

[GoBuster](https://github.com/OJ/gobuster) is another fuzzer written in the Go language which is most used for fuzzing URIs, directories/paths, DNS subdomains, AWS S3 buckets, vhost names, and supports concurrency. For example:
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +In the above command dir speciefies we are fuzzing directory, -u is the flag for URL and -w is the flag for wordlist where endpoints.txt is the worldlist file for doing fuzzing.The command runs concu
```suggestion
In the above command `dir` specifies we are fuzzing a directory, `-u` is the flag for URL and `-w` is the flag for wordlist where `endpoints.txt` is the worldlist file payloads will be taken from. The command runs concurrent request to the endpoint to find available directories.
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +### Wordlists and refrences
```suggestion
### Wordlists and References
```

2022-10-08 20:57 UTC, kingthorin commented on document/6-Appendix/C-Fuzz_Vector.md
> +In the above section , we have seen why we need a wordlist. Just wordlist is not enough,the worlist must great for you fuzzing condition. If you don't find any wordlists that matches your condition t
```suggestion
In the examples above we have seen why we need a wordlist. Just wordlists are not enough, the worlist must great for your fuzzing scenario. If you don't find any wordlists that match the necessary scenario then consider generating your own wordlist. Some popular wordlists and references are provided below.
```

2022-10-09 03:13 UTC, maheshbasnet089 commented
Is it okay or should more need to be updated @kingthorin sir?

2022-10-09 06:39 UTC, kingthorin commented
Well all the suggestions need to be applied, assuming you agree with them.

The file name and references/links will need to be adjusted after @ThunderSon chimes in on naming :wink:

2022-10-09 08:23 UTC, maheshbasnet089 commented
Yes king sir your all suggestions have been updated

2022-10-09 12:06 UTC, kingthorin commented on document/6-Appendix/C-Fuzzing.md
> +Testing for vulnerabilities by feeding input one by one manually can be hectic. In the present era where people have got less time and less patience level, the idea of manually feeding input for find
```suggestion
Testing for vulnerabilities by feeding input one by one manually can be hectic. In the present era where people have got less time and less patience level, the idea of manually feeding input for finding bugs/vulnerabilities in the target can be overwhelming. To reduce this overwhelming problem and to save time, fuzzing can be a big plus point. Fuzzing is an automated process where all the hard work is handled by a fuzzing tool. All an analyst has to do is look at the responses, timing, and the status codes after the process is done. Consider a site where there are a many input fields to test for XSS. In a manual approach, all we do is feed the input field with XSS payloads one by one, which would be much too hectic. In contrast, for an automated approach, all you need is to provide the XSS payload list to the fuzzer and all input testing is handled by fuzzer.
```

2022-10-09 12:06 UTC, kingthorin commented on document/6-Appendix/C-Fuzzing.md
> +In the above command, `userIds.txt` is a worldlist file containing numeric ID values. Here,we are telling wfuzz to fuzz the request to the example URL. Note that `FUZZ` word in the URL, it will act a
```suggestion
In the above command, `userIds.txt` is a worldlist file containing numeric ID values. Here,we are telling wfuzz to fuzz the request to the example URL. Note that `FUZZ` word in the URL, it will act as a placeholder for wfuzz to replace with values from the wordlist. All the numeric IDs value of the `userIDs.txt` file will be inserted replacing the `FUZZ` keyword.
```

2022-10-09 12:06 UTC, kingthorin commented on document/6-Appendix/C-Fuzzing.md
> +In the above command `dir` specifies we are fuzzing a directory, `-u` is the flag for URL and `-w` is the flag for wordlist where `endpoints.txt` is the worldlist file payloads will be taken from. Th
```suggestion
In the above command `dir` specifies we are fuzzing a directory, `-u` is the flag for URL and `-w` is the flag for wordlist where `endpoints.txt` is the worldlist file payloads will be taken from. The command runs concurrent requests to the endpoint to find available directories.
```

2022-10-10 02:18 UTC, maheshbasnet089 commented
anything more to be updated @kingthorin sir?

2022-10-10 11:59 UTC, kingthorin commented
Just the file name and links throughout the doc. The team will be in-touch.

2022-10-10 12:42 UTC, maheshbasnet089 commented
The links are updated I guess . Please do check

On Mon, 10 Oct 2022, 5:44 pm Rick M, ***@***.***> wrote:

> Just the file name and links throughout the doc. The team will be in-touch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/wstg/pull/979#issuecomment-1273207122>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQXRZ3SSZKQFFGQLOQ3HIH3WCQAJBANCNFSM6AAAAAARACRE7Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-10 13:05 UTC, kingthorin commented
They haven’t but we also haven’t finalized the file name :wink:

2022-10-10 13:38 UTC, maheshbasnet089 commented
Are u talking about word list and references link or wot ?

On Mon, 10 Oct 2022, 6:50 pm Rick M, ***@***.***> wrote:

> They haven’t but we also haven’t finalized the file name 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/wstg/pull/979#issuecomment-1273285919>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQXRZ3S4KICH4P52TPXMQNLWCQIBNANCNFSM6AAAAAARACRE7Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-10 13:45 UTC, kingthorin commented
I’m talking about links throughout the guide as I’ve mentioned multiple times. However, there’s no point trying to address it until the team has agreed on the file name.

2022-11-22 15:53 UTC, rejahrehim commented on document/6-Appendix/C-Fuzzing.md
> +
Can we include Fuzzing options with ZAP as well ( As we already mentioned some tools, ZAP can't be missed ) 
What you think @kingthorin @ThunderSon

2022-11-22 15:58 UTC, rejahrehim commented
> Well all the suggestions need to be applied, assuming you agree with them.
> 
> The file name and references/links will need to be adjusted after @ThunderSon chimes in on naming 😉

`C-Fuzzing.md` would be better as this PR update the page with more details on fuzzing along with the fuzz vectors.

2022-11-22 16:12 UTC, kingthorin commented on document/6-Appendix/C-Fuzzing.md
> +
That would definitely make sense. @maheshbasnet089 are you up for adding/covering that?

2023-04-17 01:51 UTC, kingthorin commented
@maheshbasnet089 do you intend to finish this?

2023-04-17 05:10 UTC, maheshbasnet089 commented
added about zap

2023-04-28 03:13 UTC, maheshbasnet089 commented
Any updates to be done Or are u merging it ?

2023-04-29 14:35 UTC, kingthorin commented
@maheshbasnet089 i think it’s done. I need to read through the whole thing one last time. I’ll try to get it tackled this weekend.

2023-04-29 15:00 UTC, maheshbasnet089 commented
> @maheshbasnet089 i think it’s done. I need to read through the whole thing one last time. I’ll try to get it tackled this weekend.

Okay sir

2023-05-02 15:50 UTC, kingthorin approved these changes

2023-05-02 15:50 UTC, merged